### ISSUE TITLE
Temporary data is not pruned

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1004]
Nanoc does not remove unused entries from data files in the `tmp/` directory.

These files tend to grow over time and will consume more and more memory, as they’re always fully loaded into memory.

**Comment by ddfreyne** [comment]
A solution that seems obvious to me at the moment is to *not* load data (checksums, compiled content, and dependencies) for items and layouts that don’t exist anymore.

**Comment by ddfreyne** [comment]
#1013 fixes the issue for the compiled content cache. Checksums still need to be pruned. Dependencies are already taken care of.

**Comment by connorshea** [comment]
👏 thanks @ddfreyne :D

**Comment by ddfreyne** [comment]
Checksums are pruned as of #1027, so this issue is resolved.
