### ISSUE TITLE
--verbose table formatting is off

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1005]
On sites that take long to compile, the format of the table outputted by `compile --verbose` is off:

```
               | count    min    avg    max     tot
---------------+-----------------------------------
md_to_html_ext |  2396  0.00s  0.00s  0.01s   0.32s
           erb |  2514  0.00s  0.18s  1.18s  462.42s
     redcarpet |  2396  0.00s  0.01s  0.28s  30.60s
          sass |     2  0.39s  2.19s  4.00s   4.38s
```

**Comment by connorshea** [comment]
This is the relevant method: https://github.com/nanoc/nanoc/blob/63fe7e79dc4f8ceefb8cfd0f244503033e640c27/lib/nanoc/cli/commands/compile.rb#L227

**Comment by connorshea** [comment]
Should it use a terminal table generation gem, or is that excessive for this? :)

Regardless, it should probably allow for an arbitrary length.

**Comment by connorshea** [comment]
@ddfreyne I'd like to contribute a fix for this, should we make it dynamically resize somehow or just update it to fit, e.g. 1000.00s?

**Comment by ddfreyne** [comment]
@connorshea I’m OK with either! Dynamically resizable would be nice, though.

Preferably without an external table generation gem. I prefer to avoid adding a dependency unless necessary, and even then I’ll prefer reimplementing something in Nanoc to pulling in a dependency.

**Comment by ddfreyne** [comment]
(You might be interested in https://github.com/nanoc/nanoc/blob/master/lib/nanoc/checking/runner.rb#L115 for inspiration)
