### ISSUE TITLE
Calling nanoc from rake fails when using rbenv to manage Rubies

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1006]
When rake calls `bundle exec nanoc` compilation fails because the `$LOAD_PATH` is truncated.

### Steps to reproduce

1. Install rbenv and ruby-build
1. ` rbenv install 2.3.3`
1. `git clone https://github.com/agross/nanoc-rake-rbenv.git`
1. `cd nanoc-rake-rbenv`
1. `rbenv local 2.3.3`
1. `gem install bundler && bundle`
1. `bundle exec nanoc` => works
1. `bundle exec rake` => fails

### Expected behavior

I expect this to work the same as running `bundle exec nanoc` from the command line:

```ruby
task :default do
  sh(*%w(bundle exec nanoc))
end
```

### Actual behavior

My initial debugging showed that due to https://github.com/nanoc/nanoc/commit/2643931feee7aeea9e99b552178db537facfb677 calling ` Bundler.require` the `$LOAD_PATH` is truncated to no longer include nanoc. I couldn't find any documentation why `Bundler.require` (which calls `Bundler.setup` which cleans the `$LOAD_PATH`) removes entries.

### Details

Not sure if this is a bug in nanoc, rbenv or something else. The same setup works without rbenv or when rbenv uses system ruby (`rbenv local system && bundle exec rake`)

**Comment by ddfreyne** [comment]
It seems like `Bundler.require` indeed kicks out stuff out of the `LOAD_PATH`. Bizarre! I’ll need to continue investigating to find out more.

**Comment by agross** [comment]
Some further investigation shows that adding `Bundler.with_clean_env` fixes it:

```ruby
task :default do
  Bundler.with_clean_env do
    sh(*%w(bundle exec nanoc))
  end
end
```

My guess is that it's not a bug in nanoc or bundler or rbenv, but rather PEBKAC. What do you think?

**Comment by ddfreyne** [comment]
I feel that the bug is either in Bundler or the way it’s used, but I can’t quite tell how.

I’ll close it for the time being because a fix (or workaround?) is known, and I believe it is not something that Nanoc can fix.
