### ISSUE TITLE
Something eats line breaks in metadata

### ISSUE THREAD

**Issue by anton-tsyganenko** [nanoc/nanoc#1026]
I add pieces of code, that i want to be in head of the page to metadata like this:
```
head: >
      <meta name="description" content="description of this page">
      <style>/*here goes
      some multi-line
      styles only needed
      on this page*/</style>
```

and add the following code to the layout:
```
<meta name="generator" content="Nanoc <%= Nanoc::VERSION %>">
<% if @item[:head] %><%= @item[:head] %>
<% end %></head>
```

but when nanoc compiles it, I get spaces instead of line breaks:
```
<meta name="generator" content="Nanoc 4.4.4">
<meta name="description" content="description of this page"> <style>/*here goes some multi-line styles only needed on this page*/</style>

</head>
```

**Comment by ddfreyne** [comment]
Replace the `>` (indicating folded style) with `|` (indicating literal style). In literal style, the line breaks will not be converted into spaces, while in folded, they will:

```yaml
head: |
      <meta name="description" content="description of this page">
      <style>/*here goes
      some multi-line
      styles only needed
      on this page*/</style>
```

See the [Scalar](http://www.yaml.org/spec/1.2/spec.html#id2760844) section of the YAML spec for details.
