### ISSUE TITLE
:pre snapshot not created for non-laid out items

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1064]
For an item whose compilation rule does not contain a `layout` call, a `:pre` snapshot is no longer being created.

Potentially caused by #1041.

**Comment by sunshineco** [comment]
Thanks for filing this issue, Denis.

For completeness and as an aid for readers, see the original [problem report](https://groups.google.com/d/msg/nanoc/MMO2pHyhjvc/Er-gycygAwAJ) for additional context.
