### ISSUE TITLE
@item.binary? no longer works

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1068]
I noticed when upgrading from 4.5.2 to 4.5.3 that ```@item.binary?``` no longer works inside the Rules file. It was removed in commit 764bc69d448e479afbf757c06096bb9a016492af 

I assume this is not intentional as it is a breaking change and it's still documented as working. But we should either document the change or, more likely, restore the method (and add a test for it...).

**Comment by ddfreyne** [comment]
`@item` never had a `#binary?` method, but `@item_rep` did—and it still does (see https://github.com/nanoc/nanoc/blob/764bc69d448e479afbf757c06096bb9a016492af/lib/nanoc/base/views/item_rep_view.rb#L77-L79), even though its implementation has changed in the commit you linked to, 764bc69d448e479afbf757c06096bb9a016492af.

`Item` and `ItemRep` are both internal classes and not part of the public API.

**Comment by Fjan** [comment]
Ok, in that case the documentation should be updated, it's still documented here:
https://nanoc.ws/doc/reference/variables/

**Comment by ddfreyne** [comment]
Correct… I’ve reported that as nanoc/nanoc.ws#192

**Comment by Fjan** [comment]
Ok, I'll work around it, but it was very useful to have a method that indicates whether the source asset is binary, for example:
```filter(:erb) unless item.binary?```
 And I'm probably not the only one who used it (as it was a documented), so you still might want to consider adding it back to avoid breaking things for other people.

**Comment by ddfreyne** [comment]
Oh, I am mistaken… `@item.binary?` *does* exist, and it works in Nanoc 4.5.3 as well.

Can you elaborate on how it fails for you?

**Comment by Fjan** [comment]
Ok, I see that it works one of my other projects. Might be problem with a monkey patch gone wrong, sorry, I'll reopen after I've researched it and I can reproduce it consistently.

**Comment by Fjan** [comment]
As an side, this is what no longer works in 4.5.3:
```Nanoc::Int::NotificationCenter.on(:compilation_started) {|ir| Trans::set_language_from_id(ir.item.identifier) unless ir.binary?}```
So I guess something changed as ```ir.binary?``` and ```ir.item.binary?``` no longer exist but I'll figure out another way to do it.

**Comment by ddfreyne** [comment]
The notifications are part of a private API and have indeed changed in 4.5.3. (Anything in `Nanoc::Int` is private.) `Item` and `ItemRep` both no longer have `#binary?`.

What does `Trans::set_language_from_id` do? Perhaps I can help you find an alternative that does not require a private API.

**Comment by Fjan** [comment]
The site serves multiple languages so it simply sets a language variable based on the directory name in the identifier (/en/ would be English, /fr/ French, etc), and that is later picked up by translation functions. (The site uses the ```:symbol.t``` convention, the .t method is defined on the Symbol class to get the translation from a translation library). Setting the language inside the Rules file proved problematic because the translation functions are also needed in the layout and in the partials that generate menus. 

I've already found workaround but it's still using the internal notifications API, so a suggestion to do this another way would be welcome.

**Comment by ddfreyne** [comment]
Is this language variable a global? If so, you will likely run into issues, as Nanoc does’t give guarantees about the order in which items are compiled, and can also suspend and resume compilation of an item if needed. When `Trans::set_language_from_id` is called for one item, but Nanoc then resumes compiling another item, the language of the other item might be incorrect. I am (slowly) working towards making Nanoc multi-threaded, which will make this effect even more visible.

My suggestion would be to have not have `:sym.t` but `t(:sym)` so that it can access the environment, and specifically `@item`, in order to determine the language needed for the translation:

```ruby
def lang_of_item
  # returns "en" or "nl" or so
  @item.identifier.to_s.…
end

def t(sym)
  # translate sym based on lang_of_item
  # …
end
```

**Comment by Fjan** [comment]
I was afraid you were going to say that. Our entire code base (hundreds of pages), including the Rails code base, uses the :symbol.t convention, and it's what our translators are familiar with, so changing to an imperative style t(:sym) would be a major undertaking.

**Comment by ddfreyne** [comment]
You could use fiber-local variables (e.g. `Thread.current[:lang]`) to store the current language. That’ll persist between fibers being suspended and resumed. This way, you could have a filter that calculates the language for the current item and stores it in a fiber-local var, without having to rely on notifications.

(There are not thread-local but fiber-local—the naming is confusing.)

**Comment by Fjan** [comment]
Great, thanks, I'll try that.

**Comment by ddfreyne** [comment]
With Nanoc 4.6, you can also capture the language of an item and reuse that later. For instance:

```ruby
# captures the language (nl) for the current item
content_for(:language, 'nl')
```

```ruby
<!-- fetches the captured content -->
<p>The language of the current item is <%= content_for(@item, :language) %>.</p>
```

**Comment by Fjan** [comment]
Ok thanks. But deriving the language again is as simple as a regex on the item name in our case, the problem is that the language sets a global (or class level) variable, so it is important to know when the item at hand switches so we can reset it. Anyway, the current use of the internal ```NotificationCenter.on(:compilation_started)``` works fine in 4.6, but when I have some time I'll try out your suggestion to use fiber-local variables to prevent future issues with context switching.

**Comment by ddfreyne** [comment]
Ah, my mistake. The problem with the need for a global is still present...

My suggestion would be to modify `Symbol#t` so that it reads from a fiber-local variable.
