### ISSUE TITLE
Store temp data per output directory

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1070]
See https://github.com/nanoc/nanoc/pull/1069#issuecomment-272901414.

The temporary data ideally needs to be stored per output directory, rather than per environment.

The current approach (storing only one set of temporary data) is correct, but yields sub-optimal performance.

**Comment by Fjan** [comment]
As mentioned in the comment on #1069, avoiding recompilation can probably only be achieved if the output directories for each environment are completely separate (not the same and not in each others hierarchy). This is probably true for most use cases. 

The simplest implementation is probably to invalidate the tmp directory for users that have at least one duplicate output directory, and then restore https://github.com/nanoc/nanoc/commit/a8e116098002d709aa40d393a4c1d4087dc56049

**Comment by ddfreyne** [comment]
@Fjan A fix is in #1071. There’s no explicit invalidation going on, as it’s not necessary.
