### ISSUE TITLE
item[:filename] is nil for .yaml files

### ISSUE THREAD

**Issue by igorspasic** [nanoc/nanoc#1086]
item[:filename] is nil for .yaml files on nanoc 4.6.1

### Steps to reproduce

1. Add `foo.yaml` anywhere inside content.
2. In pre-processor block, iterate items and: `print item[:filename]`
3. The filename will be nil

### Expected behavior

I expect filename attribute for this yaml item to be set. `identifier` is set.

### Actual behavior

Filename attribute of an yaml item is not set.

**Comment by igorspasic** [comment]
I am doing now this in my preprocessor block

```
  @items.each do |item|
    # TODO
    # fix missing filename attribute
    if (item[:filename] == nil) then
      item[:filename] = "content" + item.identifier
      print item[:filename]
    end

```
Ugly :)

**Comment by ddfreyne** [comment]
The `:filename` attribute is an alias for `:content_filename`, which will be nil if there is no content file. You can instead use `:meta_filename`.

This is missing from the documentation. Will fix!

**Comment by ddfreyne** [comment]
I’ve created nanoc/nanoc.ws/issues/196 to track this.
