### ISSUE TITLE
Building conventions into nanoc compilation

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1088]
Rather a question than a bug, but I still find it hard to wrap my head around nanoc 4's compilation and internal data model. I know that I might be using private APIs, but to be frank the public API is not enough for my use cases (that all worked great with 3.x 😃). 

I would like to extend nanoc's `ItemWithRepsView` such that it's easy to find an associated sidebar image for the compiled item at hand.

```ruby

module Nanoc
  class ItemWithRepsView
    def sidebar_image
      identifier = "/assets/images/articles#{self.identifier.without_ext}.*"

      image = @context.items[identifier]
      return nil unless image
      self.class.new(image, @context)
    end
  end
end
```

The returned `ItemWithRepsView` should then be useable from the layout (haml, markdown, etc.) to render HTML.

```haml
- if @item.sidebar_image
  = @item.sidebar_image.path(rep: sidebar)
```

**The issue I'm seeing is that the `path` is always `nil`.**

If I `@context.reps[image].find { |r| r.name == :sidebar }.path` inside my helper, the path correctly points to the output directory.

I wonder why that is and how I can get around that limitation. Thanks!

**Comment by ddfreyne** [comment]
Hi!

The view classes (such as `ItemWithRepsView`) are not intended to be modified or subclassed, and so the code you’ve provided has no guarantees of working.

My recommendation would be a `sidebar_image` helper:

```ruby
def sidebar_image_for(item)
  @items["/assets/images/articles#{item.identifier.without_ext}.*"]
end
```

Such a function would be used in a similar way:

```haml
- if sidebar_image_for(@item)
  = sidebar_image_for(@item).path(rep: sidebar)
````

**Comment by agross** [comment]
Thanks. How would you organize helpers such that they won't pollute every object during runtime?

**Comment by ddfreyne** [comment]
@agross I personally find it nice to define the functions at the top level and not care about potential clashes (it won’t interfere with methods defined on objects).

If that’s not an option, an alternative could be to have a module with module functions on it, e.g.

```ruby
module NanocWs
  module_function

  def sidebar_image_for(item)
    @items["/assets/images/articles#{item.identifier.without_ext}.*"]
  end

  # … other methods here …
```

You can then use it as

```haml
- if NanocWs.sidebar_image_for(@item)
  = NanocWs.sidebar_image_for(@item).path(rep: sidebar)
```

or, after `include NanocWs`, call it without module name, as before:

```haml
- if sidebar_image_for(@item)
  = sidebar_image_for(@item).path(rep: sidebar)
```

**Comment by agross** [comment]
I didn’t know about `module_function`, that's interesting.

Unfortunately, for the "non-included" case `NanocWs.sidebar_image_for(@item)`, `@items` appears to be `nil`. Any ideas (other that passing `@items` to `sidebar_image_for`?

**Comment by ddfreyne** [comment]
> Unfortunately, for the "non-included" case `NanocWs.sidebar_image_for(@item)`, `@items` appears to be `nil`. Any ideas (other that passing `@items` to `sidebar_image_for`?

Ahhh, correct. You’ll have to pass in `@items`:

```
module NanocWs
  def self.sidebar_image_for(item, items)
    items["/assets/images/articles#{item.identifier.without_ext}.*"]
  end

  # … other methods here …
end
```

… or stick with the `include` approach (which is IMO nicer).

**Comment by agross** [comment]
> or stick with the include approach (which is IMO nicer).

I've had it this way with Nanoc 3.x. Unfortunately my methods are now stuck on every object, even unrelated ones:

```rb
String.new.methods.grep /list/
[
    [ 0]       advisory_board_list(*items)       String (Helpers::Lists)
    [ 1]              article_list()             String (Helpers::Lists)
    [ 2]                 book_list()             String (Helpers::Lists)
    [ 3]    consulting_quotes_list()             String (Helpers::Lists)
    [ 4]       interviews_all_list()             String (Helpers::Lists)
    [ 5] interviews_customers_list()             String (Helpers::Lists)
    [ 6]    interviews_inline_list()             String (Helpers::Lists)
    [ 7]  interviews_trainers_list()             String (Helpers::Lists)
    [ 8]          open_source_list()             String (Helpers::Lists)
    [ 9]                 sort_list(list, &block) String (Helpers::Lists)
    [10]              trainer_list()             String (Helpers::Lists)
    [11]      training_quotes_list()             String (Helpers::Lists)
    [12]                video_list()             String (Helpers::Lists)
]
```

IMHO that's far from nice. It's freaking me out that I might overwrite some method on some object I don't even know of.

This is why I want to model the `xxx_for` methods as separate objects/classes/containers with explicit input (beyond what's generally available during Nanoc rendering).

**Comment by ddfreyne** [comment]
`include` won’t cause any methods to be overwritten. For example:

```ruby
module Foo
  def reverse
    'hah fooled'
  end
end

include Foo

puts 'hello'.reverse
# => olleh
```
