### ISSUE TITLE
"nanoc check --list" duplication

### ISSUE THREAD

**Issue by sunshineco** [nanoc/nanoc#1089]
`nanoc check --list` emits:

~~~
Available checks:
  css
  external_links
  external_links
  html
  internal_links
  internal_links
  mixed_content
  stale
~~~

Notice the doubled `external_links` and `internal_links`. Presumably, the output was intended to show short forms `elinks` and `ilinks` instead, like this:

~~~
Available checks:
  css
  elinks
  external_links
  html
  ilinks
  internal_links
  mixed_content
  stale
~~~

**Comment by ddfreyne** [comment]
This is an issue in ddplugin: ddfreyne/ddplugin#3.

**Comment by ddfreyne** [comment]
ddplugin 1.0.1 fixes this!
