### ISSUE TITLE
'check' should accept hyphenated check names

### ISSUE THREAD

**Issue by sunshineco** [nanoc/nanoc#1090]
_(This is a very minor enhancement request.)_

The nanoc command-line interface uniformly uses hyphens for multi-word commands and options (`create-site`, `show-plugins`, etc.). Names given to the `check` command, however, use underscores (`external_links`, `internal_links`, `mixed_content`), which is inconsistent with the rest of the command-line API and increases cognitive load since one has to remember when to use hyphens and when to use underscores.

Implementation details aside, it might be helpful for `nanoc check` to accept hyphenated names, as well. (Listing names in hyphenated, rather than underscore, form would be nice too.)

**Comment by ddfreyne** [comment]
Definitely a good suggestion—I’m unsure why I initially decided to go with snake_case rather than kebab-case here.

**Comment by ddfreyne** [comment]
Migrated to nanoc/features/issues/13
