### ISSUE TITLE
add 'nanoc clean' command

### ISSUE THREAD

**Issue by sunshineco** [nanoc/nanoc#1092]
Akin to `make clean`, it would be nice if nanoc knew how to clean up after itself, hence the proposed `nanoc clean`. While it's true that one can employ ad-hoc cleanup methods (`rm -fr crash.log output tmp`, `git clean -dXf`, etc.) an officially supported method would be easier to document and more amenable to scripting.

Aside from the obvious build products (`output` and `tmp`), one would expect other nanoc-specific detritus (`crash.log`, `output.diff`, and any others) to be removed as well.

**Comment by ddfreyne** [comment]
Migrated to nanoc/features/issues/9.
