### ISSUE TITLE
Erubi support

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1096]
It would be nice to get nanoc support for [Erubi](https://github.com/jeremyevans/erubi): it should be faster and have a reduced memory footprint compared to ERB and Erubis.

I took a quick look at the code, and while adding a filter is trivial it seems it would take some effort to make it work properly with the nanoc capturing helpers.

**Comment by ddfreyne** [comment]
I haven’t taken a very close look, but running `Erubi` with `bufvar: '_erbout'` should work with the capturing helper.

**Comment by ddfreyne** [comment]
Migrated to nanoc/features/issues/8.

**Comment by Fjan** [comment]
Ok, thanks. As an aside, I noticed their claim of 86% faster HTML escaping is based on simply replacing a chained gsub by CGI.escapeHTML (https://github.com/jeremyevans/erubi/commit/ad418917a5c75e969f1bbf213c1a95b84c4c56e8)

Nanoc is doing a chained gsub as well [here](https://github.com/nanoc/nanoc/blob/master/lib/nanoc/helpers/html_escape.rb) so we could easily copy/replace that code with CGI.escapeHTML to get that same speedup.
