### ISSUE TITLE
Nanoc::Spec::HelperHelper introduced an ordering requirement in 990d6963

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1110]
By making `@items` immutable in https://github.com/nanoc/nanoc/commit/990d696398202886d8dfa5891ad6e725f74d2150#diff-4a5a2171683f37ed95183db55a9b2e97L34, an item created in a test context does not see future created items. (By "see" I mean the first item's `@context.items` includes only itself, the second item's `@context.items` includes the first and itself, etc.)

### Steps to reproduce

1. Create a `test.rb`
    ```ruby
    require 'nanoc'
    require 'nanoc/spec'

    class TestMe
      def described_class
        self.class
      end

      include Nanoc::Spec::HelperHelper

      def doit
        first = ctx.create_item('item', {}, '/index.html')
        second = ctx.create_item('item2', {}, '/index2.html')

        puts Nanoc::VERSION
        puts first.instance_variable_get(:@context).items.size
        puts second.instance_variable_get(:@context).items.size
      end
    end

    TestMe.new.doit
    ```
2. `ruby test.rb` with 4.6.1 or 4.6.2 installed.

### Expected behavior

Output:

```
4.6.2
2
2
```

(First item does know about the second item)

### Actual behavior

When run with 4.6.2:
```
4.6.2
1
2
```

(First item doesn't know about the second item)

When run with 4.6.1:
```
4.6.1
2
2
```

(First item does know about the second item)

### Details

I use `Spec::HelperHelper` extensively to simulate different items before running tests. For example I create two items and call a method on the first (the rspec `subject`). With nanoc 4.6.2 the item's context will not include other items created after the `subject`.

**Comment by ddfreyne** [comment]
Yeah, this one’s tricky to solve while keeping the API the same. I propose changing the API so you can do

```
ctx.create_item('item', {}, '/index.html')
ctx.create_item('item2', {}, '/index2.html')

first = items['/index.html']
second = first = items['/index2.html']
```

I like the idea of `create_item` *not* modifying the context, so I’d like to keep it that way.

**Comment by agross** [comment]
Any functional programmer likes immutability. Unfortunately it's not Ruby's strong side, but that's why there is Elixir. Unfortunately, Elixir does not have nanoc ;-)

I'm not sure mixing both styles is beneficial here. Perhaps we need a special mutable collection for testing (and use the one deprived of `:<<` in production).

Also, what about `ctx` returning a new context?

```
ctx.create_item(...)
   .create_item(...)

ctx.items['/index.html'] # This is the point there the item is created with both items in its collection
```

**Comment by ddfreyne** [comment]
I assume you mean something like this:

```ruby
ctx = ctx.create_item(…)

ctx.items['/index.html']
```

otherwise, you’d still be modifying `ctx`!

I’m okay with code that mutates objects, as long as it’s explicit in doing so. The old `#create_items` implementation wasn’t explicit in its mutation, and that’s one of the reason why it broke.

I have a slight preference for the API that has mutation, because it’s simpler.

**Comment by agross** [comment]
What I meant is that `ctx.create_item` returns a modified copy of itself.

```
ctx.create_item() # creates a copy of ctx (#1)
   .create_item() # creates copy #2, which has all modifications of #1
```

This way the original `ctx` remains untouched, and `#1` contains only the first item, and `#2` contains the first and the second item.

**Comment by ddfreyne** [comment]
I don’t feel that a purely function approach buys us much, and it makes things more complicated. This is especially true in tests, where the amount of set-up logic is typically small and straightforward.

I like your idea of chaining, though. Perhaps this could work:

```ruby
ctx
  .create_item(…)
  .create_item(…)

first = ctx.items['/first.html']
second = ctx.items['/second.html']
```

If, for some reason, having a mutable `ctx` is not desired or not an option, it’s always possible to create a separate one that will not be mutated, with `HelperContext.new`.

**Comment by ddfreyne** [comment]
A potential fix is in #1112.

**Comment by agross** [comment]
I'm still in the middle of adjusting my specs, but this looks good to me. Even made the specs a bit clearer!

**Comment by agross** [comment]
👍 Thank you!
