### ISSUE TITLE
Clearer mutual dependency error

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1111]
The `RecursiveCompilation` error suffers from a few problems:

* It is badly named (`MutualDependency` or `DependencyCycle` would be more clear).
* It does not provide information about which rep depends on which rep.
* It lumps all dependency cycles together.

A better error message would be something along the lines of this:

```
DependencyCycle: 5 item representations mutually depend on each other

    item /foo.md, rep :default, depends on
    item /bar.md, rep :default, which depends on
    item /qux.md, rep :default, which depends on
    item /foo.md, rep :default (first item rep above)

    item /donkey.md, rep :default, depends on
    item /giraffe.md, rep :default, which depends on
    item /donkey.md, rep :default (first item rep above)
```

or

```
…

    (a) item /foo.md, rep :default, depends on
    (b) item /bar.md, rep :default, which depends on
    (c) item /qux.md, rep :default, which depends on (a)
```

Note that

* a dependency cycle error can occur because there is more than one dependency cycle. (In the first example above, two dependency cycles occur.)

* there can be item reps that are not in a cycle, but still cannot be compiled because they have a dependency on an item rep in the cycle.

**Comment by ddfreyne** [comment]
Suggested solution:

1.  Replace

    ```ruby
    raise Nanoc::Int::Errors::RecursiveCompilation.new(graph.vertices)
    ```

    in `item_rep_selector.rb` with

    ```ruby
    raise Nanoc::Int::Errors::DependencyCycles.new(graph.cycles)
    ```

2.  Add `DirectedGraph#cycles` (returns a list of cycles, represented as an array)

3.  Rename `Nanoc::CLI::ErrorHandler#resolution_for` to `Nanoc::CLI::ErrorHandler#details_for`

4.  Make `Nanoc::CLI::ErrorHandler#details_for` print the cycles.

All of this with proper tests.

**Comment by denis-soundcloud** [comment]
Simpler algorithm: Pick a random node from the resulting graph, and follow edges until you find a cycle. Remove all visited nodes from the graph. Repeat.
