### ISSUE TITLE
Dependence on item's compiled_content causes reverse dependency

### ISSUE THREAD

**Issue by blinry** [nanoc/nanoc#1119]
An item which depends on another item's compiled content seems to result in a reverse dependency.

### Steps to reproduce

Setup:

```
$ cat Rules 
#!/usr/bin/env ruby

compile '/**/*.md' do
  filter :erb
  filter :kramdown
  layout '/default.*'
end

route '/**/*.md' do
  if item.identifier =~ '/index.*'
    '/index.html'
  else
    item.identifier.without_ext + '/index.html'
  end
end

compile '/**/*' do
  write item.identifier.to_s
end

layout '/**/*', :erb
$ cat content/a.md 
---
title: a
---

a content
$ cat content/b.md 
---
title: b
---

b content
$ cat content/index.md
<% items.each do |i| %>
    <% if i[:title] %>
        <%= i.compiled_content %>
    <% end %>
<% end %>
```

Execution:

```
$ touch content/a.md
$ nanoc --verbose
Loading site… done
Compiling site…
   identical  [0.00s]  output/b/index.html
   identical  [0.04s]  output/a/index.html
   identical  [0.01s]  output/index.html
```

### Expected behavior

b.md is not recompiled, because it has no dependency on a.md or index.md.

### Actual behavior

b.md is recompiled.

### Details

This is another one where I'm not sure if it's a bug. It is at least unexpected to me, and causes recompilation of all items in a blog each time one of the articles is changed if a feed is present. Please tell me if you'd prefer to have issues like these discussed somewhere else. Thanks!

**Comment by ddfreyne** [comment]
I can’t reproduce this in Nanoc 4.6.4. Is this the version you’re using?

```
% nanoc co --verbose
Loading site… done
Compiling site…
      create  [0.09s]  output/a/index.html
      create  [0.01s]  output/b/index.html
      create  [0.00s]  output/index.html

Site compiled in 0.14s.

% touch content/a.md

% nanoc co --verbose
Loading site… done
Compiling site…
   identical  [0.07s]  output/a/index.html
        skip  output/b/index.html
        skip  output/index.html
```

**Comment by ddfreyne** [comment]
What does `nanoc show-data` show you w.r.t dependencies for a.md and b.md?

**Comment by blinry** [comment]
> I can’t reproduce this in Nanoc 4.6.4. Is this the version you’re using?

Yep!

```
$ nanoc show-data
[...]

item /a.md depends on:
  [ layout ] (r___) /default.html

item /b.md depends on:
  [ layout ] (r___) /default.html

item /index.md depends on:
  [   item ] (_ac_) /a.md
  [   item ] (_ac_) /b.md
  [ layout ] (r___) /default.html
```

Looks reasonable, I think?

In your own attempt, shouldn't index.md be recompiled (because it checks for both items' title attribute)? Just to make sure, here's the site I used: https://github.com/blinry/nanoc-test

**Comment by ddfreyne** [comment]
Ahh, my bad—I had `content/index.html` rather than `content/index.md`, which made it not be filtered with `:erb`. I can reproduce what you’re seeing now.

I see this:

```
=== Item dependencies =======================================================

Legend:
  r = dependency on raw content
  a = dependency on attributes
  c = dependency on compiled content
  p = dependency on the path

item /a.md depends on:
  [ layout ] (r___) /default.html

item /b.md depends on:
  [ layout ] (r___) /default.html

item /index.md depends on:
  [   item ] (_ac_) /a.md
  [   item ] (_ac_) /b.md
  [ layout ] (r___) /default.html
```

```
=== Item representation outdatedness ========================================

item /a.md, rep default:
  is outdated: The attributes of this item have been modified since the last time the site was compiled.

item /b.md, rep default:
  is not outdated

item /index.md, rep default:
  is outdated: This item uses content or attributes that have changed since the last time the site was compiled.
```

`b.md` is recompiled because `index.md` is recompiled, and it needs the compiled content of `b.md`. That’s expected, but because `b.md` is not considered as outdated, the cached compiled content will be used, so it should be quite fast. You can see this with `--debug`:

```
% nanoc co --debug
…
*** Suspended compilation of <Nanoc::Int::ItemRep name="default" raw_path="output/index.html" item.identifier="/index.md">: The current item cannot be compiled yet because of an unmet dependency on the “/b.md” item (rep “default”).
*** Started compilation of <Nanoc::Int::ItemRep name="default" raw_path="output/b/index.html" item.identifier="/b.md">
*** Used cached compiled content for <Nanoc::Int::ItemRep name="default" raw_path="output/b/index.html" item.identifier="/b.md"> instead of recompiling
*** Ended compilation of <Nanoc::Int::ItemRep name="default" raw_path="output/b/index.html" item.identifier="/b.md">
…
```

**Comment by blinry** [comment]
Oh, I see. I also understand the reasoning.

Maybe it would make sense to display "cached" instead of "identical" in the compilation log in this case, to differentiate between the costly recompilation and the cached case? This would maybe avoid some confusion. But the `--debug` option is also very helpful!

Thanks, Denis, my favourite software maintainer! :sparkles:

**Comment by ddfreyne** [comment]
> Maybe it would make sense to display "cached" instead of "identical" in the compilation log in this case

Absolutely! I opened #1120 for that.
