### ISSUE TITLE
Show “cached” rather than “identical” when using cached content

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1120]
Nanoc currently show

* `skip` if the item rep is not processed at all (no need)
* `identical` if the item rep is either recompiled, or cached compiled content is used

Showing `cached` rather than `identical` when the cached compiled content is used, will make it more clear that the item rep is not recompiled.

**Comment by gpakosz** [comment]
What about `identical (cached)` ?

**Comment by ddfreyne** [comment]
@gpakosz That could work, but I fear it might be a bit long.

**Comment by ddfreyne** [comment]
Migrated to nanoc/features/issues/12.
