### ISSUE TITLE
Documentation issue "Using the datasource"

### ISSUE THREAD

**Issue by rkuebert** [nanoc/nanoc#1192]
Hi,

I just included a data source in my project but had an issue with the documentation. I am not sure if the behaviour regarding `find_all` patterns changed and the documentation just does not reflect it yet.

Nanoc and ruby version:
Nanoc 4.4.7 © 2007-2017 Denis Defreyne.
Running ruby 2.3.3 (2016-11-21) on x86_64-linux-gnu with RubyGems 2.5.2.

The documentation page I am referring to is https://nanoc.ws/doc/guides/using-external-sources/#using-the-data-source.

The following helper method always returns 0 items:

```
def sorted_employees
  employees = @items.find_all('/external/hr/employees/*')
  employees.sort_by do |e|
    [ e[:last_name], e[:first_name] ]
  end
end
```

Replacing the line with `@items.find_all(...)` with either one of the following gives the desired result:

```
employees = @items.find_all("/external/hr/employees/**/*")
employees = @items.find_all(%r{/external/hr/employees/})
```

Cheers

Roland

**Comment by ddfreyne** [comment]
Hi, thanks for reporting!

The behavior of the code depends on the `identifier_type` and the `string_pattern_type`, and the documentation doesn’t clearly state which ones are used. (The `legacy` ones are used, but that shouldn’t be the default!)

Action points for me:

* update the documentation to use `identifier_type: full` and `string_pattern_type: glob`
* clearly state which `identifier_type` and the `string_pattern_type` is used
* find out which other pieces of documentation (if any) implicitly rely on legacy identifier type/string pattern type.

**Comment by ddfreyne** [comment]
The following changes to the documentation should take care of this issue:

https://github.com/nanoc/nanoc.ws/commit/b35168d32391f8099fa3e501c30c7eb00a6a8120
https://github.com/nanoc/nanoc.ws/commit/5d044ddf518b06bd87be43d3fe051b79fb55d0e7
https://github.com/nanoc/nanoc.ws/commit/1934d1ef8f2730a11346b425dd5bed4520618e78
https://github.com/nanoc/nanoc.ws/commit/d12b3cedeb9f857fff17c344c110023ed15f08bd
