### ISSUE TITLE
Ability to include sourcemap with sass filter

### ISSUE THREAD

**Issue by ryanjm** [nanoc/nanoc#1200]
I want to be able to generate the sourcemap with sass.

```
compile '/stylesheets/*.scss' do
  filter :sass, syntax: :scss, sourcemap: true
  write item.identifier.without_ext + ".css"
end
```

But, each `compile` is only able to output [one file](https://github.com/nanoc/nanoc/issues/883#issuecomment-229864903) at a time. So I'd like the ability to create a second rule to handle the sourcemap:

```
compile '/stylesheets/*.scss' do
  filter :sass_sourcemap, syntax: :scss
  write item.identifier.without_ext + ".css.map"
end
```

But ([source](https://nanoc.ws/doc/rules/)):

> For every item, Nanoc finds the first matching compilation rule.

So how can Nanoc support this? Is there a way to opt out of the "only first match" rule?

Some people have created custom [filters](https://github.com/nanoc/nanoc/issues/1148#issuecomment-290976898) which also write out their own files, but doesn't seem like a proper solution for Nanoc.

**Comment by ddfreyne** [comment]
It’s true that one filter can only generate one piece of output; in this case, the filter would either return the CSS, or the sourcemap.

As a way around this, for now, you can use multiple representations (in this case I’ve opted for `rep: :sourcemap`):

```
compile '/stylesheets/*.scss' do
  filter :sass, syntax: :scss
  write item.identifier.without_ext + ".css"
end

compile '/stylesheets/*.scss', rep: :sourcemap do
  filter :sass_sourcemap, syntax: :scss
  write item.identifier.without_ext + ".css.map"
end
```

This assumes that the `:sass_sourcemap` filter writes out the sourcemap.

I’ve created nanoc/features/issues/17 to track the idea of filters with multiple output files.

**Comment by ryanjm** [comment]
Thank you. I didn't realize that you could have multiple representations like that. I'll try that out.
