### ISSUE TITLE
Short options clash in builtin commands

### ISSUE THREAD

**Issue by whitequark** [nanoc/nanoc#1202]
E.g. see `nanoc deploy --help`, I've marked the problematic ones with `>`:
```
OPTIONS
>   -C --no-check            do not run the issue checks marked for
                             deployment
    -D --list-deployers      list available deployers
    -L --list                list available locations to deploy to
    -n --dry-run             show what would be deployed
    -t --target=<value>      specify the location to deploy to (default:
                             `default`)

OPTIONS FOR NANOC
>   -C --no-color            disable color
    -V --verbose             make output more detailed
    -d --debug               enable debugging
    -h --help                show the help message and quit
    -l --color               enable color
    -v --version             show version information and quit
    -w --warn                enable warnings
```
Is this known? Is this considered fine? This seems potentially problematic to me, especially in scripts.

**Comment by ddfreyne** [comment]
This isn’t known and it’s not fine!

I checked the current behavior and it’s as follows:

* `nanoc deploy -C` is equal to `nanoc deploy --no-check` 
* `nanoc -C deploy` is equal to `nanoc --no-color deploy`
* `nanoc --no-check deploy` errors (as expected)

The Nanoc CLI pick the most specific option (`-C` becomes `--no-check`), which makes sense, but unfortunately makes it hard to fix this bug without potentially breaking things.

I suggest leaving it as-is, but adding a test to ensure that no such situations arise in the future, and then hopefully fix it properly in 5.0. WDYT?

Denis

**Comment by whitequark** [comment]
Fine by me

**Comment by ddfreyne** [comment]
Found another case:

```
OPTIONS
>   -v --verbose          show more detailed help

OPTIONS FOR NANOC
    -C --no-color         disable color
>   -V --verbose          make output more detailed
    -d --debug            enable debugging
    -e --env=<value>      set environment
    -h --help             show the help message and quit
    -l --color            enable color
>   -v --version          show version information and quit
    -w --warn             enable warnings
```

**Comment by ddfreyne** [comment]
And another one, `nanoc check` (this is the last):

```
OPTIONS
    -L --list             list all checks
    -a --all              run all checks
>   -d --deploy           run checks for deployment

OPTIONS FOR NANOC
    -C --no-color         disable color
    -V --verbose          make output more detailed
>   -d --debug            enable debugging
    -e --env=<value>      set environment
    -h --help             show the help message and quit
    -l --color            enable color
    -v --version          show version information and quit
    -w --warn             enable warnings
```

**Comment by whitequark** [comment]
What about commands added by plugins? If you ever add another global nanoc option that could lead to conflicts.

**Comment by ddfreyne** [comment]
> What about commands added by plugins? If you ever add another global nanoc option that could lead to conflicts.

That’s a good point. I feel that all plugins that add Nanoc commands should have a test that verifies that it does not accidentally override a parent command’s options. That probably means Cri should have built-in support (at least for Rspec) for this kind of test!

**Comment by ddfreyne** [comment]
I’ve created ddfreyne/cri/issues/59 to track progress on a feature in Cri that prevents clashing options.
