### ISSUE TITLE
Site loading skipped

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1211]
Commit https://github.com/nanoc/nanoc/commit/213ba4f88948ddd5de58546862cb939741f67e2e caused a small bug in 4.8.3 that results in the "Loading site..." step being skipped. The "Compiling site..." step now does the loading instead.

### Steps to reproduce

1. in default.rb put ```puts "I'm loading"```
2. nanoc compile

### Expected behavior

(in 4.8.2)
Loading site… I'm loading done
Compiling site…

### Actual behavior

(in 4.8.3)
Loading site… done
Compiling site…
I'm loading

### Details

The line ```site.nil?``` that was removed in the commit apparently implicitly triggered the loading, because restoring it fixes the bug. It would probably be a good idea to make that more explicit in the code.

**Comment by ddfreyne** [comment]
Good catch—I’ve started work on a fix in #1212.

**Comment by ddfreyne** [comment]
The overlap between `#load_site` and `#site` has always bothered me. Looks like I finally got bit by it.

I’ll leave this issue open until I have a proper refactoring that makes this code less brittle, and makes the tests cover this case in a nice way.

**Comment by ddfreyne** [comment]
PR #1213 improves the situation by not making `#load_site` bypassable.
