### ISSUE TITLE
internal_links check fails

### ISSUE THREAD

**Issue by vesaoikonen** [nanoc/nanoc#1218]
After nanoc update the internal_links check fails with error
NameError: uninitialized constant Nanoc::Checking::Checks::InternalLinks::CGI
Did you mean?  Cri
               Nanoc::CLI

Line 56 in internal_links.rb is
     path = CGI.unescape(path)
I changed it (back?) to 
     path = URI.unescape(path)
and then checking seems to work again.

**Comment by ddfreyne** [comment]
There’s a missing `require 'cgi'` in Nanoc. Fix forthcoming.

(The reason why this wasn’t caught earlier is because the automated tests likely indirectly load `cgi`.)

**Comment by ddfreyne** [comment]
Fixed by f94503b8e3a5a7351d34cb5f04ad86f3b14ab92e — unfortunately tricky to test automatically.
