### ISSUE TITLE
Parse error when using four dashes to signal metadata

### ISSUE THREAD

**Issue by denis-soundcloud** [nanoc/nanoc#1222]
Using four dashes to indicate a metadata section leads to a confusing error.

### Expected

A clear error when using four dashes, stating that four dashes are not valid.

### Actual

A weird error:

```
did not find expected node content while parsing a block node at line 2 column 1
```

### Details

The filesystem data source sometimes accepts 3, 4, or 5 dashes, and at other times, accepts only 3 or 5:

* https://github.com/nanoc/nanoc/blob/master/lib/nanoc/data_sources/filesystem.rb#L378
* https://github.com/nanoc/nanoc/blob/master/lib/nanoc/data_sources/filesystem.rb#L382

It should disallow four dashes.

**Comment by ddfreyne** [comment]
CC @BenjaminDebeerst — this’ll be fixed in the 4.8.10 release.
