### ISSUE TITLE
Running Multiple Filters

### ISSUE THREAD

**Issue by HaoZeke** [nanoc/nanoc#1244]
(Summarise the bug in a single line.)

### Steps to reproduce

1. Make an .md file
2. Use pandoc to process the content
3. Try using a layout in handlebars or mustache

### Expected behavior

The site should render correctly.
It does with .erb layouts

### Actual behavior

The html is mangled

```html
&lt;/h1&gt;
&lt;p&gt;
You’ve just created a new Nanoc site. The page you are looking at right now is the home page for your site. To get started, consider replacing this default homepage with your own customized homepage. Some pointers on how to do so:
&lt;/p&gt;
&lt;ul&gt;
&lt;li&gt;
&lt;p&gt;
```

### Details

This is with {{yield}}
When I filter through :erb and change it back to <%= yield %> it works.

I have attempted to use multiple filters for the layout but that causes an error.

```ruby
compile '/**/*.{html,md}' do
    filter :pandoc, args: [
        { from: :markdown, to: :html},
            :table_of_contents,
        ]
    layout '/default.*', :mustache
end
```

```
TypeError: no implicit conversion of Symbol into Hash
```

**Comment by ddfreyne** [comment]
Can you share the `Rules` file that causes this problem?

**Comment by ddfreyne** [comment]
Ahh, the problem is that `{{yield}}` *intentionally* escapes its input. From the Mustache documentation:

> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

I assume the same applies to Handlebars.

**Comment by HaoZeke** [comment]
Oops, my bad..
That works perfectly, for handlebars and mustache!

I'll open a pull request to modify the docs later, the [mustache](https://nanoc.ws/doc/reference/filters/#mustache) layout should be edited to {{{ yield }}}

**Comment by ddfreyne** [comment]
Thanks for notifying! I’ve updated the Mustache/Handlebars documentation already: https://github.com/nanoc/nanoc.ws/commit/814732d3019a58cc2d70f58eab09ee52b0f2c344
