### ISSUE TITLE
Pandoc filter and non-html content generation

### ISSUE THREAD

**Issue by HaoZeke** [nanoc/nanoc#1245]
Pandoc non html outputs are not generated. 

### Steps to reproduce

1. Prepare pandoc markdown file for a beamer presentation
2. Pass the following

```ruby
compile '/slides/**/*.yml /slides/**/*.md' do
 filter :pandoc, args: [
   { from: :markdown, to: :beamer },
   :standalone,
   :mathjax,
   {:slide_level => 2},
 ]
 write item.identifier.without_ext + '.pdf'
 layout '/**/blank.html'
end
```
Where blank.html has nothing but <%= yield %>

### Expected behavior

A beamer presentation pdf.

### Actual behavior

An html file was generated, according to the default layout and rendering the contents as html.

### Details

Isn't the pandoc filter a wrapper around pandoc-ruby which accepts these arguments?

**Comment by ddfreyne** [comment]
If the last instruction of a `compile` rule is *not* `write`, then Nanoc will find a matching `route` rule. In your case, I believe it will write to a HTML file.

Two alternatives:

*   Move `layout` right before `write`:

    ```ruby
    compile '/slides/**/*.yml /slides/**/*.md' do
      filter :pandoc, args: [ . . . . . ]
      layout '/**/blank.html'
      write item.identifier.without_ext + '.pdf'
    end
    ```

* Remove the `layout` call entirely — it doesn’t do anything meaningful:

    ```ruby
    compile '/slides/**/*.yml /slides/**/*.md' do
      filter :pandoc, args: [ . . . . . ]
      write item.identifier.without_ext + '.pdf'
    end
    ```

**Comment by ddfreyne** [comment]
I’ll close this issue now, but feel free to continue the conversation.

**Comment by ddfreyne** [comment]
I’ve added a [Writing/routing pitfalls](nanoc.ws/doc/rules/#writing-routing-pitfalls) section to the Nanoc documentation, which covers this in more detail.

**Comment by HaoZeke** [comment]
Strangely enough, I'm still not getting a pdf.... o.O

Still html.. Here's the full config.. (sorry)

```ruby
#!/usr/bin/env ruby

#
# Pandoc TeX Rules
#

compile '/slides/**/*.yml /slides/**/*.md' do
 filter :pandoc, args: [
   { from: :markdown, to: :pdf },
   :standalone,
   :mathjax,
   {:slide_level => 2},
 ]
 write item.identifier.without_ext + '.pdf'
end


compile '/static/**/main.scss' do
  filter :sass, syntax: :scss
  write item.identifier.without_ext + '.css'
end

passthrough '/statc/js/**/*'

compile '/**/*.html' do
  layout '/default.*'
end

#
# Pandoc Site Rules
#
compile '/**/*.md' do
 filter :pandoc, args: [
   { from: :markdown, to: :html },
   :table_of_contents,
 ]
 layout '/default.*'
end

route '/**/*.{html,md}' do
  if item.identifier =~ '/index.*'
    '/index.html'
  elsif item.identifier =~ '/**/*.pdf'
    '/test.pdf'
  else
    item.identifier.without_ext + '/index.html'
  end
end


compile '/**/*' do
  write item.identifier.to_s
end

layout '/**/*.haml', :haml, format: :html5
layout '/**/blank.pdf.erb', :erb
```

**Comment by HaoZeke** [comment]
Also the above code still doesn't produce the correct file. A pdf is generated in the site root as slide.pdf whereas a slides.pdf (empty) file is generated in the output folder.

**Comment by ddfreyne** [comment]
This won’t behave as expected:

```
compile '/slides/*.yml' '/slides/**/*.md' do
```

You likely want this instead:

```
compile '/slides/*.{yml,md}' do
```

See the [Identifiers and patterns](https://nanoc.ws/doc/identifiers-and-patterns/#patterns) page for details:

> {foo,bar}
> Matches either string in the comma-separated list. More than two strings are possible. For example, /c{at,ub,ount}s.txt matches /cats.txt, /cubs.txt, and /counts.txt, but not /cabs.txt.
