### ISSUE TITLE
The erubi filter does not show the location for compilation errors

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1255]
### Steps to reproduce

1. Create an erb file that parses initially but with an error that will only happen during compilation 
`<%= 'test' # this will parse but breaks at execution time %>`
2. put `filter :erubi` in the Rules file
3. `nanoc compile`
4. the crash output will not show the location of the offending file

### Expected behavior

The crash log should show the item being compiled

### Actual behavior

The crash log shows an incorrect line

### Details

This is trivial to fix, the eval is missing the filename parameter, I will submit a PR shortly.

**Comment by ddfreyne** [comment]
This is fixed in Nanoc 4.8.15 (just released).
