### ISSUE TITLE
How to use a second YAML file?

### ISSUE THREAD

**Issue by fakefarm** [nanoc/nanoc#1267]
Hello, I am new to nanoc and I must say I am thoroughly enjoying it! 

I followed the tutorial and have read the docs regarding data sources but still unsure how to use a second yaml file.  Specifically, I would like to have `resume.yml` be available to `resume.html`

My current implementation is that I put resume content into `nanoc.yaml`. ([view it here](https://github.com/fakefarm/woodall/blob/master/nanoc.yaml#L28)). 

Is there a step by step example for doing something like this?

Thank you!
Dave

**Comment by ddfreyne** [comment]
Hi!

Rename `resume.yml` to `resume.yaml`; this way, `review.html` and `review.yaml` will be considered the same item. Let me know if that works for you!

Also, I prefer to keep GitHub issues only for issues; there’s the [Nanoc Google group](https://groups.google.com/forum/#!forum/nanoc) and the [Nanoc Gitter channel](https://gitter.im/nanoc/nanoc) for support.

Denis

**Comment by fakefarm** [comment]
_Check, check, and check._
That solved it, thank you! And will do.
Dave
