### ISSUE TITLE
URI::InvalidComponentError raised in external link checker

### ISSUE THREAD

**Issue by iay** [nanoc/nanoc#1299]
If you have a sufficiently mangled URI in your content, it's possible to terminate the external link checker with an exception.

### Steps to reproduce

I have some original HTML (in a file processed by kramdown, if that matters) that looks like this:

```
<p>...<a href='ma&#105;&#108;to&#58;%&#54;&#57;ayo&#37;&#55;5&#110;g%&#52;&#48;%6&#55;mail%2Ec%6Fm'><code>&#105;ayoun&#103;&#64;gmail&#46;co&#109;</code></a> instead.</p>
```

Obviously that's an attempt to obfuscate the address against spam. This was 2005, so sue me.

The output generated looks like this:

```
<p>...<a href="mailto:%69ayo%75ng%40%67mail%2Ec%6Fm"><code>iayoung@gmail.com</code></a> instead.</p>
```

### Expected behavior

I wouldn't mind if something complained.

### Actual behavior

Crashes because of an uncaught exception.

### Details

It turns out that `URI::InvalidComponentError` isn't a subclass of `URI::InvalidURIError`, so it isn't caught by the existing `rescue` clause in `external_links.rb`.

Something like the following does catch this case:

```ruby
      begin
        url = URI.parse(href)
      rescue URI::InvalidURIError
        return Result.new(href, 'invalid URI')
      rescue URI::InvalidComponentError
        return Result.new(href, 'invalid URI component')
      end
```

I don't know whether catching `URI::Error` (which is the parent class of both of these) might be better instead.

**Comment by ddfreyne** [comment]
Fix in #1303. I opted for catching `URI::Error`.
