### ISSUE TITLE
Execution expired in external links validator

### ISSUE THREAD

**Issue by iay** [nanoc/nanoc#1307]
Bizarrely, it seems that there are circumstances under which a `UR.parse` call such as the one in the external link validator can cause a `Timeout::Error` to be raised. The trace looks like this:

```
Timeout::Error: execution expired

  0. /opt/local/lib/ruby2.4/2.4.0/uri/rfc3986_parser.rb:22:in `match'
  1. /opt/local/lib/ruby2.4/2.4.0/uri/rfc3986_parser.rb:22:in `split'
  2. /opt/local/lib/ruby2.4/2.4.0/uri/rfc3986_parser.rb:73:in `parse'
  3. /opt/local/lib/ruby2.4/2.4.0/uri/common.rb:231:in `parse'
  4. /Volumes/Cased/git/iay/iay/site/vendor/ruby/2.4.0/bundler/gems/nanoc-9d358854ba75/nanoc/lib/nanoc/checking/checks/external_links.rb:47:in `validate'
  5. /Volumes/Cased/git/iay/iay/site/vendor/ruby/2.4.0/bundler/gems/nanoc-9d358854ba75/nanoc/lib/nanoc/checking/checks/external_links.rb:40:in `block in select_invalid'
```

This is the site in `external_links.rb`:

```ruby
      begin
        url = URI.parse(href)
      rescue URI::Error
        return Result.new(href, 'invalid URI')
      end
```

The innermost call site, within `rfc3986_parser.rb` is this regular expression match:

```ruby
      if m = RFC3986_URI.match(uri)
```

The regular expression is this monster (I added line breaks):

```ruby
RFC3986_URI = /\A(?<URI>(?<scheme>[A-Za-z][+\-.0-9A-Za-z]*):(?<hier-part>\/\/(?<authority>
(?:(?<userinfo>(?:%\h\h|[!$&-.0-;=A-Z_a-z~])*)@)?(?<host>(?<IP-literal>\[(?:(?<IPv6address>
(?:\h{1,4}:){6}(?<ls32>\h{1,4}:\h{1,4}|(?<IPv4address>(?<dec-octet>[1-9]\d|1\d{2}|2[0-4]\d|25[0-
5]|\d)\.\g<dec-octet>\.\g<dec-octet>\.\g<dec-octet>))|::(?:\h{1,4}:){5}\g<ls32>|\h{1,4}?::(?:\h{1,4}:)
{4}\g<ls32>|(?:(?:\h{1,4}:)?\h{1,4})?::(?:\h{1,4}:){3}\g<ls32>|(?:(?:\h{1,4}:){,2}\h{1,4})?::(?:\h{1,4}:)
{2}\g<ls32>|(?:(?:\h{1,4}:){,3}\h{1,4})?::\h{1,4}:\g<ls32>|(?:(?:\h{1,4}:){,4}\h{1,4})?::\g<ls32>|(?
(?:\h{1,4}:){,5}\h{1,4})?::\h{1,4}|(?:(?:\h{1,4}:){,6}\h{1,4})?::)|(?<IPvFuture>v\h+\.[!$&-.0-;=A-Z_a-
z~]+))\])|\g<IPv4address>|(?<reg-name>(?:%\h\h|[!$&-.0-9;=A-Z_a-z~])+))?(?::(?<port>\d*))?)(?
<path-abempty>(?:\/(?<segment>(?:%\h\h|[!$&-.0-;=@-Z_a-z~])*))*)|(?<path-absolute>\/(?:(?
<segment-nz>(?:%\h\h|[!$&-.0-;=@-Z_a-z~])+)(?:\/\g<segment>)*)?)|(?<path-rootless>\g<segment-
nz>(?:\/\g<segment>)*)|(?<path-empty>))(?:\?(?<query>[^#]*))?(?:\#(?<fragment>(?:%\h\h|[!$&-.0-
;=@-Z_a-z~\/?])*))?)\z/
```

Catching the exception seems to work:

```ruby
      begin
        url = URI.parse(href)
      rescue URI::Error
        return Result.new(href, 'invalid URI')
      rescue Timeout::Error
        return Result.new(href, 'execution expired in parse')
      end
```

This allows me to find the file and then URI causing problems:

```
<a href="http://events.internet2.edu/2009/spring-mm/agenda.cfm?go=session&amp;id=10000483&amp;event=909"
```

Obviously the `&amp;` entities get turned into `&` before the external link validator sees them.

Manually performing `URI.parse` on this value works just fine.

**Comment by iay** [comment]
I uploaded the file to this location, as GitHub doesn't allow HTML attachments:

<https://iay.org.uk/downloads/1307/index.html>

**Comment by ddfreyne** [comment]
The timeout might be occurring in `URI.parse` by accident; it might be triggered somewhere else. Though I’m unclear where that could be…

**Comment by ddfreyne** [comment]
@iay How reproducible is this? Do you always get the timeout error in `URI.parse`?

**Comment by iay** [comment]
I still see them from time to time (I'm running a variant with my patch, so they get processed as errors for me). It's not reliable.

I haven't intentionally removed any links that triggered the issue, but the rate of occurrence has definitely gone down as I have cleaned up _other_ external link issues (I have a _lot_ of external link issues to clean up). That makes me wonder whether there's some leakage from one worker to another, or whether an exception in one thread can also result in an exception in another. I don't know whether those are things that can happen under Ruby's threading model.

**Comment by iay** [comment]
My recollection is that the traceback always went through the URI.parse that I guarded above, yes.

At the moment, I'm running it with the guard so when I do see exceptions I don't get the traceback. I also don't seem to be seeing (these) errors any more at all, which strengthens my feeling that they were appearing as a consequence of bleed-through from some other issue. I will try reverting some of my more recent content corrections (most of which have been fixing other external link problems) and see if I can get them to come back again.

**Comment by iay** [comment]
Confirming that checking out a version of my site project from about a week ago brings back this error, and that it is still originating from the same place.

If it's looking hard to reproduce this in isolation, would it be worth giving you access to the whole repo? It's in a private GitLab instance just now, but I could give you credentials there or mirror it across to a private repo on gitlab.com if you have an account there already.

**Comment by ddfreyne** [comment]
Hey @iay, I’m not been able to reproduce this issue. I’ve tried running the external_links check on the entire site and on subsets with it (including the URL that you mentioned), but it works as expected.

Do you have the issue still?

**Comment by iay** [comment]
I haven't seen that one for a few months now, but as mentioned in one of the earlier comments the rate seemed to go down anyway as I corrected other problems. At the moment I don't have a way to reproduce this, so it's fine if you want to close it. I can always open a new issue if it comes back.

**Comment by ddfreyne** [comment]
Makes sense!

Keep reporting issues :)
