### ISSUE TITLE
Hitting CTRL+C while inside nanoc shell always exits abruptly

### ISSUE THREAD

**Issue by gpakosz** [nanoc/nanoc#1309]
Within `nanoc shell`, hitting <kbd>CTRL</kbd>+<kbd>C</kbd> quits abruptly with "stdout closed".

You need to `$ reset` your terminal emulator to move on.

### Steps to reproduce

1. `bundle exec nanoc shell`
2. hit <kbd>CTRL</kbd>+<kbd>C</kbd>
3. Nanoc shell exists leaving terminal seemingly unresponsive: you have to `$ reset` before being able to see what you're typing again

### Another manifestation of the bug

1. `bundle exec nanoc shell`
2. start typing some Ruby
3. realize you messed up and try to hit <kbd>CTRL</kbd>+<kbd>C</kbd> to cancel your typing
3. Nanoc shell exits leaving terminal seemingly unresponsive, instead of cancelling the typing

### Expected behavior

Nanoc shell cancels current typing instead of always exiting. Nanoc shell only exits when the REPL input is empty, just like `irb`.

In any case when Nanoc shell exits, one shouldn't have to `$ reset` the terminal emulator.

**Comment by ddfreyne** [comment]
Can you show me the output of `bundle exec nanoc --version`?

**Comment by gpakosz** [comment]
Oops sorry, it's nanoc 4.8.16
```
$ bundle exec nanoc --version
Nanoc 4.8.16 © 2007-2017 Denis Defreyne.
Running ruby 2.4.3 (2017-12-14) on x86_64-darwin16 with RubyGems 2.6.14.
```

**Comment by ddfreyne** [comment]
@gpakosz Is this a problem for you with pure `pry` as well, or just `nanoc shell`?

**Comment by gpakosz** [comment]
When I launch `pry`, hitting <kbd>CTRL</kbd>+<kbd>C</kbd> doesn't exit `pry`:

![image](https://user-images.githubusercontent.com/553208/35908278-777e6d84-0bf0-11e8-953d-b77d606b03c5.png)

**Comment by ddfreyne** [comment]
@gpakosz Does the problem persist when you do the following?

1. `bundle exec nanoc shell`
2. `Signal.trap('SIGINT') { raise Interrupt }`
3. Press ^C

**Comment by gpakosz** [comment]
```
Loading site… done
[1] pry(#<Nanoc::Int::Context>)> Signal.trap('SIGINT') { raise Interrupt }
=> #<Proc:0x00007f9d6815c950@/usr/local/lib/ruby/gems/2.5.0/gems/nanoc-4.8.16/lib/nanoc/cli/error_handler.rb:39>
[2] pry(#<Nanoc::Int::Context>)>
[2] pry(#<Nanoc::Int::Context>)>
```

Better!
