### ISSUE TITLE
Pruner should check for excluded files without considering to output_dir

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1313]
When a pattern excluded from pruning is contained in the `output_dir` config variable all files below `output_dir` get excluded.

### Steps to reproduce

1. Set `output_dir: output` in `nanoc.yaml` (the default)
1. Set `prune.exclude: ['output']` in `nanoc yaml`
1. Compile site
1. `touch output/something`
1. Run `nanoc prune --yes`

### Expected behavior

`output/something` should be pruned.

### Actual behavior

`output/something` remains.

### Details

When checking whether a file is excluded from pruning, the `output_dir` path component(s) should not be considered.

**Comment by gpakosz** [comment]
I believe the behavior you're witnessing is normal. As per [Nanoc manual](https://nanoc.ws/doc/reference/config/#prune):
> The exclude option determines which files and directories you want to exclude from pruning. If you version your output directory, you should probably exclude VCS directories such as `.git` or `.hg`.

Now I would acknowledge there's an ambiguity in the Nanoc's wording.
Should `prune.exclude: ['output']` exclude `output` or `output/output`?

The current behavior makes it `output/` is excluded from pruning. And by definition, `output/something` being inside `output/` (which is excluded from pruning) doesn't get deleted.

In any case, the exclusion logic is implemented in terms of [`String#include?](https://ruby-doc.org/core-2.2.0/String.html#method-i-include-3F) so it's definitely loose and can't achieve what you're asking.

Finally, given your additional example of having `output_dir: build/bin` and a tool creating files in `build/bin/bin` it seems to me you want to exclude `build/bin/bin` and not `build/bin` right?

**Comment by agross** [comment]
> Finally, given your additional example of having `output_dir: build/bin` and a tool creating files in `build/bin/bin` it seems to me you want to exclude `build/bin/bin` and not `build/bin` right?

Right, but given that the exclude patterns are checked against each path component I cannot achieve that either.

**Comment by gpakosz** [comment]
I mean `prune.exclude: ['build/bin/bin']`

**Comment by agross** [comment]
> Now I would acknowledge there's an ambiguity in the Nanoc's wording. Should `prune.exclude: ['output']` exclude output or `output/output`?

From my point of view it should only exclude `output/output`.

Consider this:
1. `output_directory: foo` and `prune.exclude: ['bar']`
1. You use pruning and like it
1. Later, you decide you want your output in `bar`, hence you set `output_directory: bar`
1. Pruning gets disabled without anybody telling you

**Comment by agross** [comment]
> I mean `prune.exclude: ['build/bin/bin']`

Not possible, as each path *component* is checked against a pattern. What you suggested never is a component. For `build/bin/bin/foo.dll` these components will be checked against exclude patterns: `build`, `bin`, `bin`, `foo.dll`.

I remember a discussion we had earlier that I would prefer pruning to use globs. It allows for fine-grained control, is rather standard, but doesn't still believe these globs should be checked against paths below `output_dir`, whatever that value is at the moment.

**Comment by agross** [comment]
https://github.com/nanoc/nanoc/issues/883

**Comment by ddfreyne** [comment]
Having globs would certainly still be useful, though it wouldn’t fix this particular bug.

Fix is coming up.

**Comment by agross** [comment]
Thank you!

**Comment by agross** [comment]
I'm sorry but it still doesn't work. I made a little repro: https://github.com/agross/nanoc-pruning

**Comment by ddfreyne** [comment]
Reopening!

**Comment by ddfreyne** [comment]
@agross Can you verify that #1324 works for you?

**Comment by agross** [comment]
Looking good!

**Comment by ddfreyne** [comment]
Nice! That PR needs better test coverage, so I’ll spend a bit more time to finish it up and then release 4.9.2, hopefully this weekend.
