### ISSUE TITLE
Unhelpful error message when text filter returns nil

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1323]
When a textual filter returns `nil` (as I did when I forgot to `return content`), you get this error message:

```
Loading site... done
Compiling site...

Captain! We've been hit!

  ... 8 lines omitted (see crash.log for details)
  9. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  8. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  7. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `block in each'
  6. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/recalculate.rb:32:in `block in run'
  5. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/executor.rb:65:in `layout'
  4. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/executor.rb:92:in `assigns_for'
  3. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compilation_context.rb:41:in `assigns_for'
  2. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/content.rb:71:in `string'
  1. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/lazy_value.rb:18:in `value'
  D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/lazy_value.rb:18:in `delete'

FrozenError: can't modify frozen Hash
You attempted to modify immutable data. Some data cannot be modified once compilation has started. Such data includes content and attributes of items and layouts, and filter arguments.

Current item: /index.html (:default representation)

A detailed crash log has been written to ./crash.log.
```

### Steps to reproduce

```rb
class Foo < Nanoc::Filter
  identifier :foo
  type :text

  def run(content, params = {})
  end
end
```

1. Add the filter above and add a compilation rule
2. `bundle exec nanoc compile`

### Expected behavior

Some error that I might have forgotten to return something or nanoc using `nil` or nanoc translating `nil` to `''`.

### Actual behavior

Error message above.

### Crash log

<details>
<pre><code>
Crashlog created at 2018-02-27 01:33:00 +0100

===== MESSAGE:

FrozenError: can't modify frozen Hash
You attempted to modify immutable data. Some data cannot be modified once compilation has started. Such data includes content and attributes of items and layouts, and filter arguments.

===== ITEM BEING COMPILED:

Current item: /index.html (:default representation)

===== STACK TRACE:

  17. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/resume.rb:41:in `block in fiber_for'
  16. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/resume.rb:14:in `block in run'
  15. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/abstract.rb:23:in `block in call'
  14. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/abstract.rb:21:in `call'
  13. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/cache.rb:23:in `run'
  12. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/abstract.rb:23:in `block in call'
  11. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/abstract.rb:21:in `call'
  10. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/recalculate.rb:27:in `run'
  9. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  8. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  7. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `block in each'
  6. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/recalculate.rb:32:in `block in run'
  5. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/executor.rb:65:in `layout'
  4. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/executor.rb:92:in `assigns_for'
  3. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compilation_context.rb:41:in `assigns_for'
  2. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/content.rb:71:in `string'
  1. from D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/lazy_value.rb:18:in `value'
  D:/Dropbox/Apps/Ruby/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/lazy_value.rb:18:in `delete'

===== VERSION INFORMATION:

Nanoc 4.9.1 © 2007-2018 Denis Defreyne.
Running ruby 2.5.0 (2017-12-25) on x64-mingw32 with RubyGems 2.7.3.
</code></pre>
</details>

**Comment by ddfreyne** [comment]
@agross Is that the full crash log? The stack trace is missing parts!

**Comment by agross** [comment]
@ddfreyne Yes, it was copied from crash log (the extra empty lines were added by GitHub, though).

**Comment by agross** [comment]
On macOS:

```
Loading site… done
Compiling site…

Captain! We’ve been hit!

  ... 8 lines omitted (see crash.log for details)
  9. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  8. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `each'
  7. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/action_sequence.rb:50:in `block in each'
  6. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compiler/phases/recalculate.rb:32:in `block in run'
  5. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/executor.rb:65:in `layout'
  4. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/executor.rb:92:in `assigns_for'
  3. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/services/compilation_context.rb:41:in `assigns_for'
  2. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/content.rb:71:in `string'
  1. from /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/lazy_value.rb:18:in `value'
  /Users/agross/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/nanoc-4.9.1/lib/nanoc/base/entities/lazy_value.rb:18:in `delete'

FrozenError: can't modify frozen Hash
You attempted to modify immutable data. Some data cannot be modified once compilation has started. Such data includes content and attributes of items and layouts, and filter arguments.

Current item: /index.html (:default representation)

A detailed crash log has been written to ./crash.log.
```

[crash.log](https://github.com/nanoc/nanoc/files/1762107/crash.log)
