### ISSUE TITLE
internal_links check for xhtml files

### ISSUE THREAD

**Issue by lo48576** [nanoc/nanoc#1328]
`internal_links` checker checks `*.html` files, but not `*.xhtml` files.

### Steps to reproduce

1. Prepare (generate) `*.xhtml` files with wrong site-local links.
2. Run `nanoc check ilinks`

### Expected behavior

`nanoc check ilinks` detects broken links in `*.xhtml` files.

### Actual behavior

`nanoc check ilinks` doesn't detect broken links in `*.xhtml` files.

### Details

Maybe this line should be changed:
https://github.com/nanoc/nanoc/blob/9050195b2839efa331eadfe2154622b0313b54d4/nanoc/lib/nanoc/checking/checks/internal_links.rb#L18

I'm not sure this should be configurable or can be hard-coded, but I think not only `*.html` but also `*.xhtml` and `*.htm` should be (can be) checked as HTML file.

**Comment by ddfreyne** [comment]
Good catch! Here’s a fix: #1329
