### ISSUE TITLE
Please sign the releases

### ISSUE THREAD

**Issue by ge-fa** [nanoc/nanoc#1333]
Hi,

nanoc is packaged in Debian. I would like to ensure, that the code, which is imported into Debian, wasn't tampered with along the way.

Therefore: Could you please sign the releases? See [this link](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) for some details how to do so.

In case you implement this: Could you provide a signature for the current release?

Thanks for your work,
cheers,
Georg

**Comment by gpakosz** [comment]
@ge-fa Hello, out of curiosity what's the point of Debian packaging Ruby gems to begin with?

Debian Stretch is packaging Nanoc 4.4.7 while we're at 4.9.1. Soon enough Ruby 2.3 EOL is going to be announced and all the Ruby ecosystem packaged by Debian will be too ancient anyways ¯\_(ツ)_/¯

**Comment by ddfreyne** [comment]
Hi,

Nanoc’s releases already are GPG-signed (since early 2014). You can use
`git verify-tag` to verify them.

Denis

**Comment by ddfreyne** [comment]
… or rely on GitHub to tell you that it’s valid:

![screen shot 2018-03-19 at 08 06 52](https://user-images.githubusercontent.com/6269/37582284-8a6b8a96-2b4c-11e8-9379-cc567a58fcde.png)

**Comment by ge-fa** [comment]
> Debian Stretch is packaging Nanoc 4.4.7 while we're at 4.9.1. Soon enough Ruby 2.3 EOL is going to be announced and all the Ruby ecosystem packaged by Debian will be too ancient anyways. That's what happened with Jessie ¯\(ツ)/¯

It'll be updated today.

> @ddfreyne 

Thanks, and sorry for not being clear right from the start: Would it be possible to upload a detached signature?

**Comment by ddfreyne** [comment]
> Thanks, and sorry for not being clear right from the start: Would it be possible to upload a detached signature?

Preferably not. Can you explain why the `git verify-tag` approach would not work for you?

**Comment by ge-fa** [comment]
Limited tooling support, currently. But that's not your department, obviously. Thanks for your reply and your work on nanoc!
