### ISSUE TITLE
Feature Suggestion: Multiple Lib Folders

### ISSUE THREAD

**Issue by zor-el** [nanoc/nanoc#1337]
Hi there,

I was wondering if it'd be not too much of a stretch to implement this, perhaps in the context of a filesystem datasource. Currently nanoc supports a layouts_dir and content_dir per filesystem datasource. Perhaps it can also support a lib_dir in the same way, so that lib files would be searched in every lib_dir specified?

If someone can point me into the right direction in the code, I could try to implement this myself and issue a PR.

Thoughts, anyone?

Thank you.

**Comment by gpakosz** [comment]
Nanoc has a `lib_dirs` setting already.

```
lib_dirs:
  - foo/lib
  - lib
```

Helpers in `foo/lib?` will be overridden by helpers in `lib?`

**Comment by zor-el** [comment]
Thanks! Good to know. I actually almost expected it, but since there was no mention of it in the documentation...

I was looking for a way to allow a "filesystem" to no only provide layouts and items, but also bring along any helpers that may be used in them.

How does the overriding take place? Is that on a file name basis, or method basis? I'm guessing it's the latter, and if there is a file named `default.rb` in both `lib/` and `foo/lib/`, they will both be loaded and methods will be monkey-patched, right?

**Comment by zor-el** [comment]
I just answered my own question:

- Code is loaded from each folder in lib_dirs in sequence
- Monkey-patching rules apply

Wonderful!  👍

**Comment by ddfreyne** [comment]
Whoops, `lib_dirs` being undocumented is not intentional. I’ve opened a ticket on nanoc.ws: https://github.com/nanoc/nanoc.ws/issues/221
