### ISSUE TITLE
Rules colorize-syntax acts quite strangely

### ISSUE THREAD

**Issue by Doshirae** [nanoc/nanoc#1339]
Okay so this bug is really weird, so I may not really be able to describe it well, and I apologize in advance

So in my `Rules` file, I got that 

```ruby
compile '/posts/*' do
	filter :kramdown, auto_ids: false
	filter :links
	filter :colorize_syntax, default_colorizer: :pygmentsrb
	layout '/post.erb'
end
```

The line I am interested in is the colorize_syntax rule.
The default_colorizer doesn't work
If I have the coderay gem installed, It will be coderay that will be used no matter what
Plus, every option used with coderay (like `filter :colorize_syntax, coderay: { :line_number_start => 3`) is completely ignored

The only way that works to use another colorizer is to have only one installed…
But uninstalling coderay breaks pry :/

I really don't know what could be going on…

**Comment by ddfreyne** [comment]
This might be Kramdown’s built-in colorizer. Can you try with

```
  filter :kramdown, auto_ids: false, syntax_highlighter: nil
```

… and see whether that works?

(Or alternatively, keep using Kramdown’s highlighter and don’t use Nanoc’s.)

**Comment by iay** [comment]
In my `Rules` file, I have this:

```ruby
  filter :kramdown, input: 'GFM', enable_coderay: false,
                    hard_wrap: false
  filter :colorize_syntax, default_colorizer: :rouge
```

So, `enable_coderay: false` might be another alternative.
