### ISSUE TITLE
Breadcrumb trail does not end in item itself

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#1366]
### Steps to reproduce

1. Create a site with the items listed below
2. Create a breadcrumb trail for `/there/software/ahab.md`

* `/index.md`
* `/there.md`
* `/there/software.md`
* `/there/software/ahab.zip`
* `/there/software/ahab.md`

### Expected behavior

Breadcrumb trail:

* `/index.md`
* `/there.md`
* `/there/software.md`
* `/there/software/ahab.md`

### Actual behavior

Breadcrumb trail:

* `/index.md`
* `/there.md`
* `/there/software.md`
* `/there/software/ahab.zip` ← not `ahab.md` as expected!

**Comment by iay** [comment]
I confirm that this change fixes the specific cases I had.
