### ISSUE TITLE
Ambiguity in application of .yaml files to items

### ISSUE THREAD

**Issue by iay** [nanoc/nanoc#1369]
If you have multiple files to which a `.yaml` file might apply, this can cause problems.

### Steps to reproduce

Create three files:

* `foo.png`, an image
* `foo.yaml`, containing item attributes for that image
* `foo.md`, containing its own attributes in a `---`-delimited header

### Expected behavior

I would have expected the `foo.md` item to contain the attributes from its own header, and the `foo.png` item to contain the attributes from `foo.yaml`.

### Actual behavior

1. The `foo.png` does contain the attributes from `foo.yaml`.
2. The `foo.md` item _also_ contains the attributes from `foo.yaml`.
3. The `foo.md` item _does not_ contain the attributes from its own header.
4. The `foo.md` item's content includes the header as text.

**Comment by ddfreyne** [comment]
Work-in-progress fix: #1370
