### ISSUE TITLE
Nanoc v4.10.1 doesn't seem to recompile when layout Haml options changed

### ISSUE THREAD

**Issue by moll** [nanoc/nanoc#1372]
Hey,

I'm not sure if it's by design or not, but I was playing around with Haml's `remove_whitespace` option and changing it (adding/removing, for example) in the `layout` rule doesn't seem to trigger any recompilations. Nuking the output directory does show changes however.

```
layout "/**/*", :haml, remove_whitespace: true
```

**Comment by ddfreyne** [comment]
I can confirm that this happens — and it’s not expected. Will work on a fix.

**Comment by ddfreyne** [comment]
This is now released in Nanoc 4.10.2.

**Comment by moll** [comment]
A belated thanks! :)
