### ISSUE TITLE
Cannot import Sass files by identifier

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1397]
I use Sass syntax (not Scss). Since the new sourcemap-enabled [importer hard-codes `:scss` syntax](https://github.com/nanoc/nanoc/blob/master/nanoc/lib/nanoc/filters/sass/importer.rb#L45), I cannot use `@import` with item identifiers if the item's content syntax is Sass.

### Steps to reproduce

1. Set up [documented example](https://nanoc.ws/doc/guides/using-common-filters/#using-partials)
1. Make sure the partial contains Sass syntax-specific code
1. Compile

Example repo here: https://github.com/agross/nanoc-sass-partials-by-id

### Expected behavior

Compilation succeeds

### Actual behavior

Compilation fails

```sh
$ nanoc
Loading site… done
Compiling site…
/app.sass:4 DEBUG: Could import by relative path

Captain! We’ve been hit!

Sass::SyntaxError: Invalid CSS after "..."$this-is-sass"": expected "{", was ""

Current item: /app.sass (:default representation)

  0. /_partial.sass:3
  1. /app.sass:6
```

### Details

The build output should contain both `/app.sass:4 DEBUG: Could import by relative path` and `'Could import by item identifier'`.

I need to use `@import "/item/identifier.sass"` instead of plain files because plain files cause a dependency on all items' raw content. This essentially disables Nanoc's caching for the Sass filter output.

### Crash log

https://gist.github.com/agross/ada776af1111de4d54f5f84c81200142

**Comment by agross** [comment]
FWIW, before the importer sets the syntax to `:scss`, `options[:syntax]` already equals `:sass`. I guess removing that assignment will then break Sass importing Scss . I think Nanoc needs to somehow guess the syntax.

**Comment by agross** [comment]
@gpakosz FYI

**Comment by gpakosz** [comment]
Hi @agross, I'm currently in holidays. I'll have a look next week.

**Comment by agross** [comment]
👍 Enjoy!
