### ISSUE TITLE
nanoc 4.11.1 introduces breaking change by making compiled_content include the layout

### ISSUE THREAD

**Issue by DivineDominion** [nanoc/nanoc#1412]
I upgraded my project from 4.11.0 to 4.11.2 and noticed a weird glitch: the full-text post previews included the layout again.

![screenshot 2019-02-20 at 11 33 42](https://user-images.githubusercontent.com/59080/53085607-8be93000-3503-11e9-8197-812167a86f7d.png)

Turns out that between 4.11.0 and 4.11.1, `#compiled_content` changed and now returns a cached representation with the layout already added. I found that a call to `compiled_content(snapshot: :pre)` makes it look as expected.

So fixing this was pretty easy, I just wanted to let you know that this is a change at all so you might add it to the release notes.

I couldn't reproduce this in a vanilla project with v4.11.1, though. Maybe it's because the affected items are references in `preprocess`? If you aren't aware of this change and don't have a hunch what's going on and want me to investigate, I can try different configurations @ddfreyne

**Comment by ddfreyne** [comment]
Yikes — that is definitely a bug. Will investigate.

**Comment by ddfreyne** [comment]
This is almost certainly caused by 5cbad99abfed9e3cb02bc271f2be1ad7f12b1641 (part of #1394). It’s a refactoring that I’ve been wanting to make for a long time.

I’m still investigatating why it fails for you, though.

**Comment by ddfreyne** [comment]
@DivineDominion I’m not able to reproduce the problem you described. Could you create a zip of `tmp/nanoc` and send it to me (denis+github@denis.ws)? After you’ve done that, can you try removing tmp/nanoc and re-running Nanoc?

**Comment by ddfreyne** [comment]
@DivineDominion Are you still experiencing this issue?

**Comment by ddfreyne** [comment]
This is not an isolated issue, as I just saw the same issue come in: https://groups.google.com/forum/#!topic/nanoc/pbHOJ3T6wiY

**Comment by DivineDominion** [comment]
While finding the fix wasn't that bad, I find it pretty hard to create a test project that crashes. I stopped a while ago but will try to squeeze in time this week to figure this out.

**Comment by ddfreyne** [comment]
I am now able to reproduce the problem, and am working on a fix.

**Comment by ddfreyne** [comment]
Here is a fix: #1421

I am struggling to write a regression test for it, though.

**Comment by DivineDominion** [comment]
Good you found the culprit! I ran into it in another project just last week but couldn't trim it down to a simple example :/
