### ISSUE TITLE
Internal links checker throwing exception

### ISSUE THREAD

**Issue by iay** [nanoc/nanoc#1423]
### Steps to reproduce

1. start with my working site
2. `bundle update nanoc` (to get 11.4.4)
3. `bundle exec nanoc check internal_links`

### Expected behavior

All is well.

### Actual behavior

```
Loading site… done
  Running check internal_links…   
Captain! We’ve been hit!

NoMethodError: undefined method `green' for "ok":String

  0. /Volumes/Cased/git/iay/iay/site/vendor/ruby/2.4.0/gems/nanoc-4.11.4/lib/nanoc/checking/runner.rb:109:in `block in run_checks'
```

### Details

The line in question is:

```
        puts check.issues.empty? ? 'ok'.green : 'error'.red
```

I note that elsewhere in `runner.rb` there's a `require 'colored'` but I don't seem to have that available. Missing dependency perhaps?

**Comment by ddfreyne** [comment]
`colored` was a dependency of `cri`, which is a dependency of `nanoc`. I removed `colored` as a dependency from `cri`, but did not realise that Nanoc uses `colored` indirectly.

I will add `colored` as an explicit dependency to `nanoc`.

**Comment by ddfreyne** [comment]
(Unfortunately, these kinds of problems are bound to happen because that is the way Ruby works.)

**Comment by ddfreyne** [comment]
Fixed by 3008036bd834219c532e4c357e767dac47f758ad.

**Comment by ddfreyne** [comment]
(You could also downgrade `cri` as a workaround.)

**Comment by iay** [comment]
Confirming that the change you pushed works for me.

**Comment by ddfreyne** [comment]
This is now in the Nanoc 4.11.5 release.
