### ISSUE TITLE
not outdated binary cached compiled content available does not change compiled content cache

### ISSUE THREAD

**Issue by da2x** [nanoc/nanoc#1427]
### Steps to reproduce

1. Run tests.
2. Run them again and again.

### Actual behavior

    1) Nanoc::Int::Compiler::Phases::Cache#run not outdated binary cached compiled content available does not change compiled content cache
     Failure/Error: FileUtils.cp(binary_content.filename, filename)
     
     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /var/folders/rl/pb4vl0zd2p1992h4kp1pf9sr0000gn/T/test20190501-86152-18oktmk
     # ./lib/nanoc/base/repos/binary_compiled_content_cache.rb:65:in `block in []='
     # ./lib/nanoc/base/repos/binary_compiled_content_cache.rb:51:in `each'
     # ./lib/nanoc/base/repos/binary_compiled_content_cache.rb:51:in `[]='
     # ./lib/nanoc/base/repos/compiled_content_cache.rb:46:in `[]='
     # ./spec/nanoc/base/services/compiler/phases/cache_spec.rb:122:in `block (5 levels) in <top (required)>'
     # /Users/tmp/nanoc/common/spec/spec_helper_foot.rb:40:in `block (2 levels) in <top (required)>'
     # /Users/tmp/nanoc/common/spec/spec_helper_foot_core.rb:31:in `block (4 levels) in <top (required)>'
     # /Users/tmp/nanoc/common/spec/spec_helper_foot_core.rb:6:in `__nanoc_core_chdir'
     # /Users/tmp/nanoc/common/spec/spec_helper_foot_core.rb:31:in `block (3 levels) in <top (required)>'
     # /Users/tmp/nanoc/common/spec/spec_helper_foot_core.rb:30:in `block (2 levels) in <top (required)>'

### Details

This one test keeps failing randomly maybe 30% of the time when running on macOS 10.14.4. Never seen it fail on Ubuntu 19.04.

**Comment by ddfreyne** [comment]
I’ve been trying to make this test fail, with no luck. I’m using the following:

* macOS 10.14.4 (18E226)
* Ruby 2.6.3 (2019-04-16)
* RubyGems 3.0.3

What does `nanoc --version` show for you?

**Comment by ddfreyne** [comment]
Oh, I did manage to make it fail, though for me only after ~100 tries.

It turns out that I’m mis-using `Tempfile`, and a GC run can break the test. Will fix.

**Comment by ddfreyne** [comment]
Fixed on master — can you verify that this works for you now, too?

**Comment by da2x** [comment]
I ran the tests 24 times without hitting this. It seems to be fixed.
