### ISSUE TITLE
nanoc show-data crashes with contract violation

### ISSUE THREAD

**Issue by da2x** [nanoc/nanoc#1428]
### Steps to reproduce

1. Run `nanoc show-data` (confirmed to crash on nanoc.ws’ sources.)

### Crash log

    ParamContractError: Contract violation for argument 1 of 1:
        Expected: (Nanoc::Core::Item or Nanoc::Core::ItemRep),
        Actual: <Nanoc::Core::Layout identifier="/entry.erb">
        Value guarded in: Nanoc::Int::OutdatednessChecker::outdated_due_to_dependencies?
        With Contract: Or, Hamster::Set => Bool
        At: /home/da/.local/share/rubygems/gems/nanoc-4.11.5/lib/nanoc/base/services/outdatedness_checker.rb:160 

https://gist.github.com/da2x/29a1c61023ba9372b66ee02eb204c8ab

**Comment by ddfreyne** [comment]
I can reproduce this one!
