### ISSUE TITLE
The --diff option fails when there are many changes

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1440]
When compiling a large number of files the `--diff` option consistently fails. It works fine when compiling only a small number of files, or when not using the --diff option. It looks like the --diff option may be doing something that's not thread safe.

### Steps to reproduce

1. Make a change that causes many files to change at once, e.g. change a layout file
2. Compile with diff option `nanoc compile --diff`

### Expected behavior

An output.diff file should be generated

### Actual behavior

The compile itself works, but not the diff and there are several errors in the terminal, similar to this one:

```
#<Thread:0x00007fab10f83ed8@/Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/nanoc-4.11.5/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb:50 run> terminated with exception (report_on_exception is true):
/Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/tty-file-0.7.1/lib/tty/file.rb:363:in `block in diff': (/var/folders/80/t3vssmwj0_73q_lmhfk382xw0000gn/T/old20190614-38241-1j08432 is binary, diff output suppressed) (ArgumentError)
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/tty-file-0.7.1/lib/tty/file.rb:751:in `open'
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/tty-file-0.7.1/lib/tty/file.rb:751:in `open_tempfile_if_missing'
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/tty-file-0.7.1/lib/tty/file.rb:358:in `diff'
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/nanoc-4.11.5/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb:78:in `block (2 levels) in diff_strings'
	from /Users/jmfaber/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tempfile.rb:295:in `open'
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/nanoc-4.11.5/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb:70:in `block in diff_strings'
	from /Users/jmfaber/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tempfile.rb:295:in `open'
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/nanoc-4.11.5/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb:69:in `diff_strings'
	from /Users/jmfaber/.rvm/gems/ruby-2.5.3/gems/nanoc-4.11.5/lib/nanoc/cli/commands/compile_listeners/diff_generator.rb:58:in `block in generate_diff_for'
```

**Comment by ddfreyne** [comment]
Do you have a sample site that I can test this with?

The `ArgumentError` troubles me — it might indicate a different source of the problem.

**Comment by Fjan** [comment]
You are right, I noticed it only happens only in nanoc files with non-latin text and after some more debugging found that this bug was really a side effect of a bug in the underlying gem tty-file. I filed the bug there: 
https://github.com/piotrmurach/tty-file/issues/11

**Comment by ddfreyne** [comment]
I’m modifying the diff implementation in #1455, which should make the diffing more reliable.

**Comment by ddfreyne** [comment]
(and very slightly faster)
