### ISSUE TITLE
guard-nanoc’s nanoc-live doesn't log what it's doing

### ISSUE THREAD

**Issue by Ecco** [nanoc/nanoc#1449]
### Steps to reproduce

1. Run `bundle exec nanoc live`
2. Modify a file
3. Save it

### Expected behavior

I think previously `nanoc live` used to log what it was doing, exactly like `nanoc compile` does. For example

```
      update  [0.00s]  output/foobar/index.html
```

### Actual behavior

Now I only get a `14:13:41 - INFO - Compilation succeeded.` line.

**Comment by Ecco** [comment]
Was not using the right gem (`guard-nanoc` instead of `nanoc-live`). See #1450

**Comment by Ecco** [comment]
Since apparently `guard-nanoc` is still a thing, I reopened this issue. Note that the problem doesn't happen with `nanoc-live`.

**Comment by ddfreyne** [comment]
I’ve not been working on this issue, because I intend to bring `nanoc-live` to a finished state soon.

Let me know how `nanoc-live` works for you — ideally, flawlessly :)

**Comment by Ecco** [comment]
Well, for me it does work perfectly 😄

**Comment by axilleas** [comment]
:wave: I switched to `nanoc-live`, but it only regenerates the site if `lib/` is changed. Do I need to set up anything in `nanoc.yml` to also pick up `content/`?

**Comment by ddfreyne** [comment]
@axilleas That should work out of the box — is this the GitLab site?

**Comment by axilleas** [comment]
@ddfreyne correct :) You can see the changes here https://gitlab.com/gitlab-org/gitlab-docs/merge_requests/632.

**Comment by axilleas** [comment]
So, I got a chance to test this again, and it seems I no longer have the issue in https://github.com/nanoc/nanoc/issues/1449#issuecomment-558049581. No idea what changed since then :smile:

**Comment by ddfreyne** [comment]
Good to hear!

I’ll close this ticket now, also because the new nanoc-live is now out of beta (and can be used as a guard-nanoc replacement).
