### ISSUE TITLE
nanoc live can be provided by two gems

### ISSUE THREAD

**Issue by Ecco** [nanoc/nanoc#1450]
### Summary of the issue

Currently the `nanoc live` command can be provided by two gems: `guard-nanoc`, and `nanoc-live`.

Nanoc-live seems to be the latest-and-greatest option, but guard-nanoc still works even though it's a bit broken.

### Possible solution

Maybe recent versions of nanoc should warn when `guard-nanoc` is loaded instead of `nanoc-live`?

**Comment by iay** [comment]
The documentation still seems to refer to `guard-nanoc` and I note that `nanoc-live`'s version number still includes a "b4" suffix. So `guard-nanoc` may still be the current solution.

**Comment by Ecco** [comment]
Indeed, except it's buggy: see #1449 which hit me when using guard-nanoc.

**Comment by ddfreyne** [comment]
`nanoc-live` is still in beta and has some breaking issues which prevent it from being the main solution.

**Comment by Ecco** [comment]
Oh, ok. So then I'm reopening #1449 :)

**Comment by ddfreyne** [comment]
guard-nanoc and nanoc-live will soon (#1468) print a message similar to this:

```
----------------------------------------
NOTE:
You are using the `nanoc live` command provided by `nanoc-live`, but the `guard-nanoc` gem is also installed, which also provides a `nanoc live` command.
Recommendation: Remove `guard-nanoc` from your Gemfile.
----------------------------------------
```
