### ISSUE TITLE
Where is nanoc/spec?

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#1465]
### Steps to reproduce

1. Upgrade from 4.11.9 to 4.11.14
2. `require 'nanoc/spec'`

### Expected behavior

I can run specs using the spec helpers with `bundle exec rspec`.

### Actual behavior

```
require 'nanoc/spec'

LoadError:
  cannot load such file -- nanoc/spec
```

**Comment by agross** [comment]
Seems like a1ba3ec0deeb36a738c5c527805a276a5512487c deleted that file.

**Comment by ddfreyne** [comment]
Yes, my bad — nanoc/spec should have stayed there.

**Comment by ddfreyne** [comment]
The `Nanoc::Spec` features now live in a separate `nanoc-spec` gem. To use it:

1. Add `nanoc-spec` to your Gemfile and run `bundle install`.
2. Ensure that a `require 'nanoc-spec'` is present.

**Comment by agross** [comment]
Thank you!
