### ISSUE TITLE
nanoc requires Ruby version ~> 2.4

### ISSUE THREAD

**Issue by vieiro** [nanoc/nanoc#1472]
### Steps to reproduce

1. Read the installation instructions that indicate that nanoc works on Ruby 2.3
2. Try to install nanoc with Ruby 2.3

### Expected behavior

The installation works as indicated in the documentation (i.e., nanoc works on Ruby 2.3).

### Actual behavior

C:\> gem install nanoc --version 4.10
Fetching: parallel-1.19.1.gem (100%)
Successfully installed parallel-1.19.1
Fetching: nanoc-4.10.0.gem (100%)
ERROR:  Error installing nanoc:
        nanoc requires Ruby version ~> 2.4.

### Details

See above

### Crash log

See above.

### Suggested fix

Update the documentation to indicate that nanoc requires Ruby >= 2.4
i.e., change the part that says "Nanoc supports the official Ruby interpreter from version 2.3 up."  at https://nanoc.ws/doc/installation/#compatibility-guarantees

**Comment by ddfreyne** [comment]
Thank you for reporting! This is fixed in nanoc/nanoc.ws@33958cd now.
