### ISSUE TITLE
Live reload does not work for `*.xhtml` files

### ISSUE THREAD

**Issue by lo48576** [nanoc/nanoc#1473]
### Steps to reproduce

Reproducible with nanoc 4.11.14 and Ruby 2.6.5.

1. Set up nanoc to write some `*.html` file and `*.xhtml` output files.
2. Run `nanoc live` or `nanoc view -L`.
3. Update the source files of `*.html` and `*.xhtml` respectively.

### Expected behavior

Live reload automatically make browser to refresh `*.html` and `*.xhtml` pages.

### Actual behavior

Live reload works for `*.html` files, but not for `*.xhtml` files.

### Details

I checked the response from the server.
For `*.html` files, `<script>`s are inserted in `<head>` elements.
However, `*.xhtml` files are not modified and `<script>`s are not inserted.

**Comment by lo48576** [comment]
Checked `rack-livereload` 0.3.17, and noticed the lines below are the cause of this problem:

https://github.com/onesupercoder/rack-livereload/blob/0e7c889dbe54b360ff48760253c905a2f6acb0a0/lib/rack/livereload/processing_skip_analyzer.rb#L39-L41

```ruby
      def html?
        @headers['Content-Type'] =~ %r{text/html}
      end
```

There seems nothing `nanoc` can do for this...?
Using `text/html` instead of `application/xhtml+xml` could solve this, but I don't think it is right thing to do.

Still worse, <https://github.com/onesupercoder/rack-livereload> has issue tracker disabled!

**Comment by ddfreyne** [comment]
Thanks for reporting! I’ve created a PR on `rack-livereload`, so hopefully it gets merged and released soon: https://github.com/onesupercoder/rack-livereload/pull/3/files.

**Comment by ddfreyne** [comment]
I will close this issue now, as there’s nothing that can be done from the Nanoc side of things. Hopefully, the aforementioned PR will be merged soon.
