### ISSUE TITLE
relativize_path should work on img srcset

### ISSUE THREAD

**Issue by bobbens** [nanoc/nanoc#1475]
### Steps to reproduce

1. Add an `<img>` tag using srcset
2. Compile using relativize_paths

### Expected behavior

Expected not only the src attribute but also all the links in the srcset to be relativized.

### Actual behavior

Only the src attribute is relativized.

### Details

I wasn't able to get the selector parameter to work using srcset like I have done in the past for data-src. This is likely due to the fact that srcsets, unlike src, are a list of links and image sizes, and not just a single link.

**Comment by da2x** [comment]
These are the elements affected by this issue: `img[srcset]` and `source[srcset]` (comma-separated list with width descriptor), and `a[ping]` (whitespace separated list).
