### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by ghost** [nanoc/nanoc#1480]
I see that Markdown is supported:

https://nanoc.ws/doc/tutorial#write-pages-in-markdown

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by cdlm** [comment]
Not directly, if I skimmed the docs correctly, but any markup tool can be supported by [writing a filter](https://nanoc.ws/doc/filters/#writing-filters).

**Comment by ddfreyne** [comment]
As @cdlm said — Nanoc doesn’t come with a filter for reStructuredText, but you can write one yourself. I did a bit of research and it doesn’t look like there are any actively-maintained Ruby libraries for reStructuredText, but you could shell out.

I’ll close this issue for now.
