### ISSUE TITLE
Compilation time 10x with contracts gem installed

### ISSUE THREAD

**Issue by da2x** [nanoc/nanoc#1483]
### Steps to reproduce

1. `gem install contracts`
2. `nanoc create-site test && cd test && touch content/testfile{1..5000}.txt && nanoc && nanoc && nanoc`
3. Note the last compilation time.
4. `gem uninstall contracts`
5. `nanoc create-site test && cd test && touch content/testfile{1..5000}.txt && nanoc && nanoc && nanoc`
6. Note the last compilation time.

### Expected behavior

Fast compilation time.

### Actual behavior

Compilation takes 2.5 seconds w/o the gem and 25 seconds with it installed.

**Comment by da2x** [comment]
@ddfreyne on gitter:

> 1) I recommend running Nanoc using bundler, with a Gemfile that doesn’t have contracts, which will avoid the problem
> 2) If contracts is available, it might be worth printing a warning message

**Comment by ddfreyne** [comment]
Also:

> And it’s probably a good idea to update installation instructions (https://nanoc.ws/doc/installation/) to mention Bundler and how to use it

**Comment by ddfreyne** [comment]
Nanoc will now emit a warning (see #1489) when `contracts` is loaded. Can you check the warning message and see whether it makes sense to you?

**Comment by da2x** [comment]
The message is very clear and actionable. :+1:
