### ISSUE TITLE
@rep not available in Rendering helper

### ISSUE THREAD

**Issue by bobbens** [nanoc/nanoc#1484]
### Steps to reproduce

1. Create a layout that uses @rep (e.g., @rep.name).
2. Try to render the layout with the Rendering helper

### Expected behavior

Normal rendering of the layout.

Document (https://nanoc.ws/doc/reference/helpers/#rendering) says:

> The assigns (@item, @config, …) will be available in the partial. It is also possible to pass custom assigns to the method; these assigns will be made available as instance variables inside the partial.

### Actual behavior

It  will crash because @rep is nil.

### Details

I believe simple @rep is not being defined in the environment created by the Rendering helper. Either the documentation should make clear what is available, or @rep should be added to the environment.

You can get around this by doing something like
```
<%= render '/my_layout.erb', :rep => @rep %>
```

**Comment by ddfreyne** [comment]
This is an oversight on my part — `@item_rep` is available, but `rep` is not. Will fix!
