### ISSUE TITLE
Encoding::CompatibilityError when trying to run nanoc on Windows and Ruby 2.7.1

### ISSUE THREAD

**Issue by ethancrawford** [nanoc/nanoc#1502]
On a windows 10 computer with Ruby 2.7.1 and latest stable release of the nanoc gem installed (4.11.16):
Attempting to run nanoc (for example, to print the version information, or compile a new site, etc) results in an error.
I understand from the tutorial that Windows is not officially supported, but have raised this in case it is useful. I also see that the tutorial says 'Nanoc runs mostly fine on Windows, with some limitations' - are these described anywhere?

### Steps to reproduce
Here's what I did:
1. Install the gem as per the tutorial, in a cmd window
2. Type `nanoc --version` as suggested in the tutorial

### Expected behavior
Nanoc prints out its current version

### Actual behavior
Nanoc prints out some notes, warnings, and an error, as seen below (as well as a stack trace and crash log info, see underneath):
```
------------------------------------------------------------------------------
A NOTE ABOUT PERFORMANCE:
The `contracts` gem is loaded, which enables extra run-time checks, but can drastically reduce Nanoc’s performance. The `contracts` gem is intended for development purposes, and is not recommended for day-to-day Nanoc usage.

To speed up compilation, either uninstall the `contracts` gem, or use Bundler (https://bundler.io/) with a Gemfile that doesn’t include `contracts`.
------------------------------------------------------------------------------
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nanoc-core-4.11.16/lib/nanoc/core/dependency_props.rb:16: warning: The called method `__contracts_ruby_original_initialize_ka39pjaq9zih' is defined here

Captain! We've been hit!

Encoding::CompatibilityError: Unicode Normalization not appropriate for ASCII-8BIT
```

### Details
(Describe other details, if any, that you believe might be relevant.)
Not sure how useful it is, but note that commands such as `nanoc create-site X` appear to work - in as far as when I ran *that*, I get the following output, when creating a site called 'doc' for example:
```
------------------------------------------------------------------------------
A NOTE ABOUT PERFORMANCE:
The `contracts` gem is loaded, which enables extra run-time checks, but can drastically reduce Nanoc’s performance. The `contracts` gem is intended for development purposes, and is not recommended for day-to-day Nanoc usage.

To speed up compilation, either uninstall the `contracts` gem, or use Bundler (https://bundler.io/) with a Gemfile that doesn’t include `contracts`.
------------------------------------------------------------------------------
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/nanoc-core-4.11.16/lib/nanoc/core/dependency_props.rb:16: warning: The called method `__contracts_ruby_original_initialize_ka39ocdx3x7d' is defined here
      create  nanoc.yaml
      create  Rules
      create  content/index.html
      create  content/stylesheet.css
      create  layouts/default.html
Created a blank Nanoc site at 'doc'. Enjoy!
```

### Crash log

(When reporting a crash, create a [Gist](https://gist.github.com/) with the contents of the `crash.log` file, and link the Gist here.)

See https://gist.github.com/ethancrawford/b6b2de0e27b31fc68c0c9e5135f955d3 for the log when running `nanoc --version`.

**Comment by ethancrawford** [comment]
I have noticed that this actually seems related to the contracts gem. Since I was not using bundler to test nanoc, I uninstalled the contracts gem, re-ran `nanoc --version`, and it behaves correctly:
```
Nanoc 4.11.16 (c) 2007–2019 Denis Defreyne.
Running ruby 2.7.1 (2020-03-31) on x64-mingw32 with RubyGems 3.1.2.
```

Feel free to close or transfer this issue if it belongs in the contracts project.

**Comment by ddfreyne** [comment]
Glad to hear it’s solved!

I think the issue is still relevant, though. What Nanoc is doing is filtering out (or transforming) Unicode characters on terminals that don’t support unicode, so that it doesn’t lead to weird output. This filtering/transforming isn’t working on the text written by the `contracts` gem, and I believe Nanoc should be able to deal with that too.

**Comment by ethancrawford** [comment]
It seems that there is a problem still when nanoc tries to load the custom code in `/lib`, at least some of the time.
With a file such as `lib/test.rb` containing the following:
```
def test
  'test'
end
```
The website compiles successfully.

Now, I had been curious about investigating replacing Nanoc's sass integration with sassc - and to begin with, was attempting to recreate your sass filter locally in my site, copying the code from the nanoc gem. So, I started by replacing the content of /lib/test.rb with the content from https://github.com/nanoc/nanoc/blob/master/nanoc/lib/nanoc/filters/sass.rb.

However, this seems to display the same Encoding::CompatibilityError in my original post. I tried cutting out bits of the filter code to see if I could narrow down the issue, and even something as small as this raises the error - it seems to be the line where the constant is set.
```
module Nanoc::Filters
  module SassCommon
    REQUIRES = %w[sass nanoc/filters/sass/importer nanoc/filters/sass/functions].freeze
  end
end
```

Here's the crash.log related to the above instance if you are interested - https://gist.github.com/ethancrawford/e666ba8ffa677f813ff1634eaecbe951

Exactly why the /lib code is a problem in that case, I am not sure. TBH I'm mostly poking around in the dark. I'd be quite happy to assist with this if I knew a bit more - but perhaps my Ruby-fu is not as strong as I had hoped 😂

**Comment by ethancrawford** [comment]
Hey @ddfreyne,
So, after a bunch of time following the stack trace of the error and searching the internet, I appear to have gotten past it, but I am not 100% sure whether it is the correct/desired fix.
I have changed the following line:
https://github.com/nanoc/nanoc/blob/20374c874f2f6759e10d4e8a2c447fb32976d922/nanoc-core/lib/nanoc/core/code_snippet.rb#L40
and I have made it:
```ruby
eval(@data.inspect, TOPLEVEL_BINDING, @filename) 
```
With the above, nanoc can load the test code in the previous comment and successfully compile the site.

I'd welcome your advice on my change here in regards to solving this error. If it's correct, I'd be happy to submit a PR for it, including a spec. However, it's not immediately clear to me what form a spec for this change would take either - so I'd welcome any thoughts you might have on that also.

**Comment by ethancrawford** [comment]
Ha. Ignore the above. That was clearly never going to work.

This one might be a bit beyond me still 😂

**Comment by ethancrawford** [comment]
For larks, I tested something like `$stdout.set_encoding('utf-8')` here:
https://github.com/nanoc/nanoc/blob/0694f68e2dd53bb0fda84c6a3ade19d33f1f18a8/nanoc-cli/lib/nanoc/cli.rb#L43-L46
Still didn't help though. It would be nice if things could be made to work on Windows, but as mentioned, it might not be me that manages it!
