### ISSUE TITLE
Donation link broken

### ISSUE THREAD

**Issue by tbm** [nanoc/nanoc#1506]
The README says:

> Please take a moment and donate to Nanoc. A lot of time has gone into developing Nanoc, and I would like to keep it going. Your support will ensure that Nanoc will continue to improve.

But the Donorbox link gives:

>  Oops!
> We’ve tried searching but couldn’t find the page you’re looking for

**Comment by ethancrawford** [comment]
I had been thinking about doing the same thing initially, but the Nanoc website says at https://nanoc.ws/contributing/ that Denis is no longer accepting donations for the Nanoc project, and instead recommends sending donations elsewhere to other worthy causes.
Going by something I saw in the gitter chat room, it's possible the donation link in the readme was removed in a recent commit to 'master' branch, but possibly in the switch to 'main' becoming the default branch this might have been lost? not sure.

**Comment by ddfreyne** [comment]
I forgot to update the README! Will do so in a bit.

Nanoc is no longer accepting donations because I believe my or Nanoc’s cause isn’t nearly as important as some other ones.

**Comment by ddfreyne** [comment]
I’ve removed the donation link from the README now.

**Comment by ddfreyne** [comment]
If you still want to donate, donate to a worthy cause instead! https://nanoc.ws/contributing/#making-a-donation
