### ISSUE TITLE
Can we make Guard pass options to Nanoc?

### ISSUE THREAD

**Issue by RubenVerborgh** [nanoc/nanoc#1524]
For instance, can we set the environment?

**Comment by ddfreyne** [comment]
There is no direct way to pass options to Guard, but you could set environment variables that Nanoc can read (e.g. in the preprocessor). Would that work? What’s your use case?

**Comment by RubenVerborgh** [comment]
Concretely, I would want Guard to start nanoc with a specific environment such as _development_.

**Comment by ddfreyne** [comment]
You can set the Nanoc environment as the `NANOC_ENV` env variable and that’ll do the trick!
