### ISSUE TITLE
check stale fails unexpectedly with special routing rules

### ISSUE THREAD

**Issue by opatry** [nanoc/nanoc#1526]
### Steps to reproduce

0. Clone https://github.com/opatry/nanoc-check-stale-issue and follow `README.md` instructions.
1. `bundle install`
2. `rm -rf output && bundle exec nanoc && bundle exec nanoc check stale`

### Expected behavior

Check stale is `ok`.

### Actual behavior

Check stale is `error`.

### Details

I'm trying to remove useless files from output. I have a list of photos and each of them has `:excerpt` and `:default` representations and all of them are routed in `output/`.
My goal is to only compile and route some of them for the `:excerpt` representation.

In the `preprocess` block, I listed all photos expected for the `:excerpt` representation, then I ignore stuff in `compile` rule as well as in `route` for all others photos of such representation.

`Rules`
```ruby
all_excerpt_pictures = []

preprocess do
  sorted_articles.each do |item|
    content = item.raw_content
    item[:pictures] = content.scan(/picture\('(.+)'\)/).flatten.uniq

    if content =~ /\s<!-- more -->\s/
      excerpt = content.partition('<!-- more -->').first
      all_excerpt_pictures += excerpt.scan(/picture\('(.+)'\)/).flatten.uniq
    else
      all_excerpt_pictures += item[:pictures]
    end
  end
end

...

[:excerpt, :default].each do |repr|
  compile '/photos/*', :rep => repr do
    unless repr == :excerpt && !all_excerpt_pictures.include?(@item.identifier.to_s)
      width = @config[:picture_width][repr]
      # filter :thumbnailize, :width => width unless @config[:dev]
    end
  end

  compile '/posts/*', :rep => repr do
    ...
  end
end

...

[:excerpt, :default].each do |repr|
  route '/photos/*', :rep => repr do
    unless repr == :excerpt && !all_excerpt_pictures.include?(@item.identifier.to_s)
      "#{@item.identifier.chop}-#{@item_rep.name}.#{@item[:extension]}"
    end
  end
end
```

Everything works fine in terms of `output/` content but `bundle exec nanoc check stale` fails for all photos I want to keep for the `:excerpt` representation.

Note that I rely on snapshot to retrieve `:excerpt` step of compilation of content using such photos.
Maybe It's an effect of the #809 "Stale check ignores non-final snapshot paths" issue?

Output:
```
$ rm -rf output && bundle exec nanoc && bundle exec nanoc check stale
Loading site… done
Compiling site…
      create  [0.00s]  output/photos/The_Osborne_Apartments-default.jpeg
      create  [0.00s]  output/photos/WoodStorkWhole-default.jpeg
      create  [0.00s]  output/photos/WoodStorkWhole-excerpt.jpeg
      create  [0.00s]  output/index.html
      create  [0.01s]  output/2020/12/23/test/index.html

Site compiled in 0.23s.
Loading site… done
  Running check stale…   error
Issues found!
  output/photos/WoodStorkWhole-excerpt.jpeg:
    [ ERROR ] stale - file without matching item

Error: One or more checks failed
```

Commenting special case in `route` rule L66 fixes the issue (but not needed pictures are kept in `output/`: `output/photos/The_Osborne_Apartments-excerpt.jpeg`).

Output:
```
$ rm -rf output && bundle exec nanoc && bundle exec nanoc check stale
Loading site… done
Compiling site…
      create  [0.00s]  output/photos/The_Osborne_Apartments-excerpt.jpeg <<<<---- I do not want this one
      create  [0.00s]  output/photos/The_Osborne_Apartments-default.jpeg
      create  [0.00s]  output/photos/WoodStorkWhole-excerpt.jpeg
      create  [0.00s]  output/photos/WoodStorkWhole-default.jpeg
      create  [0.00s]  output/index.html
      create  [0.03s]  output/2020/12/23/test/index.html

Site compiled in 0.21s.
Loading site… done
  Running check stale…   ok
```

**Comment by opatry** [comment]
If I run `bundle exec nanoc compile --debug --verbose` when it works and when it doesn't:
```diff
284a285
>       create  [0.00s]  output/photos/WoodStorkWhole-excerpt.jpeg
287,289c288,290
<       create  [0.00s]  output/photos/WoodStorkWhole-excerpt.jpeg
<       create  [0.01s]  output/2020/12/23/test/index.html
<       create  [0.01s]  output/index.html
---
>       create  [0.00s]  output/photos/The_Osborne_Apartments-excerpt.jpeg
>       create  [0.00s]  output/index.html
>       create  [0.03s]  output/2020/12/23/test/index.html
300,301c301,302
<      erb │     9   0.00s   0.00s   0.01s   0.01s   0.01s   0.01s
< kramdown │     3   0.00s   0.00s   0.05s   0.05s   0.06s   0.06s
---
>      erb │     9   0.00s   0.00s   0.02s   0.02s   0.03s   0.05s
> kramdown │     3   0.00s   0.00s   0.06s   0.07s   0.08s   0.08s
303c304
< Site compiled in 0.19s.
---
> Site compiled in 0.20s.
```

The steps seem really comparable.

When I execute `bundle exec nanoc show-data`:
```diff
34,36d33
<   [ raw  ] /Users/opatry/work/opatry.net/test/output/photos/The_Osborne_Apartments-excerpt.jpeg
<   [ last ] /Users/opatry/work/opatry.net/test/output/photos/The_Osborne_Apartments-excerpt.jpeg
<   [ pre  ] /Users/opatry/work/opatry.net/test/output/photos/The_Osborne_Apartments-excerpt.jpeg
```

**Comment by opatry** [comment]
I tried adding this to help understand:
```ruby

postprocess do
  @items.each do |item|
    puts "Item #{item.identifier}"
    item.reps.each do |repr|
      puts " --- Rep #{repr.name} -> #{item.path :rep => repr.name}"
    end
  end
end
```

With the following (again, expected) output:
```
Item /posts/2020-12-23-test/
 --- Rep excerpt -> 
 --- Rep default -> /2020/12/23/test/
Item /
 --- Rep default -> /
Item /photos/The_Osborne_Apartments/
 --- Rep excerpt -> 
 --- Rep default -> /photos/The_Osborne_Apartments-default.jpeg
Item /photos/WoodStorkWhole/
 --- Rep excerpt -> /photos/WoodStorkWhole-excerpt.jpeg
 --- Rep default -> /photos/WoodStorkWhole-default.jpeg
```

**Comment by opatry** [comment]
I'd say it's because `preprocess` isn't call when using `check stale`.
When routing isn't tweaked using `preprocess` rule, impl of `item_rep_paths` returns:
```ruby
#<Set: {
  "..../test/output/2020/12/23/test/index.html"
  "..../test/output/index.html"
  "..../test/output/photos/The_Osborne_Apartments-excerpt.jpeg"
  "..../test/output/photos/The_Osborne_Apartments-default.jpeg"
  "..../test/output/photos/WoodStorkWhole-excerpt.jpeg"
  "..../test/output/photos/WoodStorkWhole-default.jpeg"
}>
```

When special routing:
```ruby
#<Set: {
  "..../test/output/2020/12/23/test/index.html"
  "..../test/output/index.html"
  "..../test/output/photos/The_Osborne_Apartments-default.jpeg"
  "..../test/output/photos/WoodStorkWhole-default.jpeg"
}>
```

So, it seems to be the root cause of my trouble.
I'm not sure what to do now.
I do not understand `nanoc` internals enough to determine how execute `preprocess` or if it's even suitable.

In the meantime, I can inverse the condition in my impl to list pictures to remove instead of those to keep and it should work but it would be a bit odd and just a workaround I guess.

**Comment by opatry** [comment]
I created a PR opatry/nanoc-check-stale-issue#1 to illustrate the workaround.

**Comment by ddfreyne** [comment]
The preprocessor definitely needs to be run before running checks! Will fix.

**Comment by ddfreyne** [comment]
The underlying issue is likely related to how Nanoc interprets the Rules file, rather than the preprocessor not running.

If you replace `all_excerpt_pictures` with `@config[:all_excerpt_pictures]` (and move the first line into the preprocessor), it works as intended:

```ruby
preprocess do
  @config[:all_excerpt_pictures] = []

  sorted_articles.each do |item|
    content = item.raw_content
    item[:pictures] = content.scan(/picture\('(.+)'\)/).flatten.uniq

    if content =~ /\s<!-- more -->\s/
      excerpt = content.partition('<!-- more -->').first
      @config[:all_excerpt_pictures] += excerpt.scan(/picture\('(.+)'\)/).flatten.uniq
    else
      @config[:all_excerpt_pictures] += item[:pictures]
    end
  end
end
```

Using top-level local variables in the Rules file will often cause issues.

As an alternative, `@config` can be used for storage.

**Comment by opatry** [comment]
Ok, I'll try this approach, thanks for feedback.

**Comment by opatry** [comment]
Indeed, works perfectly fine! 👌 
Illustrated in my sample repo in PR opatry/nanoc-check-stale-issue/pull#2

Works also on my initial project.

Thanks for support 🙇‍♂️

**Comment by ddfreyne** [comment]
For completeness: The topic of detecting and/or preventing problematic usage of the Rules file (such as the one in this GitHub issue) has been on my mind, but I’m still unsure how to tackle this, or even whether this problem can be solved at all with the current way the Rules file works.

I feel that for a rules DSL, Ruby as a programming language is simply too powerful. Nanoc makes some effort in reducing what can be done in the Rules file, but there are limitations to what it can prevent/detect.
