### ISSUE TITLE
When idle "nanoc live" consumes 200% CPU!

### ISSUE THREAD

**Issue by Ecco** [nanoc/nanoc#1537]
### Steps to reproduce

1. Run `nanoc live`
2. Wait for compilation to finish, and don't make any change to the website whatsoever
2. See how CPU fan goes crazy

### Expected behavior

Nanoc live should be consuming no CPU at all since it is doing nothing.

### Details

Nanoc gives me very little info unfortunately. In the terminal, I have:
I get very little info, actually.  In the terminal, everything seems fine (nanoc is waiting for changes):
```
bundle exec nanoc live -o 0.0.0.0 -p 3001
Listening for lib/ changes…
View the site at http://0.0.0.0:3001/
[2021-01-05 14:22:45] INFO  WEBrick 1.4.2
[2021-01-05 14:22:45] INFO  ruby 2.6.6 (2020-03-31) [x86_64-darwin20]
[2021-01-05 14:22:45] INFO  WEBrick::HTTPServer#start: pid=61099 port=3001
Compiling site…
Site compiled in 3.08s.

Listening for site changes…
Reloading site… done
Compiling site…
Site compiled in 3.71s.
```

Yet the CPU is very busy, and `top` gives me:
```
Processes: 428 total, 5 running, 423 sleeping, 1554 threads                                                                                                                                            14:23:24
Load Avg: 2.30, 2.71, 3.11  CPU usage: 13.97% user, 4.27% sys, 81.75% idle  MemRegions: 139513 total, 5618M resident, 0B private, 2669M shared. PhysMem: 27G used (4029M wired), 37G unused.
VM: 2615G vsize, 0B framework vsize, 0(0) swapins, 0(0) swapouts. Networks: packets: 9636417/8341M in, 6348763/4234M out. Disks: 586037/7964M read, 2089903/28G written.

PID    COMMAND      %CPU  TIME     #TH    #WQ  #PORT MEM    PURG   CMPR PGRP  PPID  STATE    BOOSTS         %CPU_ME %CPU_OTHRS UID  FAULTS     COW      MSGSENT    MSGRECV    SYSBSD     SYSMACH    CSW
61112  ruby         120.2 00:46.74 21/1   0    28    213M+  0B     0B   61097 61099 running  *0[1]          0.00000 0.00000    501  112908+    10668    26         12         5434138+   392+       1005389+
61099  ruby         104.7 00:41.58 30/1   0    51    43M+   0B     0B   61097 61097 running  *0[1]          0.00000 0.00000    501  18467+     5100     168        71         3540896+   612+       183725+
```
See the 100% load on each process.

And `ps ax` gives:
```
61099 s031  R+     0:57.69 /Users/ecco/.rbenv/versions/2.6.6/bin/nanoc live -o 0.0.0.0 -p 3001
61112 s031  R+     1:05.29 /Users/ecco/.rbenv/versions/2.6.6/bin/nanoc live -o 0.0.0.0 -p 3001
```

### Environment

- macOS 11.1
- ruby 2.6.6p146 
- nanoc 4.11.15

**Comment by iay** [comment]
For what it's worth, I upgraded my main machine to Big Sur just yesterday and started noticing this same behaviour. I am _fairly_ sure it didn't happen under Catalina.

I have been running Big Sur on my secondary machine since it went GA, but unfortunately haven't been using `nanoc live` there, so I can't be certain this isn't machine-specific.

**Comment by ddfreyne** [comment]
I’ve noticed this behavior as well (pre-Big Sur too) and it is one of the reasons why nanoc-live isn’t at 1.0 yet.

I’ve not had much luck in debugging this issue, but can you try the following:

Edit `nanoc-live/lib/nanoc/live/live_recompiler.rb` and change

```ruby
            wait_for_delay: 0.0,
```

to

```ruby
            wait_for_delay: 0.1,
```

on lines 114 and 128.

In addition, edit `nanoc/lib/nanoc/data_sources/filesystem.rb` and change

```
          Listen.to(dir, latency: 0.1, wait_for_delay: 0.0)
```

to

```
          Listen.to(dir)
```

With these changes, do you still experience this issue?

**Comment by ddfreyne** [comment]
Can you upgrade `nanoc` to 4.11.23 and `nanoc-live` to 1.0.0b8, and see whether the issue persists? With the new versions, I can not reproduce this issue anymore. @Ecco

**Comment by iay** [comment]
Again, for whatever it's worth, I switch to 4.11.23 and switched from `guard-nanoc` to `nanoc-live` (and got 1.0.0b8) and my idle CPU has dropped to zero.

(I'm also enjoying the page reload functionality, which I don't think `guard-nanoc` provided.)

**Comment by Ecco** [comment]
So, this bug *just* hit me again. I simply:
 - Removed the "tmp" and "output" dir
 - Ran `bundle update nanoc` and `bundle update nanoc-live`

This brought me to the exact versions you mentioned.

And… apparently the bug is gone! Yay!

I'll add a comment here if it ever happens again!

Thank you **so much** for fixing this!

**Comment by ddfreyne** [comment]
Sweet!

I think this probably makes nanoc-live ready to be a 1.0!
