### ISSUE TITLE
Ruby sass end of life

### ISSUE THREAD

**Issue by bkmgit** [nanoc/nanoc#1545]
### Details

sass has reached end of life https://sass-lang.com/ruby-sass

Is [sasc](https://github.com/sass/sassc-ruby) a reasonable alternative?

**Comment by ddfreyne** [comment]
Hey Benson,

Ruby Sass indeed needs to be replaced in Nanoc, but I haven’t made much progress with it yet. sassc (and the associated [libsass](https://github.com/sass/libsass)) are also deprecated, and are therefore not a good choice.

@a4z wrote a Dart Sass filter that shells out. See the Gitter conversation here: https://gitter.im/nanoc/nanoc?at=60e1f6179cf31717300d966e. For the time being, this might be an option for you. (Note that it doesn’t track Sass file dependencies yet, which is something that the a `:dart_sass` filter included with Nanoc would have to do.)

See also https://github.com/nanoc/features/issues/45.

**Comment by DannyBen** [comment]
The sass guys really did a number on the entire Ruby community with the dart move...

**Comment by DannyBen** [comment]
For what its worth:

1. As far as I can see in other Ruby based web frameworks, they all moved to `sassc`, I believe nanoc should do the same.
2. I am totally **not** in favor of having a `:dart_sass` filter. This is an "implementation detail" and is not a concern of the user. The `sass` filter should work using the best tool possible. Perhaps it should even "decide" how to convert, in a similar way that rack apps choose the best available server handler.
3. Either way - I believe this should be fixed soon. The Ruby SASS is EOL for a long time now.

**Comment by denisdefreyne** [comment]
`sassc` is not a good option, as it too is deprecated.

**Comment by a4z** [comment]
what about https://github.com/ntkme/sass-embedded-host-ruby

That is ruby and uses the dart sass.
Have not tried it so far, but maybe I will give it a try in some future

**Comment by denisdefreyne** [comment]
@a4z That looks like a good base! For Nanoc, it would need to have custom `importers` so that it can handle `@imports`, and do correct dependency tracking -- I think that’s one of the main tricky bits.

**Comment by DannyBen** [comment]
> it would need to have custom `importers` so that it can handle `@imports`

[Something like this?](https://github.com/DannyBen/sasstool/blob/master/lib/sasstool/importer.rb)

**Comment by DannyBen** [comment]
> what about https://github.com/ntkme/sass-embedded-host-ruby

There is also the more specific sassc dart shim
https://github.com/ntkme/sassc-embedded-shim-ruby

as mentioned in https://github.com/sass/sassc-ruby/issues/220

**Comment by denisdefreyne** [comment]
Yes, but without using `sassc` or `libsass`, as both are deprecated.

**Comment by denisdefreyne** [comment]
I’ve (finally) gotten around to testing out `sass-embedded`/`sass-embedded-host-ruby`, and it seems to be working well:

```ruby
require 'sass-embedded'

def make_dart_sass_importer(items)
  {
    canonicalize: lambda do |param, **|
      'nanoc:' + items[param.sub(/\Ananoc:/, '')].identifier
    end,
    load: lambda { |url|
      param = url.sub(/\Ananoc:/, '')
      item = items[param]
      return {
        contents: item.raw_content,
        syntax: item.identifier.ext
      }
    }
  }
end

Nanoc::Filter.define(:dart_sass) do |content, _params = {}|
  result = Sass.compile_string(
    content,
    importer: make_dart_sass_importer(@items),
    syntax: item.identifier.ext
  )
  result.css
rescue StandardError => e
  warn e.full_message
  raise e
end
```

This provides a `:dart_sass` filter. It certainly needs more polish, but so far it seems to work quite well. It doesn’t have sourcemap support, though that should be easy enough to add, and also doesn’t have a `nanoc()` function yet.

**Comment by denisdefreyne** [comment]
And a PR to prepare the `nanoc-dart-sass` gem: #1627

**Comment by 0x1eef** [comment]
@denisdefreyne 

> (Note that it doesn’t track Sass file dependencies yet, which is something that the a :dart_sass filter included with Nanoc would have to do.)

Curious - how do you plan to solve that ? Thanks !

**Comment by denisdefreyne** [comment]
> Curious - how do you plan to solve that ? Thanks !

The `nanoc-dart-sass` filter already takes care of that. It pretty much work out of the box because of how the filter works; it gets the content via `@items` so it works with the dependency tracker automatically.

**Comment by 0x1eef** [comment]
@denisdefreyne 

What if there happened to be `main.scss`, and `other_main.scss` ? `main.csss` would have a set of unique dependencies, and `other_main.scss` would have another set of unique dependencies. Would a rebuild of both those entry points be triggered regardless of what dependency changed? Thanks!

**Comment by denisdefreyne** [comment]
Only the necessarily rebuilds will happen, so `main.scss` could be unaffected while `other_main.scss` would be rebuilt.

**Comment by 0x1eef** [comment]
Oh - wow !  I didn't realize that. Could that also work for https://github.com/0x1eef/nanoc-webpack.rb ? At the moment each manifest declares its dependencies, but maybe they don't have to ? I don't quite see how it works. It would be amazing if it was unneccessary though.

**Comment by denisdefreyne** [comment]
@0x1eef Unfortunately not. The reason why it works for the Nanoc `:dart_sass` filter is because it fetches content from `@items`, which Webpack won’t do.

See the [dart_sass filter.rb](https://github.com/nanoc/nanoc/blob/main/nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb#L41-L43):

```ruby
        def load(url)
          item = @items[url.sub(/\Ananoc:/, '')]
          {
            contents: item.raw_content,
            syntax: Util.syntax_from_ext(item.identifier.ext),
          }
        end
      end
```

The `@items[…]` and `item.raw_content` expressions are what create the dependencies, and therefore ensure that dependent items are recompiled when needed, without having to declare dependencies manually.

I think the way Dart Sass handles imports is fantastic, and makes integrating it with Nanoc so seamless. I wish more tools took this approach!

---

In other news, I’m preparing to release the Nanoc `:dart_sass` filter hopefully quite soon.

**Comment by DannyBen** [comment]
Am I the only one who feels that the move from ruby sass to dart-sass has sucked all the fun out of sass? I have started using plain vanilla CSS because of all the overhead...

**Comment by denisdefreyne** [comment]
The `nanoc-dart-sass` 1.0.0 gem is now released.

I’ll close this issue now. There are future enhancements possible (such as adding support for sourcemaps) but I’d like to tackle that in the future.

**Comment by 0x1eef** [comment]
Nice work ! And thanks for the explanation.
