### ISSUE TITLE
asciidoctor document title removed by nanoc

### ISSUE THREAD

**Issue by luc-j-bourhis** [nanoc/nanoc#1568]
### Steps to reproduce

An asciidoc file `something.adoc` starting with

```
= My great title

== Introduction
...
```

Then, on one hand, a Nanoc rule `filter :asciidoctor` to compile it. And on the other hand, run `asciidoctor something.adoc` on the command-line. 

### Expected behavior

I would expect the `something.html` produced in the two manners above to both have the document title. Specifically, that they both contain

```
...
<body class="article">
<div id="header">
<h1>My great title</h1>
</div>
<div id="content">
<div class="sect1">
<h2 id="_introduction">Introduction</h2>
...
```

### Actual behavior

Instead Nanoc produces:

```
...
<body>
<div class="sect1">
<h2 id="_introduction">Introduction</h2>
...
```

Note also that the `body` class lacks the `article` class, which makes the asciidoctor stylesheet misbehave. 

### Details

From my Gemfile.lock,

 -  nanoc (4.12.4)
 -  asciidoctor (2.0.17)

### Crash log

None

**Comment by luc-j-bourhis** [comment]
The problem was not with Nanoc after all. The rule must be
```
filter :asciidoctor, { attributes: "showtitle" }
```
Asciidoctor CLI must do this by default but not the API, and it's not documented anywhere I could find: I had to read asciidoctor code!

**Comment by ddfreyne** [comment]
Good catch! I wasn’t aware of `showtitle`.
