### ISSUE TITLE
nanoc 4.12 binary cache copies read-only source permissions then attempts to open for writing

### ISSUE THREAD

**Issue by draconx** [nanoc/nanoc#1572]
### Details

It appears that the new binary cache files in nanoc 4.12 are created with file mode bits copied from the corresponding source file in the content directory.

If some of the source files are read-only a clean build will work, but nanoc will crash when it needs to rebuild these binary items because it attempts to open read-only cache files for writing.

This is a regression from nanoc 4.11 where read-only binary items work OK.

### Steps to reproduce

    % nanoc create-site repro
    % cd repro
    % : >content/repro.jpg
    % chmod -w content/repro.jpg
    % nanoc
    [ this goes ok ]
    % rm -f output/repro.jpg
    % nanoc
    [ crash! ]

### Expected behavior

Cache files should be created with write permissions so that they can be opened for writing.

### Actual behavior

Cache files are created without write permissions and thus cannot be opened for writing.

### Crash log

https://gist.github.com/draconx/7285bd0f38644728815603fb48596489

**Comment by draconx** [comment]
This is the failing syscall:

    openat(AT_FDCWD, "/tmp/repro/tmp/nanoc/ea7dcf6678f0f/binary_content_data/_repro_jpg-3238dce643/default-7505d64a54/raw-ce15802a8c", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0100444) = -1 EACCES (Permission denied)

**Comment by ddfreyne** [comment]
Thanks for reporting! I’ve been out for a while, but will pick up this bug soon.

**Comment by ddfreyne** [comment]
This is fixed in the newly-released Nanoc 4.12.6.
