### ISSUE TITLE
nanoc-4.12.6 crashes with external metadata on binary items

### ISSUE THREAD

**Issue by draconx** [nanoc/nanoc#1577]
### Steps to reproduce

    % nanoc create-site repro
    % cd repro
    % : >content/test.jpg
    % cat >content/test.yaml <<'EOF'
    ---
    title: test
    EOF
    % nanoc
    [ crash! ]

### Expected behavior

Site should be created successfully.

### Actual behavior

nanoc crashes: "ArgumentError: unknown keyword: permitted_classes"

### Details

External metadata seems to work (at least, there is no crash) for text items.
This problem is not observed in nanoc-4.12.5

### Crash log

https://gist.github.com/draconx/122e8fe7bfb88309d1d6c38abf0dbaf8

**Comment by ddfreyne** [comment]
This is a regression introduced by #1574.

A workaround is to use a newer version of Psych. I believe `psych` `~> 4.0` would work.

**Comment by ddfreyne** [comment]
Related: #1566 which fixes a similar issue. Unfortunately, there is no `safe_load_file` in older versions of Psych.

**Comment by ddfreyne** [comment]
This is released in 4.12.7.
