### ISSUE TITLE
replace uglifier with terser gem

### ISSUE THREAD

**Issue by pravi** [nanoc/nanoc#1578]
### Steps to reproduce

terser is better maintained fork of uglify-js and most projects have switched to terser. terser gem provides similar functionality to replace uglifier gem.

### Expected behavior

Should use terser instead of uglifier.

### Actual behavior

Still using uglifier

### Details

In debian we are trying to remove uglifier and nanoc is the last dependency blocking it. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=981224

**Comment by ddfreyne** [comment]
I have an implementation of this here: https://github.com/nanoc/nanoc/pull/1579.

**Comment by pravi** [comment]
Thanks!

**Comment by ddfreyne** [comment]
This is released in 4.12.7.
