### ISSUE TITLE
Consider making html_escape escape more characters

### ISSUE THREAD

**Issue by SamStephens** [nanoc/nanoc#1590]
### Steps to reproduce

1. Escape an HTML attribute that you've used single quotes with. E.g. `<img src='<%= item[:image_url]%>' alt='<%= html_escape(item[:image_title])%>'>`.
2. Think that you are safe.
3. Suffer an XSS attack using single quotes in the image_title attribute.

### Expected behavior

Single quotes to be escaped.

### Actual behavior

Single quotes are not escaped, meaning there's an injection attack.

### Details

I'd expect a broader set of characters to be escaped. [Rails escapes single quotes](https://api.rubyonrails.org/classes/ERB/Util.html). You could consider more https://wonko.com/post/html-escaping/.

**Comment by denisdefreyne** [comment]
Thanks! I’ve added single-quote escapes in #1524.

Thanks for linking to the article on HTML escaping, too. Some of the stuff is outside of what Nanoc can provide, but I think Nanoc could still provide some functionality to make escaping more obvious. I’m thinking a HTML tag helper, for instance:

```erb
<% tag(:a, href: "https://example.com/?a=1&b=2") do %>
  Link text here
<% end %>
```

… which would take care of escaping automatically. I also think it’s nicer than this:

```erb
<a href="<%=h "https://example.com/?a=1&b=2" %>">
  Link text here
</a>
```

… which is far harder to read, in my opinion.

Food for thought, I suppose!

**Comment by SamStephens** [comment]
Thanks Denis, and thanks for your prompt response to all my issues.

Looks like you've linked to issue 1524 rather than pull request 1524 above.

As far as the article goes, it's more for interests sake, I don't really think protecting against unquoted attribute values is a requirement.

The tag helper idea is interesting. For me I find the second form more readable, because I don't have to translate it into it's HTML representation in my head. I think you need a Rails background for the first form to be more readable (to be fair, I suspect most people using Nanoc have a Rails background).

I think the key question here is philosophical: feature richness vs. simplicity.

----

Off topic, but while I have you, something you might be interested in: I've created [an action to allow for use of Nanoc for publishing Github pages](https://github.com/SamStephens/nanoc-build-pages), now [Github pages publishes using actions, to support different site generators](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/).

**Comment by denisdefreyne** [comment]
> The tag helper idea is interesting. For me I find the second form more readable, because I don't have to translate it into it's HTML representation in my head.

It’s a new day, and I now think that plain-old-HTML approach of `<a href="…` is more readable, too. It’s searchable as well (searching for `<a href` won’t find the `tag(:a`) uses).

I suppose that Nanoc has gone without a tag helper for 15+ years, so adding one is very much not urgent at all :)

Nice work on the Nanoc GitHub action!
