### ISSUE TITLE
Documentation references deprecated guard-nanoc gem

### ISSUE THREAD

**Issue by SamStephens** [nanoc/nanoc#1591]
https://nanoc.app/doc/sites/ points people to [guard-nanoc](https://github.com/guard/guard-nanoc):

> You can use [guard-nanoc](https://github.com/guard/guard-nanoc) to automatically recompile the site when it changes.

However, according to https://nanoc.app/whats-new/#better-live-recompilation, guard-nanoc has now been superseded by nanoc-live.

**Comment by denisdefreyne** [comment]
Good catch! I’ve updated the [Compiling a site](https://nanoc.app/doc/sites/#compiling-a-site) section on the Nanoc web site with instructions on how to set up and use `nanoc-live`.
