### ISSUE TITLE
Add deprecation notice to guard-nanoc/README.md

### ISSUE THREAD

**Issue by SamStephens** [nanoc/nanoc#1592]
According to https://nanoc.app/whats-new/#better-live-recompilation, guard-nanoc has been replaced by nanoc-live. It would be good to place a notice in the guard-nanoc README.md about this deprecation.

**Comment by denisdefreyne** [comment]
Thanks! I’ve updated the README of `guard-nanoc` to point to the new [live recompilation documentation](https://github.com/nanoc/nanoc/tree/main/guard-nanoc).
