### ISSUE TITLE
HAML partial rendering fails because of missing `_erbout` binding

### ISSUE THREAD

**Issue by freesteph** [nanoc/nanoc#1639]
### Steps to reproduce

1. Setup HAML for a simple nanoc project ;
2. Try and render a HAML partial with a block ;
3. Rendering fails

### Expected behavior

The template compiles normally.

### Actual behavior

```
NameError: undefined local variable or method `_erbout' for #<Nanoc::Core::Context:0x0000000107a373b8 @content="%h1 My simple page.\n\n= render(\"/partials/foobar.haml\") do\n  %h2 This should work normally\n", @item=<Nanoc::Core::CompilationItemView identifier=/page.haml>, @rep=<Nanoc::Core::CompilationItemRepView item.identifier=/page.haml name=default>, @item_rep=<Nanoc::Core::CompilationItemRepView item.identifier=/page.haml name=default>, @items=<Nanoc::Core::ItemCollectionWithRepsView>, @layouts=<Nanoc::Core::LayoutCollectionView>, @config=<Nanoc::Core::ConfigView>>
```

### Details

I'm probably doing something wrong but I just cannot figure out what it is. I've made [a repo with the full files](https://github.com/freesteph/nanoc-haml-block-bug) but it looks roughly like this:

```haml
# content/page.haml
%h1 Example page

= render("/partials/foobar.haml") do
  %h2 This should work normally
```

```haml
# layout/partials/foobar.haml
.foobar
  %h2 This is a partial rendered from a page

  - if block_given?
    = yield
```

### Crash log

https://gist.github.com/freesteph/13a20fe7a618f1229e2d6b7c6073a8d6

Thank you.

**Comment by denisdefreyne** [comment]
This is likely the result of Haml 6.0 changing the API (see #1595).

I haven’t been able to figure out how to make the filtering helper work with Haml 6, and the same underlying reason is making it impossible to use `#render` with a block.

**Comment by freesteph** [comment]
So I've been exploring `nanoc` + `tilt` + `haml` + `temple` over the holidays and my mind is absolutely numbed at this point. Not only that but after writing lots of terrible hacks and spending hours in debug statements it turns out the fix might be disappointingly simple and consists in replicating the options used to coerce the Slim filter.

```diff
From a5fb9efd821419f8b8e4f1248587182292af00e0 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?St=C3=A9phane=20Maniaci?= <stephane.maniaci@gmail.com>
Date: Wed, 28 Dec 2022 00:15:17 +0100
Subject: [PATCH] filters: get the Haml filter to play nicely

We rely on an output buffer of `_erbout`, and we want to handle
`capture` statements ourselves, which was already being done for the
Slim filter but not the Haml one.
---
 nanoc/lib/nanoc/filters/haml.rb | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git a/nanoc/lib/nanoc/filters/haml.rb b/nanoc/lib/nanoc/filters/haml.rb
index 8d57d8df6..052b58efe 100644
--- a/nanoc/lib/nanoc/filters/haml.rb
+++ b/nanoc/lib/nanoc/filters/haml.rb
@@ -15,7 +15,11 @@ module Nanoc::Filters
     # @return [String] The filtered content
     def run(content, params = {})
       # Get options
-      options = params.merge(filename: filename)
+      options = params.merge(
+        filename: filename,
+        outvar: '_erbout',
+        disable_capture: true
+      )
 
       # Create context
       context = ::Nanoc::Core::Context.new(assigns)
-- 
2.38.1

```

Hopefully this provides a starting point for an actual fix, or better yet, might be the fix? Do let me know if I can be of any help when you get a chance to look at it.

**Comment by denisdefreyne** [comment]
Ooh, thanks for looking into this! I’m short on time, but will try to give this a closer look. PRs are also always appreciated too!

**Comment by willtcarey** [comment]
I was getting this error and https://github.com/nanoc/nanoc/issues/1639#issuecomment-1366257238 seemed to fix my issue.

I just added it to my Rules file so I didn't have to monkey patch the gem.
```
layout '/*.haml', :haml, format: :html5, disable_capture: true, outvar: '_erbout'
```

**Comment by freesteph** [comment]
Hi @denisdefreyne, any chance you could glance at this sometime? It still seems to be happening with the unpatched nanoc main branch.

**Comment by denisdefreyne** [comment]
I have a fix available in #1719.

I had some trouble reproducing it, needing `- _erbout << yield` rather than `= yield`, to avoid the escaping of the rendered content. (I’m not very familiar with Haml as I don’t use it myself.)

**Comment by freesteph** [comment]
Oh great, thank you! Do you want me to (try and) craft an example repo?

**Comment by denisdefreyne** [comment]
@freesteph Could you test out this change for your repositories on this particular Nanoc branch?

To do so, replace the `nanoc` line in your Gemfile with this:

```ruby
gem 'nanoc', branch: 'denis/fix-haml-erbout', glob: 'nanoc/*.gemspec'
```

You might also need to add the following lines temporarily – but only add them if `bundle install` fails:

```ruby
gem 'nanoc-cli',  branch: 'denis/fix-haml-erbout', glob: 'nanoc-cli/*.gemspec'
gem 'nanoc-core', branch: 'denis/fix-haml-erbout', glob: 'nanoc-core/*.gemspec'
```

After `bundle install`, the `:haml` filter should work out of the box. Can you verify?

**Comment by freesteph** [comment]
@denisdefreyne the fix works great over here. There are some `Haml::TempleEngine: Option :line is invalid` warnings along the way but nothing that should stop the release of this fix. Thank you! ⭐

**Comment by denisdefreyne** [comment]
Thanks! I’ll release a new Nanoc version soon.

**Comment by denisdefreyne** [comment]
This is now released in Nanoc 4.13.3.

**Comment by gizmomogwai** [comment]
I found this thread because I had problems after upgrading from an ancient version of nanoc to 4.13.3.
My site uses haml not only for content but also for layouts. 
Even if I use straight forward html content and put that in the layout it gets escaped there.
Replacing e.g.

    %div= yield

with 

    %div
      - _erbout << yield

repairs it, but makes everything really look ugly!

Is this another issue, or should this be fixed in 4.13.3?

**Comment by denisdefreyne** [comment]
> Even if I use straight forward html content and put that in the layout it gets escaped there. Replacing e.g.
> 
> ```
> %div= yield
> ```

As I understand it, in recent Haml versions, `= yield` will indeed perform escaping.

The workaround is `- _erbout << yield` as you suggested, though I’m not sure what you mean by “makes everything really look ugly” — are you referring to the syntax of `- _erbout << yield`?

**Comment by gizmomogwai** [comment]
i can live with that .. i need to do several places with - _erbout << yield as i have also some small code snippets that produce output.
