### ISSUE TITLE
Caching doesn't work if more than two data sources other than the default are defined

### ISSUE THREAD

**Issue by axilleas** [nanoc/nanoc#1640]
### Steps to reproduce

1. Define two more data sources in `nanoc.yaml`  apart from the default one (three in total).
2. Run `nanoc compile` to build the site.
3. Run `nanoc compile` again and see all the files being built again.

### Expected behavior

Nanoc shoudn't compile the files that haven't changed since their last compilation.

### Actual behavior

Nanoc always compiles all the files, no matter if a file has changed or not.

### Details

This bug seems to have appeared after https://github.com/nanoc/nanoc/pull/1637 was introduced.

We stumbled upon this issue in the GitLab documentation, for more info see https://gitlab.com/gitlab-org/gitlab-docs/-/issues/1336.

**Comment by denisdefreyne** [comment]
I am unable to reproduce the problem with a small test site, and the GitLab Docs site somehow started compiling extremely slowly, which makes this problem quite hard to debug (on average 20–30s per page, while it should be a fraction of a second).

**Comment by denisdefreyne** [comment]
@axilleas Can you check whether https://github.com/nanoc/nanoc/pull/1644 solves the issue for you?

You were correct in that having multiple data sources surfaces the problem, though they need to have `items_root` set. A bug was introduced in https://github.com/nanoc/nanoc/pull/1603 that made item/layout references (used in outdatedness checking and dependency tracking) not update when item/layout identifiers were changed.

**Comment by denisdefreyne** [comment]
This should be fixed in the just-releases Nanoc 4.12.15. Can you verify?

**Comment by axilleas** [comment]
@denisdefreyne yes! Confirmed that it works! Thank you once again!
