### ISSUE TITLE
migration from sass filter to dart_sass filter leads to a crash

### ISSUE THREAD

**Issue by doc75** [nanoc/nanoc#1646]
### Steps to reproduce

1. unzip [dart-sass-sample.zip](https://github.com/nanoc/nanoc/files/10950681/dart-sass-sample.zip)
2. cd dart-sass-sample
3. bundle update
4. bundle exec nanoc

### Expected behavior

the file `output/css/bulma.min.css` is created

### Actual behavior

Crash during site compilation:
```
Loading site… done
Compiling site…

Captain! We’ve been hit!

Sass::CompileError: /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-dart-sass-1.0.0/lib/nanoc/dart_sass/filter.rb:37:in `canonicalize': undefined method `identifier' for nil:NilClass (NoMethodError)

          "nanoc:#{@items[url.sub(/\Ananoc:/, '')].identifier}"
                                                  ^^^^^^^^^^^
	from /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded/host/importer_registry.rb:53:in `canonicalize'
	from /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded/host.rb:92:in `canonicalize_request'
	from /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded/dispatcher.rb:88:in `public_send'
	from /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded/dispatcher.rb:88:in `block in receive_message'


Current item: /assets/css/bulma-custo.sass (:default representation)

  0. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded/protofier.rb:16:in `from_proto_compile_response'
  1. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded/host.rb:66:in `compile_request'
  2. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded.rb:216:in `compile_string'
  3. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/sass-embedded-1.59.2-x86_64-linux-gnu/lib/sass/embedded.rb:53:in `compile_string'
  4. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-dart-sass-1.0.0/lib/nanoc/dart_sass/filter.rb:19:in `run'
  5. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-core-4.12.15/lib/nanoc/core/filter.rb:188:in `setup_and_run'
  6. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-core-4.12.15/lib/nanoc/core/executor.rb:22:in `filter'
  7. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-core-4.12.15/lib/nanoc/core/compilation_phases/recalculate.rb:32:in `block in run'
  8. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-core-4.12.15/lib/nanoc/core/action_sequence.rb:48:in `each'
  9. /home/user/.rvm/gems/ruby-3.2.1@nanoc/gems/nanoc-core-4.12.15/lib/nanoc/core/action_sequence.rb:48:in `each'
  ... 7 lines omitted (see crash.log for details)

A detailed crash log has been written to ./crash.log.
```

### Details

[sass-sample.zip](https://github.com/nanoc/nanoc/files/10950680/sass-sample.zip) is the initial version using `sass` before doing the migration to `dart_sass` and it is working fine

### Crash log

https://gist.github.com/doc75/5670b74f6d759ff421fe15091e9e1659

**Comment by ttych** [comment]
Hello,

I had the same issue,
when trying to move from sass to dart_sass, to move from @import to @use syntax.

It seem's that is the sass compiler,
it injects all the @items (all compiled elements from the site),

https://github.com/nanoc/nanoc/blob/f14166910059ab7150072ba89be3b8dd3e7654c4/nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb#L19

So the @items looks like : 
- /assets/css/bulma-custo.sass
- /assets/css/bulma/sass/utilities/initial-variables.sass
- ....

So when at the first @import or @use, it tries to solve this, by look into the NanocImport,
so try to look for "bulma/sass/utilities/initial-variables"
as the import line is : 
`@import "bulma/sass/utilities/initial-variables"`
but the entry in the NanocImporter object is  "/assets/css/bulma/sass/utilities/initial-variables.sass"

https://github.com/nanoc/nanoc/blob/f14166910059ab7150072ba89be3b8dd3e7654c4/nanoc-dart-sass/lib/nanoc/dart_sass/filter.rb#L37
is equivalent to nil.identfier
which generates the error message you have.

So this example works:

content/css/a.sass:
```
@import "/css/b.sass"
```

content/css/b.sass:
```
body
  background: #fff
```

Tests seem's to expect this syntax also, with full qualified path:
https://github.com/nanoc/nanoc/blob/f14166910059ab7150072ba89be3b8dd3e7654c4/nanoc-dart-sass/spec/nanoc/dart_sass/filter_spec.rb#L74

Which is strange, and prevent to import css project in a subfolder.

**Comment by denisdefreyne** [comment]
The Dart Sass filter indeed expects an absolute path. That’s by accident rather than on purpose, though. That can definitely be improved!

**Comment by doc75** [comment]
@denisdefreyne I would be happy to help on this as I do not want to change the whole bulma package I am using for years. Any hint on how to make it work with relative path (I am not so familiar with the Nanoc code) ?

**Comment by denisdefreyne** [comment]
I believe this should be fixed now -- can you confirm (before I do a release)? Stick this in your `Gemfile`:

```ruby
gem 'nanoc-dart-sass',
    git: 'https://github.com/nanoc/nanoc',
    glob: 'nanoc-dart-sass/*.gemspec'
```

… then run `bundle`, and now compiling (`bundle exec nanoc`) should make this work again.

**Comment by doc75** [comment]
@denisdefreyne I confirm that with the github version the compilation is working fine.
Thank you so much 🙏

**Comment by doc75** [comment]
@denisdefreyne Sorry to ask, do you know when you are planning to release a new nanoc-dart-sass gem version with this fix ?

**Comment by denisdefreyne** [comment]
@doc75 `nanoc-dart-sass` v1.0.1 is released now! Thanks for being so patient.

**Comment by doc75** [comment]
> Thanks for being so patient

No problem. You owe me nothing as this is open source software that you are developing on your spare time. So this normal to be patient and that you perform such action when you have time.
Keep up this great piece of software.
