### ISSUE TITLE
nanoc-live depends on defunct (and now-broken) version of rack-livereload; live reload is broken

### ISSUE THREAD

**Issue by pcantrell** [nanoc/nanoc#1647]
Rack 3.0 requires all headers to be lowercase. The `rack-livereload` gem is not yet compatible with Rack 3.0, incorrectly looks for `Content-Type` instead of `content-type`, and failing to find it, assumes that no documents are ever HTML and thus refuses to inject `livereload.js` into pages.

As a result, live reload in `nanoc live` is currently broken: Nanoc automatically rebuilds after changes, but one must manually refresh the browser to see the changes.

---

There is a [pull request on `rack-livereload`](https://github.com/jaredmdobson/rack-livereload/pull/13) to fix this. Alas, the fix **will not land** for `nanoc live` even after the PR is merged, because Nanoc is using an outdated source for the `rack-livereload` gem. The previously authoritative version of the gem has been deprecated:

https://github.com/johnbintz/rack-livereload

Per that page, the new authoritative version of the gem is:

https://github.com/jaredmdobson/rack-livereload

Nanoc may want to consider updating its dependency to point to that git repo.

---

In the meantime, anyone who wants to restore live reloading in Nanoc without waiting for all these fixes can add this to their Nanoc project’s `Gemfile`:

    gem "rack-livereload", git: "https://github.com/pcantrell/rack-livereload", branch: "lowercase-headers"

**Comment by denisdefreyne** [comment]
This is resolved with the new rack-livereload version (see https://github.com/denisdefreyne/adsf/issues/29)!
