### ISSUE TITLE
Replace unmaintained hamster gem with immutable-ruby

### ISSUE THREAD

**Issue by graaff** [nanoc/nanoc#1655]
The hamster gem appears to be no longer maintained, and has compatibility issues with ruby30 and newer versions. See for example https://github.com/hamstergem/hamster/issues/254 and https://github.com/hamstergem/hamster/pull/252

In the hamster issue a reference is made to a maintained fork: https://rubygems.org/gems/immutable-ruby. This should be a drop-in replacement with just the top level class name to change (if the documentation is to be believed :-)

I have not investigated whether the incompatibilities affect nanoc itself, it may be that nanoc only uses code paths that are unaffected by these incompatibilities, given that it only uses Vector and Set (and not OrderedSet). Still the missing ordered_set dependeny may lead to load errors later.

I'm also the Gentoo maintainer of nanoc and currently nanoc is stuck in Gentoo on ruby 3.0 only support because of this issue. We will be phasing out ruby30 before september (due to openssl 1.1.1 support stopping at that time) and it would be great if we can keep nanoc and support it also with ruby 3.1.

**Comment by denisdefreyne** [comment]
Thanks for reporting. I created #1656 which should take care of this.

**Comment by graaff** [comment]
Great! Thanks for the quick response.
