### ISSUE TITLE
YAML anchors/aliases broken

### ISSUE THREAD

**Issue by zor-el** [nanoc/nanoc#1676]
### Steps to reproduce

Using a YAML alias in `nanoc.yaml` or in a front matter will cause compilation to crash with an exception.

### Technical Analysis

Broken upstream with Psych 4 (https://bugs.ruby-lang.org/issues/17866) and reinforced in Nanoc with [PR 1583](https://github.com/nanoc/nanoc/pull/1583), commit `8882be18101315c7c65ee88dded328d3d44b30db`. 

#### Details

Psych 4 has introduced a [severe breaking change](https://bugs.ruby-lang.org/issues/17866) - YAML anchors and aliases are no longer recognized by default.

Nanoc enforces Psych >= 4 since [PR 1583](https://github.com/nanoc/nanoc/pull/1583), commit `8882be18101315c7c65ee88dded328d3d44b30db`. This prevents first aid workarounds such as `gem 'psych', '<4'` in the project Gemfile.

Net result: All `nanoc.yaml` configurations and content front matters that make use of anchors have since been broken. (Though apparently not that many people use YAML aliases given that I'm the fist to report this. :))

### Technical Solution

Psych 4 requires the option `aliases: true` to process anchors and aliases.

I've already **fixed this locally and will be submitting a PR shortly**.

**Comment by denisdefreyne** [comment]
This is fixed by #1677.
