### ISSUE TITLE
Mutex TypeError when Compiling Website

### ISSUE THREAD

**Issue by bobbens** [nanoc/nanoc#1687]
### Steps to reproduce

1. Compile
2. See `TypeError: no _dump_data is defined for class Thread::Mutex`

### Expected behavior

Successful compilation with no errors.

### Actual behavior

Seems to fail to compile with `TypeError: no _dump_data is defined for class Thread::Mutex`. However, it seems like it mainly manages to compile, only displays this message at the end. In particular, compiling with `-V` gives:

```
...
         filters │ count     min     .50     .90     .95     max     tot
─────────────────┼──────────────────────────────────────────────────────
 colorize_syntax │   117   0.00s   0.02s   0.09s   0.11s   0.12s   4.12s
             erb │   482   0.00s   0.00s   0.00s   0.00s   0.16s   0.70s
   html_compress │   181   0.00s   0.00s   0.00s   0.00s   0.00s   0.00s
        jupytext │    19   0.01s   0.02s   0.03s   0.03s   0.03s   0.39s
        kramdown │   117   0.00s   0.00s   0.00s   0.01s   0.08s   0.15s
relativize_paths │   299   0.00s   0.00s   0.00s   0.00s   0.00s   0.00s
            tidy │   117   0.00s   0.01s   0.02s   0.03s   0.08s   1.62s

Captain! We’ve been hit!

TypeError: no _dump_data is defined for class Thread::Mutex
...
```

Which seems to indicate it finished compilation.

### Details

This is a fairly old website I've been updating and working for something like 10 years now, and I haven't been able to isolate the error. It seems like it's trying to write a file, but it has a mutex and it causes it to fail. I'm pretty sure I've had it for a while, but mainly have been ignoring it.

### Crash log

https://gist.github.com/bobbens/b69d67c79be5503f54aea709935a35c9

**Comment by denisdefreyne** [comment]
Hey Edgar,

That’s an odd one! I’ve not seen this one before.

Can you check whether you have any uses of `Thread.new` or `Thread` or `Mutex.new` in your site’s code?

**Comment by bobbens** [comment]
I checked and am not using any as far as I can see. I am using `open3` in one of my filters which does' implicitly use a thread, but disabling that filter does not change anything.

**Comment by denisdefreyne** [comment]
Is the site source available somewhere, or would you be able to share it with me? That way, I can take a look at it myself -- it’s tricky to debug otherwise.

**Comment by bobbens** [comment]
I could try to make the source available, but it's a large and archaic website. Looking a bit more, I think the following filter could be at fault as 'shell' seems to spawn Threads that trigger the bug.

```ruby
class Jupytext < Nanoc::Filter

  requires 'shell'

  identifier :jupytext
  type       :text

  def run(contents, params={})
    sh = Shell.new
    sh.echo( contents ) | sh.system( 'jupytext', '-q', '--to', 'ipynb', '-o', '-' )
  end

end
```

I replaced it with a NOOP filter and it seems to work. What would be the best way to work around or handle this?

**Comment by denisdefreyne** [comment]
You could use the [`nanoc-external` filter](https://github.com/nanoc/nanoc/tree/main/nanoc-external).

Add it to the `nanoc` group in the Gemfile:

```ruby
group :nanoc do
  gem 'nanoc-external'
end
```

… and run `bundle install`.

Then you can use the filter like this:

```ruby
filter :external, exec: 'jupytext', options: %w(-q --to ipynb -o -)
```

Let me know how this works for you!

**Comment by bobbens** [comment]
That does seem to work, thanks! Would be nice to have that explained in the documentation.

**Comment by denisdefreyne** [comment]
Glad to have helped!

> Would be nice to have that explained in the documentation.

You’re right! I have been meaning to do that, but I have been slacking… at least it’s on the to-do list now.

**Comment by bobbens** [comment]
No worries. Great to fix this so fast (I've been seeing the issue for several years now).

As a sort of gratuitous side note, it would be nice if the nanoc-external also supported binary files so I could drop a lot of my custom filters too.

**Comment by denisdefreyne** [comment]
The `:external` filter (along with `:org_mode`, `:tilt`, and `:dart_sass`) are now documente don the Filters page: https://nanoc.app/doc/reference/filters/.

I’ve created https://github.com/nanoc/features/issues/69 to track binary file support in the `:external` filter.
