### ISSUE TITLE
External link checker flags "javascript:..." links as invalid

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1689]
### Steps to reproduce

1.  have a page with some inlined javascript, for example:
 `<a href="javascript:window.scrollTo({top:0,behavior: 'smooth'})">Back to top</a>`
2. compile and run `nanoc check elinks`

### Expected behavior

No error

### Actual behavior

nanoc check flags it as an invalid URI

**Comment by denisdefreyne** [comment]
@Fjan A fix for this is released in `nanoc-checking` v1.0.4!
