### ISSUE TITLE
nanoc-dart-sass does not install on FreeBSD 14

### ISSUE THREAD

**Issue by 0x1eef** [nanoc/nanoc#1710]
### Steps to reproduce

1. Add 'nanoc-dart-sass' to your Gemfile
2. Run 'bundle' install'

### Expected behavior

The bundle installs successfully

### Actual behavior

```
Fetching sass-embedded 1.77.8                                                       
Installing sass-embedded 1.77.8 with native extensions  
rake aborted!                                                                                                                                                           
NotImplementedError: dart-sass for x86_64-freebsd14 not available at https://github.com/sass/dart-sass/releases/tag/1.77.8 (NotImplementedError) 
```

### Details

The error makes sense; there's no prebuild available for FreeBSD (Or OpenBSD, or NetBSD).
Could we build from source instead ?

### Crash log

(When reporting a crash, create a [Gist](https://gist.github.com/) with the contents of the `crash.log` file, and link the Gist here.)

**Comment by denisdefreyne** [comment]
This would be an issue with [sass-embedded](https://github.com/sass-contrib/sass-embedded-host-ruby) rather than `nanoc-dart-sass`. A related issue: https://github.com/sass-contrib/sass-embedded-host-ruby/issues/221.

Can you check whether `gem install sass-embedded` works?

**Comment by 0x1eef** [comment]
> This would be an issue with [sass-embedded](https://github.com/sass-contrib/sass-embedded-host-ruby) rather than nanoc-dart-sass. A related issue: https://github.com/sass-contrib/sass-embedded-host-ruby/issues/221.

:+1: Let me know if we should move this issue.

> Can you check whether gem install sass-embedded works?

Same error. For what it's worth `npm install sass` works, and provides me with a `sass` executable. From what I understood it is a JavaScript implementation built from the Dart implementation. Could that maybe be an option, where we allow shelling out to node's sass ?

**Comment by denisdefreyne** [comment]
> > This would be an issue with [sass-embedded](https://github.com/sass-contrib/sass-embedded-host-ruby) rather than nanoc-dart-sass. A related issue: [sass-contrib/sass-embedded-host-ruby#221](https://github.com/sass-contrib/sass-embedded-host-ruby/issues/221).
> 
> 👍 Let me know if we should move this issue.

Yes please!

> > Can you check whether gem install sass-embedded works?
> 
> Same error. For what it's worth `npm install sass` works, and provides me with a `sass` executable. From what I understood it is a JavaScript implementation built from the Dart implementation. Could that maybe be an option, where we allow shelling out to node's sass ?

You can already use [nanoc-external](https://github.com/nanoc/nanoc/tree/main/nanoc-external) to pass content through an external command. But I’d advise against it, as it can be much slower.

**Comment by 0x1eef** [comment]
> You can already use [nanoc-external](https://github.com/nanoc/nanoc/tree/main/nanoc-external) to pass content through an external command. But I’d advise against it, as it can be much slower.

Nice ! Good to know about that. 

> > > This would be an issue with [sass-embedded](https://github.com/sass-contrib/sass-embedded-host-ruby) rather than nanoc-dart-sass. A related issue: [sass-contrib/sass-embedded-host-ruby#221](https://github.com/sass-contrib/sass-embedded-host-ruby/issues/221).
> > 
> > 
> > 👍 Let me know if we should move this issue.
> 
> Yes please!

Opened an issue here: https://github.com/sass-contrib/sass-embedded-host-ruby/issues/227
Gonna close this issue; thanks for the help!
