### ISSUE TITLE
Suggestion to remove Psych dependency

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#1712]
Please consider removing the dependency on Psych from the Gemfile.

In https://github.com/nanoc/nanoc/pull/1566/files a dependency on Psych was introduced to ensure that YAML#safe_load was available to nanoc. Now that the minimum ruby version is > 3.0 we can safely assume that's always the case and it should be safe to drop this dependency again.

*Motivation:* On Windows, installing the Psych gem is a rather painful, as it requires the dev toolkit and the libyaml library. We use nanoc in a mixed environment with contributors who may have different ruby versions installed, so locking to a specific version that's available to all of them without installation is cumbersome. The default YAML supplied with ruby should work fine nowadays. Simply removing this dependency would make our life a lot easier.

**Comment by denisdefreyne** [comment]
Good point! See #1713 for that change.

**Comment by Fjan** [comment]
Thanks!

**Comment by denisdefreyne** [comment]
This is released in Nanoc 4.13.1.
