### ISSUE TITLE
How to compile everything again after changing compass_config.rb?

### ISSUE THREAD

**Issue by moll** [nanoc/nanoc#322]
I see the `--force` option has been removed. How would one go about recompiling everything again? Nuking `./output`?

I was changing some settings in `compass_config.rb` (What a retarded config format they've made) and noticed nothing was getting recompiled.

**Comment by DaveEveritt** [comment]
Just used `rm -r tmp/*` to force a recompile after doing `git merge branchname` from a dev branch. Was thinking a `nanoc compile -force` might be welcome under circumstances where Nanoc doesn't know about the changes (i.e. run `rm -r tmp/*` before compiling)
