### ISSUE TITLE
Add error messages for kramdown

### ISSUE THREAD

**Issue by flaviut** [nanoc/nanoc#459]
The kramdown filter does not do anything with the messages that [kramdown outputs](http://kramdown.gettalong.org/rdoc/Kramdown/Document.html#attribute-i-warnings), which makes debugging invalid markdown more difficult.

I'm not sure about the best way to output them, just print them out once the document has been processed?

**Comment by ddfreyne** [comment]
Potential fix in #519.

**Comment by ddfreyne** [comment]
Fixed by #519. Fix will be in 3.7.5!
