### ISSUE TITLE
SystemStackError when updating from 3.6.9 to 3.6.10

### ISSUE THREAD

**Issue by ghost** [nanoc/nanoc#469]
After updating I get:

`/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/forwardable.rb:174: stack level too deep (SystemStackError)`

Removed the _tmp_ directory and the error changes to:

`/Library/Ruby/Gems/2.0.0/gems/nanoc-3.6.10/lib/nanoc/base/checksummer.rb:25: stack level too deep (SystemStackError)`

Same happens with 3.7.1.

Is there anything I can do to narrow down the issue?

**Comment by ddfreyne** [comment]
A fix for this, which allows items and layouts in attributes again, is in #518.

**Comment by ddfreyne** [comment]
Fixed by #518. This’ll go in 3.7.5.
