### ISSUE TITLE
s3/AWS deployment docs unclear

### ISSUE THREAD

**Issue by jm3** [nanoc/nanoc#479]
There's a [nanoc deploy](https://github.com/kamui/nanoc-deploy) gem that's evidently been merged into nanoc, and there's [activity](https://groups.google.com/d/topic/nanoc/HqHagXwd6z8/discussion) on the Google Group discussing integrations with s3cmd, but it's unclear what portions if any of these are usable today. The [deployment docs](http://nanoc.ws/docs/guides/deploying-nanoc-sites/), OTOH, do not mention fog or S3/AWS at all.

Using the yaml deployment parameters documented in [fog.rb](https://github.com/nanoc/nanoc/blob/7f2b9b173027ce6963ab4fcc575c086368a39a52/lib/nanoc/extra/deployers/fog.rb) 

```(yaml)
deploy:
  public:
    kind: fog
    bucket: blog.foo.com
```

and then running `nanoc deploy` errors with: `Error: The site has no deployment configuration for default.`

If I add `--target public`, instead I get this error: `ArgumentError:  is not a recognized storage provider`

Could I get some clarification on the right way is to deploy to s3, please?

**Comment by ddfreyne** [comment]
nanoc/nanoc.ws#74 is deployed!
