### ISSUE TITLE
Switch between different output directories (command line arg)

### ISSUE THREAD

**Issue by DivineDominion** [nanoc/nanoc#487]
My site takes about 25 seconds to compile. Because I disable Google Analytics, Disqus comments, and similar features in development mode, I clean the output directory before every deploy.

To leverage nanoc's smart compiler, I'd like to keep two output directories around: one for "production", the real site, and one for local previews. There's no command line switch to override the settings in the config YAML file it seems, or to load different config files on demand.

**Comment by DivineDominion** [comment]
I have used `NANOC_ENV` in the past and now switched to using `site.config[:env]`. My Google Analytics snippet is set up only in deployment (as it was before). Every HTML has to be re-compiled. I'd like to optimize this by using two different "staging" folders: in deployment mode, use `output-deploy/` and update everything that's necessary. When I switch to development, don't override the contents in there. When I'm done fiddling with something, re-compile.

My objective is to make compiling the site faster most of the time. Right now, if I don't clean the output dir before every deploy, all I gain is that images don't have to be resized again because they're the same in both environments.

**Comment by lifepillar** [comment]
@ddfreyne Is this advice still valid for Nanoc 4? If so, how does the syntax change? I've tried `site.config[:env]` and `@site.config[:env]`, but those give errors; `@config[:env]` doesn't, but I don't know if it serves the purpose (it should be equivalent to define `env` in `nanoc.yaml`, as far as I understand).

**Comment by ddfreyne** [comment]
@lifepillar Yes—`@config` in nanoc 3 and 4 is the same as `@site.config` in nanoc 3.

**Comment by ddfreyne** [comment]
Proper support for compilation environments now exists (see #859) as a pre-release feature; the next Nanoc 4 feature release will support it.
