### ISSUE TITLE
Ruby 1.8.7 Compatibility issues

### ISSUE THREAD

**Issue by Sudrien** [nanoc/nanoc#508]
My host still has 1.8.7 in their server stack, and I'm getting the following errors in my initial tests:

> gems/nanoc-3.7.4/lib/nanoc/data_sources/filesystem.rb:157: syntax error, unexpected '.', expecting kEND (SyntaxError)
> gems/nanoc-3.7.4/lib/nanoc/cli/commands/compile.rb:426: syntax error, unexpected '.', expecting kEND
> gems/nanoc-3.7.4/lib/nanoc/cli/commands/compile.rb:427: syntax error, unexpected '.', expecting kEND

Removing the newlines between function calls seems to fix the error messages - it seems that option as introduced in 1.9.x. I haven't got any farther than that at this point.

(Hey Dennis, long time no see)

EDIT: further issues. I could either branch, or documentation could be updated to say 1.8.x is no longer supported.

**Comment by ddfreyne** [comment]
It’s 1.8.6 instead of 1.8.7, in fact.

**Comment by mpapis** [comment]
someone with a ruby version switcher and having those older ruby versions could go through tags and run tests, just checked - RVM installs `1.8.6` on openSUSE - but my backlog grew to mach for last week, I do not think I will have time to test it in a week

**Comment by ddfreyne** [comment]
@mpapis I’ll take care of this!

**Comment by ddfreyne** [comment]
Ah, the problems begin:

```
% ruby --version
ruby 1.8.6 (2010-09-02 patchlevel 420) [i686-darwin14.0.0]
% gem install bundler
zsh: abort      gem install bundler
```

I’ll focus on 1.8.7 for the time being.

**Comment by ddfreyne** [comment]
I did some checking, and I found that nanoc 3.6.8 is the last version that can be used on Ruby 1.8.x.

Next steps would be to explicitly depend on 1.9.3+ for the next nanoc 3.7.x release, and perhaps remove the 1.8-isms from the source code (using Rubocop’s autocorrect).

**Comment by ddfreyne** [comment]
Here’s the PR that explicitly drops 1.8.x support: #517

**Comment by ddfreyne** [comment]
This issue is resolved now, I believe. Ruby 1.8.x support is dropped explicitly, and the latest nanoc version compatible with Ruby 1.8.x has been identified.

@Sudrien I’ll close this issue now. Sorry for making life a bit harder for you, but you’ll be happier with a more recent Ruby version anyway (and poke your hosting provider to upgrade Ruby!).

**Comment by Sudrien** [comment]
I'll manage. Thanks.
