### ISSUE TITLE
crash.log refers to crash log

### ISSUE THREAD

**Issue by auxbuss** [nanoc/nanoc#514]
I have a build failure. So, I look in `crash.log`. But the stack trace says:

    ... 39 more lines omitted. See full crash log for details.

But I'm already looking in the crash log.

How do I diagnose?

**Comment by ddfreyne** [comment]
Odd… should not happen! This is done by the `#write_stack_trace` method in `Nanoc::CLI::ErrorHandler`.

**Comment by ddfreyne** [comment]
@auxbuss Which version of nanoc are you using? This issue was fixed in 3.6.8 (see #397, #402).

**Comment by ddfreyne** [comment]
Please do re-open if the issue persists. Thanks!

**Comment by auxbuss** [comment]
That's possible. I dup'd a project (as a starter for new) and updated to ruby v2.2, so old gems versions may have been installed via bundler. Looking at original project, it uses nanoc v3.6.7. Having updated gems, issue is solved. Sorry for fuss.

**Comment by ddfreyne** [comment]
No prob. Thanks for reporting!
