### ISSUE TITLE
Broken link on http://nanoc.ws/docs/guides/creating-multilingual-sites/

### ISSUE THREAD

**Issue by sfermigier** [nanoc/nanoc#523]
The page <http://nanoc.ws/docs/guides/creating-multilingual-sites/> has a link to <http://projects.stoneship.org/hg/sites-moul/> as an example of a multilingual web site made with nanoc.

Unfortunately, this link is broken. Are there other examples elsewhere ? Or is the site archive available somewhere ?

**Comment by ddfreyne** [comment]
Uh oh, I think the source for that site isn’t available anymore. There’s no quick way to bring it back, but I’ll probably pop it onto GitHub soon.

**Comment by maciejczyzewski** [comment]
Look here: http://projects.stoneship.org/ (it's end, I think)
My example: https://github.com/maciejczyzewski/hyhyhy/tree/feature/doc (working)

**Comment by ddfreyne** [comment]
This is fixed by c83f120d9b8837a31d00cf691d0897fb27549514. I moved the site source to [ddfreyne/myst-online-site](https://github.com/ddfreyne/myst-online-site).

Thanks for reporting!
