### ISSUE TITLE
Default title

### ISSUE THREAD

**Issue by oddityoverseer13** [nanoc/nanoc#528]
It'd be great if there was a way to add a default title to documents. Unless I'm mistaken, right now the only way to add a title to an item is to add the yaml frontmatter to the file. I'd rather not do that, since I have many items, and most don't have frontmatter yet.

**Comment by bobthecow** [comment]
There is a way. Everything about this is customizable, because it's made out of Ruby :)

If you can give me a bit more context for where and what you're using the title for, I can give you a more specific answer, but likely you should do something like this in your templates:

```erb
<h1><%= @item[:title] || 'Default Title!' %>
```

**Comment by oddityoverseer13** [comment]
ah ok. I just created a ruby function that does this:

```
def title(item)
  item[:title] || item.identifier.chop.split('/').last.split('_').map{|w|w.capitalize}.join(' ')
end
```

I think that will suit my needs. Thanks!

**Comment by bobthecow** [comment]
:-1:

**Comment by oddityoverseer13** [comment]
@bobthecow why? :-1:

**Comment by bobthecow** [comment]
(see the edit)
