### ISSUE TITLE
RuntimeError: Found 2 content files

### ISSUE THREAD

**Issue by oddityoverseer13** [nanoc/nanoc#529]
I'm working on setting up a new site, and I got the following error:

`RuntimeError: Found 2 content files for content/docs/software/murphy/bin/push; expected 0 or 1`

Here's the whole crash.log, for reference: http://pastebin.com/bi331DM6

Here's the directory it's complaining about:
```
~/.../murphy/bin  $ ls
total 4.0K
lrwxrwxrwx 1 ... users    6 Feb  3 11:19 ace -> ace.rb*
-rwxr-xr-x 1 ... users    0 Feb  3 11:19 ace.rb*
lrwxrwxrwx 1 ... users    7 Feb  3 11:19 push -> push.rb*
-rwxr-xr-x 1 ... users 2.4K Feb  3 11:19 push.rb*
```
If I remove the symlinks, it stops complaining.

**Comment by bobthecow** [comment]
http://nanoc.ws/docs/troubleshooting/

**Comment by ddfreyne** [comment]
@oddityoverseer13 It might be wrong, but it seems like what you’re trying to do, is to ensure that the output has both _…/bin/push_ and _…/bin/push.rb_ files (same for _ace_). Is this correct?

In that case, I’d remove the symlinks and set up redirects on the server to redirect _push_ to _push.rb_ (same for _ace_).

**Comment by oddityoverseer13** [comment]
Well, I'm not quite sure what I want. I have an existing repository of documentation, in various formats, including markdown, binary, scripts, and txts. Mixed in, there are some links that point to scripts.

Since nanoc doesn't support files with multiple extensions, I'm thinking I might just create a rake task to remove these symlinks.


-------- Original Message --------

**Comment by ddfreyne** [comment]
That makes sense.

This issue appears to be resolved, so I’ll close it.
