### ISSUE TITLE
Package with Traveling Ruby

### ISSUE THREAD

**Issue by FooBarWidget** [nanoc/nanoc#530]
Not all of your users are Ruby programmers, and those who are not Ruby programmers may have trouble installing Nanoc. Maybe you can package Nanoc with [Traveling Ruby](http://phusion.github.io/traveling-ruby/) to solve this problem.

**Comment by ddfreyne** [comment]
This has been proposed before (see nanoc/nanoc.ws#72, and the [Trello card](https://trello.com/c/G5CKmS98/1-traveling-ruby-for-nanoc)). I’ll close this issue, but feel free to comment on the Trello card.
