### ISSUE TITLE
Cannot run test suite

### ISSUE THREAD

**Issue by TheLonelyGhost** [nanoc/nanoc#545]
Running on Ruby 2.2.0-p0 and, after running `bundle install`, several deprecation warnings related to minitest appeared followed by an error saying Minitest::Unit does not contain a method 'run'.

This occurs in `tasks/test.rake:15` after deprecation warnings saying "Minitest::Unit::TestCase is deprecated. Use Minitest::Test instead" and to require minitest/autorun instead.

It looks like this is a bigger issue with Minitest completely deprecating the api that's used. Perhaps we need to modify the Gemfile to specify a particular version of Minitest instead of leaving it so open?

**Comment by TheLonelyGhost** [comment]
Given the switch in the Gemfile based on ruby version, it seems like committing Gemfile.lock is out of the question. Perhaps someone with a working copy of it can help by specifying the latest working version of minitest?

**Comment by ddfreyne** [comment]
Interestingly, _Gemfile_ does have Minitest locked to 4.x:

```ruby
gem 'minitest', '~> 4.0'
```

It seems like Minitest 5.x takes precedence in your setup, which is odd. Are you running <kbd>rake</kbd> or <kbd>bundle exec rake</kbd>? (The latter is correct.)

**Comment by TheLonelyGhost** [comment]
Ah, that did it. Figured my rbenv setup would automatically handle the `bundle exec` prefix. :disappointed:

**Comment by ddfreyne** [comment]
That makes sense!

We’ll upgrade to Minitest 5.x at some point, but it’s not high prio. PRs welcome :)

**Comment by ddfreyne** [comment]
See #546.

**Comment by TheLonelyGhost** [comment]
:+1: Minitest 5.x. Was planning on opening a PR to learn more about Minitest (versus rspec, etc.) until I saw #546.

I just ended up creating a shell alias for rake to prefix it with `bundle exec`. Never use rake without bundler anyway so it works for me.
