### ISSUE TITLE
nanoc watch -> Undefined method `change` for #<Listen::Listener:0x007f8df4160c68>

### ISSUE THREAD

**Issue by raven-chen** [nanoc/nanoc#562]
here's the error stack

Crashlog created at 2015-05-09 11:00:36 +0800

===== MESSAGE:

NoMethodError: undefined method `change' for #<Listen::Listener:0x007f8df4160c68>

===== COMPILATION STACK:

  (empty)

===== STACK TRACE:

  0. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/commands/watch.rb:84:in `run'
  1. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/command_runner.rb:12:in `block in call'
  2. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/error_handler.rb:72:in `handle_while'
  3. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/error_handler.rb:24:in `handle_while'
  4. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/command_runner.rb:11:in `call'
  5. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  6. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  7. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  8. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  9. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/cri-2.7.0/lib/cri/command.rb:260:in `run'
  10. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli.rb:58:in `block in run'
  11. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/error_handler.rb:72:in `handle_while'
  12. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli/error_handler.rb:24:in `handle_while'
  13. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib/nanoc/cli.rb:56:in `run'
  14. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/bin/nanoc:25:in `<top (required)>'
  15. /Users/raven1/.rvm/gems/ruby-1.9.3-head/bin/nanoc:23:in `load'

===== VERSION INFORMATION:

nanoc 3.8.0 © 2007-2015 Denis Defreyne.
Running ruby 1.9.3 (2012-08-23) on x86_64-darwin12.0.0 with RubyGems 1.8.24.

===== SYSTEM INFORMATION:

Darwin Raven.local 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64

===== INSTALLED GEMS:

  RedCloth 4.2.3
  SQS 0.1.7
  Saikuro 1.1.0
  abstract 1.0.0
  actionmailer 3.0.20, 3.1.12, 4.0.1, 4.0.3
  actionpack 3.0.20, 3.1.12, 4.0.1, 4.0.3
  actionpack-action_caching 1.0.0
  activemodel 3.0.20, 3.1.12, 4.0.1, 4.0.3
  activerecord 3.0.20, 3.1.12, 4.0.1, 4.0.3
  activerecord-deprecated_finders 1.0.3
  activeresource 3.0.20, 3.1.12, 4.0.0
  activesupport 3.0.20, 3.1.12, 4.0.1, 4.0.3
  adsf 1.2.0
  airbrake 3.1.6, 3.1.11, 3.1.16
  amazon-ec2 0.9.17
  arel 2.0.10, 2.2.3, 4.0.2
  arrayfields 4.7.4
  atomic 1.1.14
  aws-s3 0.6.3
  aws-sdk 1.10.0, 1.18.0, 1.40.3
  barby 0.5.1
  bcrypt-ruby 2.1.4, 3.1.1
  bitly 0.6.1
  blankslate 2.1.2.4
  bourbon 3.1.6, 4.0.1
  breadcrumbs_on_rails 2.3.0
  builder 2.1.2, 3.0.4, 3.1.4
  bundler 1.1.5, 1.5.3
  capistrano 2.5.19, 2.8.0
  capistrano-cowboy 0.1.1, 0.1.2
  capistrano-ext 1.2.1
  capybara 1.1.4, 2.0.2, 2.4.4
  celluloid 0.16.0
  childprocess 0.3.9, 0.5.5
  chronic 0.2.3, 0.6.7, 0.9.1, 0.10.2
  chunky_png 1.2.9
  churn 0.0.12
  ci_reporter 1.6.5
  classifier-reborn 2.0.1
  climate_control 0.0.3
  cliver 0.3.2
  cocaine 0.5.1, 0.5.4
  coderay 0.9.8, 1.0.9, 1.1.0
  coffee-rails 3.1.1
  coffee-script 2.2.0
  coffee-script-source 1.6.2, 1.7.0
  colorator 0.1
  colored 1.2
  colorize 0.7.2
  connection_pool 1.0.0
  crack 0.1.8
  cri 2.7.0
  daemons 1.1.8
  dalli 1.1.2, 2.6.4, 2.7.2
  database_cleaner 0.9.1, 1.0.1, 1.2.0
  devise 1.1.5
  encryptor 1.1.3
  erubis 2.6.6, 2.7.0
  escape 0.0.4
  eventmachine 1.0.3, 1.0.4
  evernote-thrift 1.24.0
  evernote_oauth 0.2.1
  excon 0.6.6, 0.23.0, 0.26.0, 0.33.0
  execjs 1.4.0, 2.0.2
  ezcrypto 0.7.2
  factory_girl 2.3.2, 4.2.0, 4.4.0
  factory_girl_rails 1.4.0, 4.2.1, 4.4.1
  faraday 0.8.5, 0.8.8, 0.9.0
  fast-stemmer 1.0.2
  fastercsv 1.5.5
  fattr 2.2.0
  faye-websocket 0.4.7
  ffi 1.9.0, 1.9.6
  flay 1.4.1
  flickraw 0.9.6, 0.9.8
  flickraw-cached 20120701
  flog 2.5.0
  fog 0.5.3, 1.7.0, 1.12.1, 1.22.0
  fog-brightbox 0.0.2
  fog-core 1.22.0
  fog-json 1.0.0
  formatador 0.2.1, 0.2.4
  gdata-19 1.1.2
  geoip 1.1.1, 1.2.0
  geokit-rails3 0.1.5
  girl_friday 0.11.2
  grb 0.4.1
  hashie 2.0.5, 2.1.1
  highline 1.6.1, 1.6.2, 1.6.19, 1.6.21
  hike 1.2.2, 1.2.3
  hirb 0.3.5
  hitimes 1.2.2
  hoe 2.7.0
  hoptoad_notifier 2.4.11
  hpricot 0.8.6
  http_accept_language 2.0.0.pre
  http_parser.rb 0.5.3
  httparty 0.6.1
  httpauth 0.2.0
  i18n 0.5.0, 0.6.4, 0.6.9
  i18n-active_record 0.0.2
  jekyll 2.4.0
  jekyll-coffeescript 1.0.1
  jekyll-gist 1.1.0
  jekyll-paginate 1.0.0
  jekyll-sass-converter 1.2.1
  jekyll-watch 1.1.1
  jquery-rails 2.2.1, 3.1.0
  jquery-ui-rails 4.0.3, 4.1.2
  json 1.8.0, 1.8.1
  json_pure 1.7.7, 1.8.0, 1.8.1
  jwt 0.1.8, 0.1.13
  kaminari 0.14.1, 0.15.1
  kgio 2.8.0, 2.9.2
  koala 1.5.0
  kramdown 1.4.1
  less 1.2.21
  libv8 3.11.8.17, 3.16.14.3
  liquid 2.6.1
  listen 2.7.9
  mail 2.2.20, 2.4.4, 2.5.4
  mail_safe 0.3.1
  mailsafe 0.0.1
  main 4.4.0
  mercenary 0.3.4
  metaclass 0.0.1
  method_source 0.6.5, 0.8.1, 0.8.2
  mime-types 1.23, 1.25.1
  mini_portile 0.5.0, 0.6.0, 0.6.1
  minitest 4.7.5
  mixpanel 3.5.2
  mocha 0.13.2
  mock_redis 0.8.1
  mono_logger 1.1.0
  multi_json 1.7.4, 1.7.7, 1.8.4, 1.10.1
  multi_xml 0.5.5
  multipart-post 1.1.5, 1.2.0, 2.0.0
  mustache 0.99.4, 0.99.5
  mutter 0.5.3
  mysql2 0.2.6, 0.3.11, 0.3.13, 0.3.16
  nanoc 3.8.0
  net-scp 1.0.4, 1.1.1, 1.2.1
  net-sftp 2.0.5, 2.1.2
  net-ssh 2.1.4, 2.6.7, 2.9.1
  net-ssh-gateway 1.0.1, 1.1.0, 1.2.0
  newrelic_rpm 3.6.6.147
  nokogiri 1.5.9, 1.5.10, 1.6.0, 1.6.2.1, 1.6.5
  oauth 0.4.7
  oauth2 0.8.0, 0.8.1, 0.9.3
  omniauth 1.1.4, 1.2.1
  omniauth-facebook 1.5.0
  omniauth-oauth 1.0.1
  omniauth-oauth2 1.1.1, 1.1.2
  omniauth-twitter 0.0.17
  orm_adapter 0.4.0
  paperclip 3.4.2
  parallel 0.6.5
  parallel_tests 0.13.3
  parslet 1.5.0
  pdfkit 0.5.4
  poltergeist 1.0.3, 1.5.1
  polyglot 0.3.3, 0.3.4
  posix-spawn 0.3.9
  progressbar 0.9.0
  protected_attributes 1.0.5
  pry 0.9.5, 0.9.12.2, 0.9.12.4, 0.9.12.6
  pry-rails 0.3.2
  pygments.rb 0.6.0
  rack 1.2.8, 1.3.10, 1.5.2
  rack-cache 1.2
  rack-mount 0.6.14, 0.8.3
  rack-protection 1.5.0
  rack-ssl 1.3.3, 1.3.4
  rack-test 0.5.7, 0.6.2
  rails 3.0.20, 3.1.12, 4.0.1
  rails-observers 0.1.2
  rails_best_practices 0.5.0
  railties 3.0.20, 3.1.12, 4.0.1, 4.0.3
  raindrops 0.11.0, 0.13.0
  rake 10.0.4, 10.1.1, 10.3.0, 10.3.2
  rb-fsevent 0.9.4
  rb-inotify 0.9.5
  rcov 0.9.9
  rdoc 3.12.2
  redcarpet 3.1.2
  redis 3.0.4
  redis-actionpack 4.0.0
  redis-activesupport 4.0.0
  redis-namespace 1.3.1
  redis-rack 1.5.0
  redis-rails 4.0.0
  redis-store 1.1.4
  reek 1.2.8
  ref 1.0.5
  resque 1.24.1
  resque-retry 0.2.2
  resque-scheduler 1.9.9
  resque-status 0.4.1
  retryable 1.3.1
  ri_cal 0.8.8
  roodi 2.1.0
  rubinius-actor 0.0.2
  rubinius-core-api 0.0.1
  ruby-hmac 0.4.0
  ruby-prof 0.9.2
  ruby2ruby 1.2.5
  ruby_parser 2.0.5, 2.3.0
  rubyforge 2.0.4
  rubyzip 0.9.9, 1.1.6
  rufus-scheduler 2.0.16
  rvm 1.11.3.6
  safe_yaml 1.0.3
  sass 3.2.9, 3.2.12, 3.3.7
  sass-rails 3.1.7, 4.0.1
  selenium-webdriver 2.33.0, 2.35.1, 2.44.0
  sendgrid_toolkit 1.0.4
  sexp_processor 3.0.5, 3.0.6
  shoulda-context 1.1.6
  shoulda-matchers 2.1.0, 2.2.0, 2.6.1
  simple_oauth 0.2.0
  sinatra 1.4.3
  slim 2.0.0, 2.0.2
  slop 2.1.0, 3.4.5, 3.4.7, 3.5.0
  sprockets 2.0.4, 2.10.1, 2.11.0
  sprockets-rails 2.0.1
  temple 0.6.5, 0.6.7
  test_after_commit 0.2.0
  therubyracer 0.11.4, 0.12.1
  thin 1.3.1
  thor 0.14.6, 0.18.1
  thread_safe 0.1.3
  tilt 1.3.7, 1.4.1
  timecop 0.3.5, 0.6.3
  timers 4.0.1
  toml 0.1.1
  treetop 1.4.12, 1.4.14, 1.4.15
  twitter 4.5.0
  tzinfo 0.3.37, 0.3.38, 0.3.39
  uglifier 2.1.1, 2.3.3, 2.5.0
  unicorn 4.6.2, 4.8.3
  unicorn-worker-killer 0.4.2
  uuidtools 2.1.4
  vegas 0.1.11
  warden 1.0.6, 1.2.1, 1.2.3
  websocket 1.0.7, 1.2.1
  websocket-driver 0.5.1
  websocket-extensions 0.1.1
  whenever 0.7.3, 0.8.2, 0.9.2
  wicked_pdf 0.9.6
  wkhtmltopdf 0.1.2
  wkhtmltopdf-binary 0.9.9.1
  xml-simple 1.1.2, 1.1.3
  xpath 0.1.4, 2.0.0
  ya2yaml 0.31
  yajl-ruby 1.1.0, 1.2.0

===== ENVIRONMENT:

AUTOJUMP_DATA_DIR => "/Users/raven1/.local/share/autojump"
AUTOJUMP_HOME => "/Users/raven1"
Apple_PubSub_Socket_Render => "/private/tmp/com.apple.launchd.gh2NYS02jg/Render"
COLORFGBG => "7;0"
COMMAND_MODE => "unix2003"
DISPLAY => "/private/tmp/com.apple.launchd.6pSmnOiPJe/org.macosforge.xquartz:0"
EDITOR => "vim"
GEM_HOME => "/Users/raven1/.rvm/gems/ruby-1.9.3-head"
GEM_PATH => "/Users/raven1/.rvm/gems/ruby-1.9.3-head:/Users/raven1/.rvm/gems/ruby-1.9.3-head@global"
GOBIN => "/Users/raven1/go/bin"
GOPATH => "/Users/raven1/go"
HOME => "/Users/raven1"
IRBRC => "/Users/raven1/.rvm/rubies/ruby-1.9.3-head/.irbrc"
ITERM_PROFILE => "My Favior"
ITERM_SESSION_ID => "w0t0p0"
LC_ALL => "en_US.UTF-8"
LC_CTYPE => "en_US.UTF-8"
LOGNAME => "raven1"
MANPATH => "/opt/local/man:"
MY_RUBY_HOME => "/Users/raven1/.rvm/rubies/ruby-1.9.3-head"
OLDPWD => "/Users/raven1/gitpersonal/ryeboy"
PATH => "/Users/raven1/.rvm/gems/ruby-1.9.3-head/bin:/Users/raven1/.rvm/gems/ruby-1.9.3-head@global/bin:/Users/raven1/.rvm/rubies/ruby-1.9.3-head/bin:/Users/raven1/.rvm/bin:/Users/raven1/bin:/Users/raven1/go/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
PWD => "/Users/raven1/gitpersonal/ryeboy-site"
RUBY_VERSION => "ruby-1.9.3-head"
SECURITYSESSIONID => "186a5"
SHELL => "/bin/bash"
SHLVL => "1"
SSH_AUTH_SOCK => "/private/tmp/com.apple.launchd.BvS96wSETN/Listeners"
TERM => "xterm"
TERM_PROGRAM => "iTerm.app"
TMPDIR => "/var/folders/rs/8nfqpl9d3zb215gc23rds_4w0000gp/T/"
USER => "raven1"
XPC_FLAGS => "0x0"
XPC_SERVICE_NAME => "0"
_ => "/Users/raven1/.rvm/gems/ruby-1.9.3-head/bin/nanoc"
__CF_USER_TEXT_ENCODING => "0x1F6:0x0:0x0"
rvm_bin_path => "/Users/raven1/.rvm/bin"
rvm_env_string => "ruby-1.9.3-head"
rvm_path => "/Users/raven1/.rvm"
rvm_prefix => "/Users/raven1"
rvm_ruby_string => "ruby-1.9.3-head"
rvm_version => "1.20.9 (master)"

===== LOAD PATHS:

  0. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib
  1. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/colored-1.2/lib
  2. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/cri-2.7.0/lib
  3. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/nanoc-3.8.0/lib
  4. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/hitimes-1.2.2/lib
  5. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/timers-4.0.1/lib
  6. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/celluloid-0.16.0/lib
  7. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/rb-fsevent-0.9.4/lib
  8. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/rb-inotify-0.9.5/lib
  9. /Users/raven1/.rvm/gems/ruby-1.9.3-head/gems/listen-2.7.9/lib
  10. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1
  11. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby/1.9.1/x86_64-darwin12.0.0
  12. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/site_ruby
  13. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/vendor_ruby/1.9.1
  14. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/vendor_ruby/1.9.1/x86_64-darwin12.0.0
  15. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/vendor_ruby
  16. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1
  17. /Users/raven1/.rvm/rubies/ruby-1.9.3-head/lib/ruby/1.9.1/x86_64-darwin12.0.0

**Comment by raven-chen** [comment]
ah.. this is a deprecated method.. use guard-nanoc instead..

**Comment by ddfreyne** [comment]
This is likely due to a too new version of Listen. But yes, use _guard-nanoc_. :)

**Comment by bobthecow** [comment]
Let's make `nanoc watch` tell you to use `guard-nanoc` and then fail :P

**Comment by ddfreyne** [comment]
@bobthecow I’ll come up with a list of places where I’d like to emit deprecation notices. `watch` is one of them.
