### ISSUE TITLE
Deprecated components do not raise warnings

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#567]
Several deprecated components are implicitly deprecated and don’t loudly complain.

These commands are replaced by [guard-nanoc](https://github.com/guard/guard-nanoc):

* `nanoc watch`
* `nanoc autocompile`

These commands act outside of nanoc’s responsibility (nanoc does not manage content, merely reads it in and compiles it):

* `nanoc create-item` (no replacement)
* `nanoc create-layout` (no replacement)
* `nanoc sync` (no replacement)
* `nanoc update` (no replacement)

To do: find other deprecated components

CC @bobthecow (CC’ed because of #562)

**Comment by bobthecow** [comment]
LGTM.

Would it make sense to move `sync` and `update` type commands into a plugin, so that people could still have a way to manage data sources going forward?

**Comment by ddfreyne** [comment]
@bobthecow With the removal of `create-item` and `create-layout` commands along with matching `#create_item` and `#create_layout` commands, I don’t think it would be useful to have `sync` and `update` in commands; you’d have all the necessary code in your own `sync` implementation, and then the plugins would have almost no code at all. Does that make sense?

**Comment by ddfreyne** [comment]
`watch` and `autocompile` _are_ deprecated already (emit a warning).

As for `create-item` and `create-layout`, I’m not sure what kind of message we could emit (if anything).

**Comment by ddfreyne** [comment]
Adding deprecation warnings to everything that has changed/removed will be a lot of work, and the upgrade guide already covers all changes. I’m not sure I see a big benefit!

**Comment by bobthecow** [comment]
this is a major version, and a ton of things are changing. let's just document them and remove the code. no need to keep things around to let you know what, specifically, has changed.

**Comment by ddfreyne** [comment]
:+1:
