### ISSUE TITLE
View API lacks useful methods

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#570]
* `ConfigView`
  * `#fetch` (like `Hash#fetch`)
  * `#key?` (like `Hash#key?`)
* `ItemView`
  * `#fetch` (like `Hash#fetch`)
  * `#key?` (like `Hash#key?`)
  * `#parent` (like `Nanoc::Int::Item#parent`)
* `MutableItemView`
  * `#update_attributes` to bulk update attributes
* `MutableItemCollectionView`
  * `#concat` to bulk add items

Other related changes:

* `items.create` must return nil, so that it does not expose the internal entity.

**Comment by ddfreyne** [comment]
Idea: `AttributesView` that wraps attributes.

**Comment by cdlm** [comment]
Idea: a mixin that implements the rest of the `Hash` protocol, when you need objects that are like hashes.

**Comment by ddfreyne** [comment]
See fix in #572.
