### ISSUE TITLE
Default identifier/pattern style is legacy

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#587]
In nanoc 4, identifiers still use the legacy syntax (`/foo/` rather than `/foo.md`) by default. The pattern syntax is also legacy rather than glob (`/stuff/*/` rather than `/stuff/**/*`).

I suggest changing the defaults, and providing clear instructions on how to upgrade to nanoc 4 while retaining legacy identifier syntax and glob syntax.

**Comment by bobthecow** [comment]
:+1:

**Comment by ddfreyne** [comment]
Fixed by #592.
