### ISSUE TITLE
Auto-prune is not enabled by default

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#589]
It makes sense for nanoc to manage the contents of the _output/_ directory. In order to do so properly, it needs to have `auto_prune` turned on by default.

```yaml
prune:
  auto_prune: true
```

This will make sure that after every compilation, all stray files in the _output/_ directory are removed.

**Comment by ddfreyne** [comment]
Fixed by #590.

**Comment by bobthecow** [comment]
:+1:
