### ISSUE TITLE
Nanoc has a lowercase name

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#596]
Names start with a capital letter, so Nanoc’s name should too. The `nanoc` command is okay to keep lowercase, though.

* [x] Update nanoc executable
* [x] Update web site

**Comment by opensourcegrrrl** [comment]
Holy crap, I love this bug. :)

**Comment by gpakosz** [comment]
Where do you want to make changes?

**Comment by ddfreyne** [comment]
Any place that doesn’t explicitly refer to the command-line executable, I believe.

**Comment by opensourcegrrrl** [comment]
Also, the N in the nanoc icon will finally match! :)

**Comment by ddfreyne** [comment]
Updated site: nanoc/nanoc.ws#110

**Comment by ddfreyne** [comment]
This is now done. I also sent an announcement e-mail to the group.
