### ISSUE TITLE
`ItemView#parent` doesn't return nil if there is no parent

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#600]
`ItemView#parent` doesn't return nil if there is no parent. It returns an `ItemView` with `@item=nil `.

Reported by @cdlm.

**Comment by TheLonelyGhost** [comment]
Shouldn't this follow the null object pattern though? Returning `nil` isn't as telling as something like `EmptyItemView`.

**Comment by ddfreyne** [comment]
I don’t think it makes sense to use the null object pattern here. None of the methods (`#[]`, `#identifier`, `#compiled_content`, …) make sense for a `NullItemView` and they’d probably just raise an error, at which point having a `nil` instead of a `NullItemView` is more obvious and less work.
