### ISSUE TITLE
API does not accommodate for guard-nanoc

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#601]
nanoc 4’s public API is not accommodating for guard-nanoc; it needs to use internal APIs to work properly.

**Comment by cdlm** [comment]
See guard/guard-nanoc#20

**Comment by ddfreyne** [comment]
I’m OK with letting guard-nanoc use internal nanoc APIs. I’d rather not open up APIs publicly just for a single purpose; additionally, further down the road, Nanoc will hopefully gain better incremental processing which would obviate the need for this anyway.

Closing as a “won’t fix” issue.
