### ISSUE TITLE
Identifier#extension does not exist

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#610]
It is documented but not implemented.

For consistency, `ext` and `extension` could both be allowed (currently, `#with_ext` and `#without_ext` exist).

**Comment by ddfreyne** [comment]
CC @cdlm

**Comment by cdlm** [comment]
Hmm. I have this under pry:
```
[9] pry(#<Nanoc::Int::Context>)> item.identifier
=> <Nanoc::Identifier type=full "/notes/feed.feed">
[10] pry(#<Nanoc::Int::Context>)> item.identifier.ext
=> ".feed"
```
The period is there…
