### ISSUE TITLE
Incorrect `**` glob pattern description

### ISSUE THREAD

**Issue by remko** [nanoc/nanoc#639]
The 'Identifiers and patterns' documentation page says

> `**`
> Matches any file or directory name, and crosses directory boundaries. For example, /projects/**/*.md 
> matches both /projects/nanoc.md and /projects/nanoc/history.md.

However, this isn't true for the first case:

    2.2.1 :001 > File.fnmatch("/projects/**/*.md", "/projects/nanoc/history.md")
     => true 
    2.2.1 :002 > File.fnmatch("/projects/**/*.md", "/projects/nanoc.md")
     => false 

On the other hand, I may misunderstand how nanoc uses globs, because a `/**/` route rule matches `/`, which it doesn't using `fnmatch`, so that seems to be inconsistent with ruby globbing?

**Comment by ddfreyne** [comment]
nanoc uses both `FNM_PATHNAME` and `FNM_EXTGLOB` options:

```ruby
opts = File::FNM_PATHNAME | File::FNM_EXTGLOB

File.fnmatch("/projects/**/*.md", "/projects/nanoc/history.md", opts)
=> true

File.fnmatch("/projects/**/*.md", "/projects/nanoc.md", opts)
=> true
```

From the documentation of `FNM_PATHNAME`:

> If the `FNM_PATHNAME` flag is set in flags, then a slash character ( '/' ) in string shall be explicitly matched by a slash in pattern; it shall not be matched by either the asterisk or question-mark special characters, nor by a bracket expression. If the `FNM_PATHNAME` flag is not set, the slash character shall be treated as an ordinary character.

**Comment by ddfreyne** [comment]
Now I’m a little confused myself, to be honest. Will see what I can do about this from a documentation POV.

**Comment by ddfreyne** [comment]
The Git 1.8.2 release notes describe `**` as follows:

>  * The patterns in .gitignore and .gitattributes files can have `**/`,
   as a pattern that matches 0 or more levels of subdirectory.
   E.g. `"foo/**/bar"` matches `"bar"` in `"foo"` itself or in a
   subdirectory of `"foo"`.

This is far more clear.

**Comment by ddfreyne** [comment]
FYI: nanoc *does* use Ruby’s `fnmatch`, but I’d rather not explicitly mention that, because it is likely that at some point, the implementation will be swapped out in favour of something that is datasource-aware and thus more efficient.

**Comment by remko** [comment]
Hi Denis,

The Git description indeed more clearly explains why '**/*' is what you want in the example.

I sort of guessed that was how the globs were supposed to work from the examples from the documentation, but I hit a case where it didn't seem to have this behavior, but rather the default behavior of fnmatch without flags. Unfortunately, I don't remember where it was, but you can close this, and if I hit it again I'll reopen it with more explanation. Now I understand how it's supposed to work, so I know what to look for.

And I understand why you don't want to document that you use `fnmatch`.

**Comment by ddfreyne** [comment]
Makes sense!

I’ve created a PR for the web site to improve the explanation around the `**/` pattern: nanoc/nanoc.ws#100
