### ISSUE TITLE
nanoc lacks contributor code of conduct

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#648]
I believe that not having experienced any issues is not an excuse for not having a contributor code of conduct.

**Comment by bobthecow** [comment]
1. Don't be a jerk to anyone.
2. If you are a jerk, the rest of the community will ask you to stop.
3. If you don't stop, the rest of the community will ask you to leave.

**Comment by gpakosz** [comment]
:+1:

**Comment by ddfreyne** [comment]
@bobthecow I agree with what you said, but think “being a jerk” is too loosely defined.

I’m in favour of applying the [contributor covenant](http://contributor-covenant.org/version/1/1/0/) (also see its [GitHub repository](https://github.com/CoralineAda/contributor_covenant)).

**Comment by opensourcegrrrl** [comment]
@ddfreyne +1

**Comment by Ajedi32** [comment]
Sorry to butt in here, but I feel that "being a jerk" in that context is actually pretty well defined. It's defined by point 2: "If you are a jerk, the rest of the community will ask you to stop." E.g. The project's community collectively decides what "being a jerk" is, and will call you out on it if you are being one.

Longer CoC documents like the contributor covenant are just as subjective IMO, and don't add much beyond simple common sense. They provide obvious examples of "being a jerk", but leave everything else to the judgement of project collaborators. Unless you implement a full fledged procedure for defining in exact detail what "being a jerk" is, and exactly how to deal with it when it comes up, everything's all subjective anyway making a formal CoC document pretty pointless. Eh whatever, just my 2 cents. I'll be going now...

**Comment by ddfreyne** [comment]
@Ajedi32 My reason for having a code of conduct is in order to make everyone feel welcome to contribute. There’s a great deal of unconscious bias in the open-source community, and this is an effort to increase diversity.

**Comment by ddfreyne** [comment]
Done:

* nanoc/nanoc#667
* nanoc/nanoc.ws#111
