### ISSUE TITLE
nanoc 4.0.0b4 crashes, when executed with 'show-rules' command

### ISSUE THREAD

**Issue by andydrop** [nanoc/nanoc#649]
While it compiles my Site proberly,  nanoc 4.0.0b4 crashes, when i try to execute it with the 'show-rules' command.

Crashlog created at 2015-06-19 14:28:49 +0200

===== MESSAGE:

NoMethodError: undefined method `[]' for <Nanoc::Int::Item identifier="/Impressum/">:Nanoc::Int::Item

===== COMPILATION STACK:

  (empty)

===== STACK TRACE:

  0. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/commands/show-rules.rb:28:in `explain_item'
  1. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/commands/show-rules.rb:20:in `block in run'
  2. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/commands/show-rules.rb:20:in `run'
  3. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/command_runner.rb:12:in `block in call'
  4. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  5. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  6. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/command_runner.rb:11:in `call'
  7. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  8. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `call'
  9. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  10. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  11. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib/cri/command.rb:260:in `run'
  12. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli.rb:53:in `block in run'
  13. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  14. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  15. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib/nanoc/cli.rb:51:in `run'
  16. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/bin/nanoc:5:in `<top (required)>'
  17. /home/andy/.rbenv/versions/2.2.2/bin/nanoc:23:in `load'

===== VERSION INFORMATION:

nanoc 4.0.0b4 © 2007-2015 Denis Defreyne.
Running ruby 2.2.2 (2015-04-13) on i686-linux with RubyGems 2.4.5.

===== SYSTEM INFORMATION:

Linux datalore 3.2.0-3-486 #1 Thu Jun 28 08:08:24 UTC 2012 i686 GNU/Linux

===== INSTALLED GEMS:

  RedCloth 4.2.9
  adsf 1.2.0
  builder 3.2.2
  bundler 1.10.3
  colored 1.2
  cri 2.7.0
  hitimes 1.2.2
  json 1.8.3
  kramdown 1.7.0
  mini_portile 0.6.2
  nanoc 4.0.0b4
  nokogiri 1.6.6.2
  posix-spawn 0.3.11
  pygments.rb 0.6.3
  rack 1.6.1
  w3c_validators 1.2
  yajl-ruby 1.2.1

===== ENVIRONMENT:

BUNDLE_BIN_PATH => "/home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/bin/bundle"
BUNDLE_GEMFILE => "/home/andy/projects/remline/blog/Gemfile"
CDPATH => "/home/andy:/home/andy/projects:/home/andy/library"
COLORTERM => "gnome-terminal"
DBUS_SESSION_BUS_ADDRESS => "unix:abstract=/tmp/dbus-tDJZWk7h2d,guid=41858303bfc867306767145c5583bfd2"
DISPLAY => ":0"
EDITOR => "emacsclient"
GEM_HOME => "/home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0"
GEM_PATH => "/home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0:/home/andy/.gem/ruby/2.2.0"
GPG_AGENT_INFO => "/run/user/1000/keyring-pCHP8H/gpg:0:1"
HISTCONTROL => "ignoreboth"
HISTIGNORE => "&:ls:[bf]g:exit"
HOME => "/home/andy"
JDK_HOME => "/usr/lib/jvm/java-6-openjdk/"
LANG => "de_DE.utf8"
LANGUAGE => "de_DE.UTF-8"
LC_ALL => "de_DE.UTF-8"
LC_MEASUREMENT => "de_DE.UTF-8"
LC_MONETARY => "de_DE.UTF-8"
LC_NUMERIC => "de_DE.UTF-8"
LC_PAPER => "de_DE.UTF-8"
LC_TIME => "de_DE.UTF-8"
LESSCLOSE => "/usr/bin/lesspipe %s %s"
LESSOPEN => "| /usr/bin/lesspipe %s"
LESS_TERMCAP_mb => "\e[01;31m"
LESS_TERMCAP_md => "\e[01;38;5;74m"
LESS_TERMCAP_me => "\e[0m"
LESS_TERMCAP_se => "\e[0m"
LESS_TERMCAP_so => "\e[38;5;246m"
LESS_TERMCAP_ue => "\e[0m"
LESS_TERMCAP_us => "\e[04;38;5;146m"
LOGNAME => "andy"
LS_COLORS => "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lz=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:"
MANPATH => "/home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kramdown-1.7.0/man"
PATH => "/home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/bin:/home/andy/.rbenv/versions/2.2.2/bin:/usr/lib/rbenv/libexec:/home/andy/.rbenv/plugins/ruby-build/bin:/home/andy/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/andy/bin:/home/andy/.local/bin:/var/lib/gems/1.8/bin"
PWD => "/home/andy/projects/remline/blog"
PYTHONPATH => ":/home/andy/core/"
PYWIKIBOT_DIR => "/home/andy/.pywikibot/"
RBENV_DIR => "/home/andy/projects/remline/blog"
RBENV_HOOK_PATH => ":/home/andy/.rbenv/rbenv.d:/usr/local/etc/rbenv.d:/etc/rbenv.d:/usr/lib/rbenv/hooks"
RBENV_ROOT => "/home/andy/.rbenv"
RBENV_VERSION => "2.2.2"
RUBYLIB => "/home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib"
RUBYOPT => "-rbundler/setup"
SHELL => "/bin/bash"
SHLVL => "2"
SSH_AGENT_PID => "3904"
SSH_AUTH_SOCK => "/run/user/1000/keyring-pCHP8H/ssh"
SU_TO_ROOT_X => "gksudo"
TERM => "xterm-256color"
TZ => "Europe/Berlin"
USER => "andy"
VISUAL => "emacsclient"
VTE_VERSION => "3408"
WINDOWID => "35651590"
WINDOWPATH => "7"
XDG_RUNTIME_DIR => "/run/user/1000"
XDG_SEAT => "seat0"
XDG_SESSION_COOKIE => "d012284f9cacbc963a4b500900000a23-1434697682.443-1133336444"
XDG_SESSION_ID => "c1"
XDG_VTNR => "7"

===== GEMFILE.LOCK:

GEM
  remote: http://rubygems.org/
  specs:
    RedCloth (4.2.9)
    adsf (1.2.0)
      rack (>= 1.0.0)
    builder (3.2.2)
    colored (1.2)
    cri (2.7.0)
      colored (~> 1.2)
    hitimes (1.2.2)
    json (1.8.3)
    kramdown (1.7.0)
    mini_portile (0.6.2)
    nanoc (4.0.0b4)
      cri (~> 2.3)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    posix-spawn (0.3.11)
    pygments.rb (0.6.3)
      posix-spawn (~> 0.3.6)
      yajl-ruby (~> 1.2.0)
    rack (1.6.1)
    w3c_validators (1.2)
      json
      nokogiri
    yajl-ruby (1.2.1)

PLATFORMS
  ruby

DEPENDENCIES
  RedCloth
  adsf
  builder
  hitimes
  kramdown
  nanoc (~> 4.0.0b3)
  nokogiri
  pygments.rb
  w3c_validators

BUNDLED WITH
   1.10.3

===== LOAD PATHS:

  0. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/w3c_validators-1.2/lib
  1. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/pygments.rb-0.6.3/lib
  2. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/yajl-ruby-1.2.1
  3. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/yajl-ruby-1.2.1/lib
  4. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/posix-spawn-0.3.11
  5. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/posix-spawn-0.3.11/lib
  6. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/nokogiri-1.6.6.2
  7. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.6.2/lib
  8. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/nanoc-4.0.0b4/lib
  9. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/mini_portile-0.6.2/lib
  10. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/kramdown-1.7.0/lib
  11. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/json-1.8.3
  12. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/json-1.8.3/lib
  13. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/hitimes-1.2.2
  14. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/hitimes-1.2.2/lib
  15. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/cri-2.7.0/lib
  16. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/colored-1.2/lib
  17. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/builder-3.2.2/lib
  18. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/adsf-1.2.0/lib
  19. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/rack-1.6.1/lib
  20. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/extensions/x86-linux/2.2.0-static/RedCloth-4.2.9
  21. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/RedCloth-4.2.9/lib
  22. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/RedCloth-4.2.9/lib/case_sensitive_require
  23. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/RedCloth-4.2.9/ext
  24. /home/andy/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/bundler-1.10.3/lib
  25. /home/andy/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0
  26. /home/andy/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/i686-linux
  27. /home/andy/.rbenv/versions/2.2.2/lib/ruby/site_ruby
  28. /home/andy/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0
  29. /home/andy/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/i686-linux
  30. /home/andy/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby
  31. /home/andy/.rbenv/versions/2.2.2/lib/ruby/2.2.0
  32. /home/andy/.rbenv/versions/2.2.2/lib/ruby/2.2.0/i686-linux

**Comment by ddfreyne** [comment]
Can you try GitHub master? This issue has been fixed in master (#633) so that should work for you now.

**Comment by ddfreyne** [comment]
@andydrop I’ll close this now, but please do let me know if you still experience issues.

**Comment by andydrop** [comment]
Yes, it is fixed. Means it doesn't crash anymore
