### ISSUE TITLE
Exclude URLs from external links check

### ISSUE THREAD

**Issue by ihmels** [nanoc/nanoc#678]
You should be able to exclude URLs from external links check. This could be done in `@config[:check][:external_links][:exclude]`.

When I’m running the external links check, the test fails, because a checked link returned a `502` HTTP status code (https://pgp.mit.edu/pks/lookup). Maybe they are only accepting specific user agents to prevent spammers from collecting email addresses.

**Comment by ddfreyne** [comment]
Makes sense!

You can create a PR (on master) if you want to.

**Comment by ddfreyne** [comment]
Fixed by #686.
