### ISSUE TITLE
Invalid byte sequence in US-ASCII when running through upstart

### ISSUE THREAD

**Issue by radar** [nanoc/nanoc#688]
I've got a semi-convoluted setup here:

1. An upstart job that runs a Sinatra application which accepts webhooks from GitHub. When it gets the webhook, it runs a `./deploy` file in another directory.
2. That `./deploy` file is simply:

```
git pull --rebase origin master
bundle install --path vendor/bundle
bundle exec nanoc compile
```

When this webhook runs, it errors like this:

```
/root/mysite.com/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/stream_cleaners/utf8.rb:10:in `gsub': invalid byte sequence in US-ASCII (ArgumentError)
  from /root/mysite.com/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/stream_cleaners/utf8.rb:10:in `clean'
  from /root/mysite.com/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/cleaning_stream.rb:143:in `block in _nanoc_clean'
  from /root/mysite.com/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/cleaning_stream.rb:143:in `each'
  from /root/mysite.com/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/cleaning_stream.rb:143:in `reduce'
  from /root/mysite.com/vendor/bundle/ruby/2.2.0/gems/nanoc-4.0.0rc2/lib/nanoc/cli/cleaning_stream.rb:143:in `_nanoc_clean'
```

When I run `bundle exec nanoc compile` from the `mysite.com` directory directly, it does not produce this error.

Is this a Nanoc bug or something in my code?

**Comment by radar** [comment]
Figured it out!

I needed to put this in my upstart job:

```
env LANG=en_US.UTF-8
```

Then it uses the `UTF-8` encoding instead of `US-ASCII`.

**Comment by ddfreyne** [comment]
Glad to see it resolved!

There’s also the [character encoding troubleshooting page](http://v4.nanoc.ws/doc/troubleshooting/#character-encoding-issues), but it does not mention this particular error. I’ll update it.
