### ISSUE TITLE
Updating filters for Nanoc 4

### ISSUE THREAD

**Issue by lifepillar** [nanoc/nanoc#689]
I would like to update a couple of filters to work with Nanoc 4. I've started by updating the gemspec of `nanoc-external`, but that does not seem to be enough, because I get this error when compiling a site:

    Nanoc::Int::Errors::UnknownFilter: The requested filter, “external”, does not exist.

From the documentation, it seems that filters would work the same in Nanoc 3 as in Nanoc 4. Am I missing something?

**Comment by lifepillar** [comment]
Oh my, I was sure I had required the plugin, but that was not the case!

**Comment by ddfreyne** [comment]
OK, glad it’s solved!
