### ISSUE TITLE
#with_ext is confusing

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#697]
This method is confusing, since it deletes a single extension (leaving others) and adding the given one.

It also does not allow chaining; for instance, `foo.without_exts.with_ext('html')` will not work.

Perhaps `#with_ext` should be removed completely, possibly replaced by `#replace_ext` and `#replace_exts`.

See also: #664, #679, #696.

**Comment by barraq** [comment]
:+1:

**Comment by ddfreyne** [comment]
Fixed in #700 by removing `#with_ext`.

I figured `#replace_ext` and/or `#replace_exts` is not very useful considering `#+` already exists. If it turns out to be a nice-to-have, it might arrive in 4.1.
