### ISSUE TITLE
Proxy support for checks

### ISSUE THREAD

**Issue by majkinetor** [nanoc/nanoc#698]
w3c validators and external links do not work behind the proxy. 

For w3c validators this did it for me:

```
results = ::W3CValidators::MarkupValidator.new(:proxy_host=>'1.1.1.1', :proxy_port => 8080).validate_file(filename)
```

Similar is true for the `request_url_once` for elinks check.

I guess simple usage of environment variable `http_proxy` and friends instead of no proxy would suffice.

**Comment by ddfreyne** [comment]
Makes sense! If you feel inclined, a PR (on `master`) would definitely be welcome.

**Comment by bishop335** [comment]
Enhance this

**Comment by ddfreyne** [comment]
Moved to nanoc/features#1.
