### ISSUE TITLE
Dynamically creating rules and compile directives

### ISSUE THREAD

**Issue by majkinetor** [nanoc/nanoc#703]
I would like to generate Rules DSL from the helper module. I have custom blog helper and i would like it to generate RSS feeds automatically so I don't have to specify any compile and routing rules in the Rules file as long as specific metadata is present. That is, I want the hole thing to be pluggable by simple import and some metadata, without extensive manual setup.

For more details, please see my question on stackoverflow:

http://stackoverflow.com/questions/32645687/dynamically-creating-rules-and-compile-directives

**Comment by ddfreyne** [comment]
I’m inclined to say that this is not the purpose of the Rules file, and I believe a better approach would be to add attributes to the site configuration, items and layouts, and parameterise rules that way, so that there’s no need to generate rules programmatically.

An additional challenge with generating rules is that it gets rid of a central place where all rules are stored. This can make it difficult and confusing to find out which rules actually exist, and which rules are used for a given item/layout.

Having said that, there is `#include_rules`, which, given a file name, will include the rules in the file with that name.

**Comment by majkinetor** [comment]
> I believe a better approach would be to add attributes to the site configuration, items and layouts, and parameterise rules that way, so that there’s no need to generate rules programmatically.

This is precisely what I try to avoid. I would like to have zero configuration for some modules. I just want to plug it in (enable it in preprocessing section) and it should setup details itself. Typical case is tags module - I want to have 1 page that shows all tags and one blog for each individual tag and 1 feed for each tag blog. If I include such module it should create all those items and configure them for the articles that have `tags` metadata, no questions asked. With module arguments or site config I could customize the module if I need to. Without it, I need to setup all that manually (which means stuff in content, stuff in nanoc.yaml and stuff in Rules on multiple places, stuff in default.rb) which makes removal of tags non-trivial especially after some time has passed. Furthermore, multiply this with the number of nanoc sites where you need this functionality. If I need to maintain this module over multiple sites its even more problematic.

> An additional challenge with generating rules is that it gets rid of a central place where all rules are stored.

We have  `nanoc show-rules` for that ? Also, it seems easy to change `#include_rules` to remember all included files and list their content with new command (or just those generated by modules).

I think that existence of mechanisms such as this would make nanoc far more usable as without understanding the internals much you would be able to follow plugin/module convention to get the desired effect and only tweak internal details if those conventions are not good in your scenario. Black box functionalities would also make easier for everybody to experiment.

**Comment by ddfreyne** [comment]
Moved to nanoc/features#2.
