### ISSUE TITLE
Add `each` to ConfigView?

### ISSUE THREAD

**Issue by gjtorikian** [nanoc/nanoc#705]
I was toying around with jumping from Nanoc3 to 4 and found that one of my preprocessors has stopped working. It depends on iterating over the existing config keys to set some other information up.

Would there be any interest in a PR that adds `each` to `ConfigView`?

**Comment by ddfreyne** [comment]
Absolutely!

By the way, I started working on a [branch to upgrade the GitHub developer site to Nanoc 4](https://github.com/ddfreyne/developer.github.com/pull/1), but haven’t touched in a couple of months. (Opened as a PR on my own repo, rather than GitHub’s, so I can keep track of progress without creating noise.)

**Comment by gjtorikian** [comment]
Ah, that's awesome!

By the way, it's look like I'll probably be porting our main <help.github.com> site to Nanoc, too. It's suffering under abysmal performance with Jekyll—about a minute build times locally and nearly ten minutes (!) in production. The problem is that I've monkey-patched the code (via plugins) so much to do what we need it to do that it's getting complicated to wrap my head around it. I just couldn't find a way to hook into key parts of the compilation. I only yesterday realized that porting over to Nanoc 4 makes much more sense. I love it! I can hook into the file system before files are read (which we need), I can do some preprocessing, and I can apply the same filters to the same bits of content.

That'll bring our two major sites (`{help|developer}.github.com` under the same engine. Hopefully I'll toss over more PRs to Nanoc4 if I find more issues.

**Comment by ddfreyne** [comment]
Sounds exciting! :)

Nanoc 4.0 is in a feature freeze, but I think the wait until 4.1 won’t be that long. The 4.0 release will show all sorts of missing nice-to-have things that’ll end up in 4.1 quickly enough!

On one hand, Nanoc 4 (when using the new identifiers and new globs) will be slower than 3.x, but it also offers much more potential for optimisations, which will end up in later minor releases.
