### ISSUE TITLE
rdiscount filter - mismatch with documentation

### ISSUE THREAD

**Issue by mitchelltd** [nanoc/nanoc#714]
Both in the [filter code](https://github.com/nanoc/nanoc/blob/release-4.0.x/lib/nanoc/filters/rdiscount.rb) and in the [documentation](http://v4.nanoc.ws/doc/reference/filters/) it is said that you are to use `:symbol`, when the code requires the use of `:extensions`

**Comment by ddfreyne** [comment]
Thanks for spotting! This’ll be for the Nanoc 4.0.1 release (4.0.0 is ready to be released and I’d rather not touch it anymore).

**Comment by ddfreyne** [comment]
Fix in #722 — give me your :+1:!

**Comment by ddfreyne** [comment]
Fix will be in 4.0.1.

**Comment by mitchelltd** [comment]
That's great thanks ! I presume that the [documentation](http://nanoc.ws/doc/reference/filters/) will be changed at the same time ?

**Comment by ddfreyne** [comment]
Yes—the documentation is generated from the source code annotations, but that does mean that the documentation will stay the same until 4.0.1 is released.
