### ISSUE TITLE
auto_prune deletes dynamically created items with non ASCII characters identifier

### ISSUE THREAD

**Issue by opatry** [nanoc/nanoc#715]
Hi,

I'm facing a strange issue (Mac OS X El Capitan if it matters), as described in the issue title:

The `auto_prune` behaves strangely when handling dynamically created items with identifiers containing non ASCII characters.

starting from scratch to be sure:

```sh
$ nanoc create-site foo
$ cd foo
```

Edit the `Rules` to add a `preprocess` block to create items dynamically:

```ruby
preprocess do
  @items << Nanoc::Item.new("", {:title => "ç", :type => "note", :created_at => '2013-03-02 12:00:00 +0200', :extension => 'html'}, "/tag/ç/")
  @items << Nanoc::Item.new("", {:title => "a", :type => "note", :created_at => '2013-03-02 12:00:00 +0200', :extension => 'html'}, "/tag/a/")
end
```

```sh
$ nanoc compile
```

When `auto_prune` is set to `true`, the output is the following:

```
Compiling site…
      create  [0.02s]  output/index.html
      create  [0.00s]  output/stylesheet.css
      create  [0.00s]  output/tag/ç/index.html
      create  [0.00s]  output/tag/a/index.html
      delete  output/tag/ç/index.html
      delete  output/tag/ç
```

So, the item whose identifier contains a "special" character (ie. non ASCII) is deleted, the "normal" one is kept.

`<update>`Can't reproduce on Linux`</update>`

**Comment by gpakosz** [comment]
Works for me:

    $ env | grep LC_
    LC_ALL=en_US.UTF-8
    LC_CTYPE=en_US.UTF-8

And

    $ nanoc --version
    nanoc 3.8.0 © 2007-2015 Denis Defreyne.
    Running ruby 2.2.3 (2015-08-18) on x86_64-darwin14 with RubyGems 2.4.5.1.

    $ ruby --version
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]

**Comment by opatry** [comment]
Mac OS X 10.11.1

```sh
$ env |grep LC_              
LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8
```

```sh
nanoc --version
nanoc 3.8.0 © 2007-2015 Denis Defreyne.
Running ruby 2.0.0 (2015-04-13) on universal.x86_64-darwin15 with RubyGems 2.0.14.
```

```sh
$  ruby --version
ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
```

**Comment by opatry** [comment]
Also reproduced on 
Mac OS X 10.10.5 with case insensitive file system

```sh
$ env |grep LC_
LC_CTYPE=fr_FR.UTF-8
```
```sh
$ nanoc --version
nanoc 3.8.0 © 2007-2015 Denis Defreyne.
Running ruby 2.0.0 (2014-05-08) on universal.x86_64-darwin14 with RubyGems 2.0.14.
```
```sh
$ ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by opatry** [comment]
Hi, an update regarding conditions to reproduce.

It seems related to the ruby version since @gpakosz uses ruby 2.2.x and I'm using ruby 2.0.x.
It tried with same environment but ruby 2.2 installed using homebrew.

```sh
$ brew install ruby
$ export PATH=/usr/local/Cellar/ruby/2.2.3/bin:$PATH
$ gem install nanoc
```
```sh
$ nanoc --version
nanoc 3.8.0 © 2007-2015 Denis Defreyne.
Running ruby 2.2.3 (2015-08-18) on x86_64-darwin15 with RubyGems 2.4.5.1.
```
```sh
$ ruby --version
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
```

**Comment by ddfreyne** [comment]
Given that:

* Ruby 2.0 only receives security updates and will go end-of-life next year ([source](https://www.ruby-lang.org/en/news/2015/08/18/ruby-2-0-0-p647-released/))
* Nanoc 4 (to be released Soon™) will require Ruby 2.2 and up
* This is not a bug in Nanoc but in Ruby

I’d say that this issue can be closed with the proposed fix being “upgrade to the latest version of Ruby”.

Thanks for the thorough investigation!

**Comment by opatry** [comment]
Ok with that, maybe we can add a note on that in the [Troubleshooting](http://nanoc.ws/docs/troubleshooting/) page of the documentation? (I can open a PR if you agree with that)

**Comment by ddfreyne** [comment]
I’m about to release Nanoc 4.0 (this weekend, hopefully!) so I don’t think there’s much of a point to add this to the troubleshooting page.
