### ISSUE TITLE
Where should I commit a DateTime Bug in attribute_to_time

### ISSUE THREAD

**Issue by rosetree** [nanoc/nanoc#716]
Recently I investigated a small bug in `attribute_to_time` of the blogging helper. I’m able to fix the code, but I’m not sure, which branch I have to use. As far as I can see the bug is in master, release-3.8.x and release-4.0.x. To fix it, I would add a single line and update a bit of documentation.

So my question is: Which branch should I use to fix the bug? Or is this a new feature, as it will allow the use of DateTime in `attribute_to_time`? I’m sorry if this is a stupid question.

**Comment by ddfreyne** [comment]
I suggest `master`, since it’s an enhancement and so it should end up in the next minor Nanoc release, which will be Nanoc 4.1.

Nanoc 4.0 is in feature-freeze and pretty much ready to be released, which will happen very soon. A Nanoc 4.1 alpha will be out around the same time of the 4.0 release.

**Comment by rosetree** [comment]
Thanks for your answer. According to your recommendation, I created the pull request https://github.com/nanoc/nanoc/pull/717

**Comment by ddfreyne** [comment]
Will close in favour of #717.

(There’s also the [Contributing code](http://v4.nanoc.ws/contributing/#contributing-code) section on the web site, which has a focus on Nanoc 4 and doesn’t mention the `release-3.8.x` branch.)
