### ISSUE TITLE
"No compilation rules were found for the “/” item" after upgrading

### ISSUE THREAD

**Issue by cakebaker** [nanoc/nanoc#725]
I'm not sure whether this is a bug or a feature, though to me it looks like a bug.

In nanoc 3.x I had the following rule in my <code>Rules</code> file:
```    
compile '*' do
  # do something
end
```
For nanoc 4.0, I set <code>string_pattern_type: glob</code> in the config file and changed the rule to: 
```
compile '/*/' do  # I also tried '/**/*/', but I get the same result
  # do something
end
```
Now, when compiling my project, I get the following error:
```
Nanoc::Int::Errors::NoMatchingCompilationRuleFound: No compilation rules were found for the “/” item.

0. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/compilation/compiler.rb:210:in `block in build_reps'
1. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/compilation/compiler.rb:207:in `build_reps'
2. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/compilation/compiler.rb:123:in `load'
3. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/compilation/compiler.rb:86:in `run'
4. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/base/source_data/site.rb:23:in `compile'
5. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/cli/commands/compile.rb:376:in `block in run'
6. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/cli/commands/compile.rb:418:in `run_listeners_while'
7. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/cli/commands/compile.rb:375:in `run'
8. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/cli/command_runner.rb:12:in `block in call'
9. /home/dho/.gem/ruby/2.2.0/gems/nanoc-4.0.0/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
```
As a workaround, I had to add an additional rule (and the corresponding route) to make the compilation work:
```
compile '/*/' do
  # do something
end

compile '/' do
end
```

**Comment by ddfreyne** [comment]
I *think* that there’s no other way than to specify `'/'` separately, but I’ll have to check. This is definitely something that needs to be described in the upgrade guide though.

(I think I missed this because I always have the root page specified differently.)

**Comment by ddfreyne** [comment]
I created nanoc/nanoc.ws#133 to cover the case of upgrading a rule that matches /.

I’ll close this issue now, but feel free to shout if I missed anything.
