### ISSUE TITLE
static files - site no longer builds after v4 upgrade; upgrade guide has some gaps

### ISSUE THREAD

**Issue by jm3** [nanoc/nanoc#734]
versions: *nanoc 4.0.0 / ruby-2.2.3 / bundle 1.10.6*
*my [Rules](https://gist.github.com/jm3/9ada958f8dc186687c39) and my [nanoc.yml](https://gist.github.com/jm3/9ada958f8dc186687c39) posted as gist*

Hi friends, I did my best to follow the v4 [upgrade guide](http://nanoc.ws/doc/nanoc-4-upgrade-guide/), but migrating a site with any static assets didn't go so smoothly for me.

1) When following the instructions in the section **Upgrading from the static data source**, am I supposed to just add those before or after the existing `compile` + `route` blocks?

Currently Nanoc says: ```Nanoc::Int::Errors::NoMatchingCompilationRuleFound: No compilation rules were found for the “/” item.```

2) the [troubleshooting guide](http://nanoc.ws/doc/troubleshooting/) tells me that the following error is an artifact of "full identifiers / glob patterns", and sends me back to the 9-page upgrade guide: ```RuntimeError: Found 4 content files for static/vendor/fonts/glyphicons/glyphicons-halflings-regular; expected 0 or 1```

But like any web developer whose site has static assets, I just want the assets **copied**, period. I don't want to define custom rules / globs / magic sprinkles for every file / extension. My site only has a single page and some static assets. Is there maybe a stock nanoc.yml file I can use for this? I understand that the v4 changes were designed to make things easier, but the migration guide doesn't seem ready for prime-time with sites that use static assets (which is, in my experience, 99%+ of websites).

**Comment by ddfreyne** [comment]
Hi!

The instructions for upgrading from the static data source require globs and full identifiers to be enabled. Nanoc 4’s full identifiers include the file extension, and so the static data source becomes obsolete when using globs and full identifiers.

The configuration and Rules file look okay apart from that!

**Comment by jm3** [comment]
so I should just delete the static data source? I'm not clear what's being recommended here.

**Comment by ddfreyne** [comment]
You’ll need to enable globs and identifiers with extensions. The [extended upgrade guide](http://nanoc.ws/doc/nanoc-4-upgrade-guide/#extended-upgrade-guide) contains instructions on how to do so.

**Comment by ddfreyne** [comment]
I believe this issue is resolved and so I’ll close it. Please do follow up if you believe that it is not.
