### ISSUE TITLE
`link_to_unless_current` attributes

### ISSUE THREAD

**Issue by lvuotto** [nanoc/nanoc#737]
I think the current implementation of `link_to_unless_current` lacks the attributes flexibility of `link_to`. Giving `link_to_unless_current` the same behaviour is fairly trivial.

Has there been any discussion about this? I have no problem in submitting a pull request if the project wants to.

**Comment by ddfreyne** [comment]
It makes sense for `#link_to_unless_current` to have the same behavior of `#link_to`. A PR for this would definitely be welcome!

**Comment by lvuotto** [comment]
Alright, working on it. Should I take in consideration keeping the old behavoiur of adding an "active" class or should it be completely overriden by attributes hash?

**Comment by ddfreyne** [comment]
Yes—retain the old behavior.

**Comment by lvuotto** [comment]
And what should be the behaviour when someone set the `class` attribute? 
Append `active` always? Only if it's not present? Discard what attribute?

On 28/11/15 13:06, Denis Defreyne wrote:
> Yes—retain the old behavior.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nanoc/nanoc/issues/737#issuecomment-160314793>.
>



-- lv.

**Comment by ddfreyne** [comment]
I think it makes sense to have both `class` and a new `active_class` attribute. The final HTML class would be the combination of both, if active, or just `class`.

**Comment by ddfreyne** [comment]
I’ll close this issue now; see #743 for details.
