### ISSUE TITLE
Preprocessor not executed before check/deploy

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#763]
dowker88 wrote:

> I have a project that creates multiple sites from a single code base. Basically, the layouts, CSS, JS, etc. are all common. The Markdown files (and a few small extras) are unique to each site. I use ENV variables to specify which site is being compiled, etc.

> In Nanoc 4, the deployer behavior has changed. In version 3, I could change the source path programmatically before rsync was executed. I can't seem to find a way to do the same in Nanoc 4. The output directory is customized in the preprocessor using config[:output_dir] but it no longer runs in the new deployer. Any ideas?

It appears that the preprocessor is not executed before check/deploy.

**Comment by wlkk** [comment]
Auto

**Comment by ddfreyne** [comment]
Fixed in #784.
