### ISSUE TITLE
@layout[:foo] raises NoMethodError

### ISSUE THREAD

**Issue by hilohiro** [nanoc/nanoc#771]
Hi, I tried to upgrade my project of nanoc 3.8 to 4.0.2, and got trouble with layout attributes.
In layout `/default.html`, `@layout.attributes[:foo]` works but `@layout[:foo]` raises `NoMethodError`. That code had no trouble with nanoc 3.8.

```
NoMethodError: undefined method `[]' for <Nanoc::Int::Layout identifier="/default.html">:Nanoc::Int:
:Layout
```

I guess @layout should be `Nanoc::LayoutView` but it really is `Nano::Int::Layout`.

Thanks in advance.
HIRONO.

```
D:\home\Documents\sample\official_site\2016>nanoc --version
Nanoc 4.0.2 (c) 2007-2015 Denis Defreyne.
Running jruby 2.2.2 (2015-11-12) on java with RubyGems 2.4.8.
```

**Comment by ddfreyne** [comment]
That seems like a bug!

Is your site’s source available somewhere for me to take a look?

**Comment by ddfreyne** [comment]
Managed to reproduce the issue. Fix coming up!

**Comment by ddfreyne** [comment]
#773 has a fix.

**Comment by ddfreyne** [comment]
Fix will be in 4.1.0!

**Comment by ddfreyne** [comment]
Could you give a try by letting Nanoc use the `release-4.1.x` branch from GitHub?

**Comment by hilohiro** [comment]
Thank you a lot!
I'll try with both branch later.

**Comment by hilohiro** [comment]
I checked out the latest `release-4.1.x` branch and it worked fine!
Thank you for your quick help.
