### ISSUE TITLE
While laying out an item, @item_rep is available, but @rep is not

### ISSUE THREAD

**Issue by gjtorikian** [nanoc/nanoc#777]
I usually use `@rep` in my Rules and such because it's shorter. But I just discovered that in layouts, `@rep` is `nil`. (`@item_rep` is available to use, though.)

**Comment by ddfreyne** [comment]
Ack, weird. Is this in 4.1 alpha something?

**Comment by gjtorikian** [comment]
Yeah I'm using `'4.1.0rc1'`.

**Comment by ddfreyne** [comment]
Hmm, I can’t reproduce the issue here (using either the tag `4.1.0rc1` or the `release-4.1.x` branch). Do you have a small example where it fails?

**Comment by ddfreyne** [comment]
@gjtorikian Poke. Can you confirm that this is still an issue?

**Comment by gjtorikian** [comment]
I can't reproduce this, which means I did something silly?
