### ISSUE TITLE
Stale check no longer works on generated items

### ISSUE THREAD

**Issue by remko** [nanoc/nanoc#786]
The `stale` check seems to be failing on items I create in the `Rules` file since I upgraded to nanoc 4.1.

I removed my output dir, did a clean build, and immediately after `nanoc check stale` fails:

    output/blog/page10/index.html:
        [ ERROR ] stale - file without matching item

This item is created with `@items.create` in the preprocess step.

**Comment by ddfreyne** [comment]
Can you try reproducing the problem with the `release-4.1.x` branch? I believe this issue is fixed and will be part of 4.1.1.

**Comment by remko** [comment]
The check seems fixed in the `release-4.1.x` branch. However, my site no longer compiles with that one. Not sure if it's my fault, or whether I should file another issue:

    Nanoc::Int::ItemRepRouter::IdenticalRoutesError: The item representations <Nanoc::Int::ItemRep name="default" binary=false raw_path="output/index.html" item.identifier="/index.html"> and <Nanoc::Int::ItemRep name="default" binary=false raw_path="" item.identifier="/index.html"> are both routed to /index.html.

**Comment by remko** [comment]
It seems the preprocess block is run twice, and I add that item in the preprocess block.

**Comment by ddfreyne** [comment]
I created #787 for this!
