### ISSUE TITLE
Preprocessor run twice when compiling

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#787]
In the `release-4.1.x` branch currently, the preprocessor is run twice when compiling. See #786.

**Comment by ddfreyne** [comment]
CC @remko

**Comment by ddfreyne** [comment]
Potential fix in #788.

**Comment by ddfreyne** [comment]
@remko Can you verify that the `release-4.1.x` now works properly for you?

**Comment by remko** [comment]
Yup, works now, thanks!
