### ISSUE TITLE
tag pages

### ISSUE THREAD

**Issue by floreal** [nanoc/nanoc#803]
Hi, I wrote this: https://gist.github.com/floreal/58826423f29efbaa2a67
But that I need to call `create_tag_pages` in preporcess section of Rules file. I'd like to turn it into a datasorce so that this call wouldn't be needed anymore and then I could make a pull request.

The problem I need other datasources before using that one so that reading tags will be easy using `@items` variable.

Do you think there is a way to do it ?
Would it need a big change in nanoc codebase ?
Or should I provide a pull request with this snippet as is even if end user will need to use preprocess section in his Rules file ?

Cheers

**Comment by ddfreyne** [comment]
Data sources aren’t designed to generate items (or layouts) based on what other data sources provide.

The recommended approach is to do what you are already doing, which is using the preprocessor to generate these pages.
