### ISSUE TITLE
"nanoc check" exception when some issues do not have a subject

### ISSUE THREAD

**Issue by Fjan** [nanoc/nanoc#804]
If a "nanoc check" results in multiple issues, and some issues have a subject and others do not, then the command will fail with a "ArgumentError: comparison of String with nil failed".

The ```add_issue(desc,subject:nil)```method takes and optional subject that will become ```nil``` if not filled out. When the subject is used on some issues but not others an exception can occur because the command runner tries to sort the issues by subject and will fail when trying to compare nil with a string.

A simple solution would be to make issues without a subject default to an empty string, or to a string such as "(no subject)" [here](https://github.com/nanoc/nanoc/blob/master/lib/nanoc/extra/checking/check.rb#L46). Alternatively, the sort method in the runner can be changed to account for this.

**Comment by ddfreyne** [comment]
Fixed in #811.
