### ISSUE TITLE
Preprocessor not executed before check

### ISSUE THREAD

**Issue by francois2metz** [nanoc/nanoc#841]
The fix in #784 have been removed in #788.

Dynamic items created in the preprocess block are marked as stale.

To fix it, I added `site.compiler.action_provider.preprocess(site)` in `lib/nanoc/cli/commands/check.rb`.

I can open a pull request if you think it is the right fix.

**Comment by ddfreyne** [comment]
You’re right—#788 should’ve kept the preprocessing step before checks.

Your suggestion seems correct. I’ll implement the fix and add a regression spec.

**Comment by ddfreyne** [comment]
Fix in #842.

**Comment by francois2metz** [comment]
Thanks!

**Comment by ddfreyne** [comment]
This is released in 4.1.5 now.
