### ISSUE TITLE
ArgumentError: Content filename is not absolute

### ISSUE THREAD

**Issue by partha88** [nanoc/nanoc#854]
Crashlog created at 2016-05-12 11:56:49 +0530

===== MESSAGE:

ArgumentError: Content filename is not absolute

===== COMPILATION STACK:

  (empty)

===== STACK TRACE:

  0. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/entities/content.rb:19:in `initialize'
  1. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/entities/content.rb:44:in `new'
  2. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/entities/content.rb:44:in `create'
  3. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/data_source.rb:143:in `new_item'
  4. lib/data_sources/static.rb:28:in `block in items'
  5. lib/data_sources/static.rb:18:in `map'
  6. lib/data_sources/static.rb:18:in `items'
  7. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:31:in `block (2 levels) in site_from_config'
  8. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:30:in `each'
  9. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:30:in `block in site_from_config'
  10. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:55:in `with_data_sources'
  11. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:29:in `site_from_config'
  12. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:12:in `new_from_cwd'
  13. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/command_runner.rb:24:in `site'
  14. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:156:in `site'
  15. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:161:in `compiler'
  16. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:166:in `stack'
  17. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:270:in `write_compilation_stack'
  18. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:116:in `write_compact_error'
  19. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:92:in `print_error'
  20. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:71:in `rescue in handle_while'
  21. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:45:in `handle_while'
  22. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  23. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/command_runner.rb:11:in `call'
  24. /var/lib/gems/2.3.0/gems/cri-2.7.0/lib/cri/command_dsl.rb:233:in `block in runner'
  25. /var/lib/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  26. /var/lib/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  27. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/commands/nanoc.rb:37:in `block in define'
  28. /var/lib/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:294:in `run_this'
  29. /var/lib/gems/2.3.0/gems/cri-2.7.0/lib/cri/command.rb:247:in `run'
  30. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli.rb:53:in `block in run'
  31. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:64:in `handle_while'
  32. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:22:in `handle_while'
  33. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli.rb:51:in `run'
  34. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/bin/nanoc:9:in `<top (required)>'
  35. /usr/local/bin/nanoc:22:in `load'
  36. /usr/local/bin/nanoc:22:in `<top (required)>'
  37. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `load'
  38. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:63:in `kernel_load'
  39. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli/exec.rb:24:in `run'
  40. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli.rb:304:in `exec'
  41. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  42. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  43. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
  44. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
  45. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/cli.rb:11:in `start'
  46. /var/lib/gems/2.3.0/gems/bundler-1.12.3/exe/bundle:27:in `block in <top (required)>'
  47. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib/bundler/friendly_errors.rb:98:in `with_friendly_errors'
  48. /var/lib/gems/2.3.0/gems/bundler-1.12.3/exe/bundle:19:in `<top (required)>'
  49. /usr/local/bin/bundle:22:in `load'

===== VERSION INFORMATION:

Nanoc 4.1.6 © 2007-2016 Denis Defreyne.
Running ruby 2.3.1 (2016-04-26) on x86_64-linux-gnu with RubyGems 2.6.4.

===== SYSTEM INFORMATION:

Linux 01hw772321 3.16.0-70-generic #90~14.04.1-Ubuntu SMP Wed Apr 6 22:56:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

===== INSTALLED GEMS:

  adsf 1.2.0
  builder 3.2.2
  bundler 1.12.3
  coderay 1.1.1
  colored 1.2
  commonjs 0.2.7
  cri 2.7.0
  daemons 1.2.3
  diff-lcs 1.2.5
  eventmachine 1.2.0.1
  ffi 1.9.10
  formatador 0.2.5
  guard 2.13.0
  guard-nanoc 1.0.2
  json 1.8.2
  less 2.6.0
  libv8 3.16.14.15
  listen 3.1.3
  lumberjack 1.0.10
  method_source 0.8.2
  mime-types 2.3
  mini_portile 0.5.3
  nanoc 4.1.6
  nenv 0.3.0
  nokogiri 1.6.1
  notiffany 0.0.8
  pry 0.10.3
  rack 1.6.4
  rb-fsevent 0.9.7
  rb-inotify 0.9.7
  ref 2.0.0
  rspec 2.14.1
  rspec-core 2.14.8
  rspec-expectations 2.14.5
  rspec-mocks 2.14.6
  ruby_dep 1.3.1
  sass 3.4.18
  shellany 0.0.1
  slop 3.6.0
  therubyracer 0.12.1
  thin 1.6.2
  thor 0.19.1

===== LOAD PATHS:

  0. /var/lib/gems/2.3.0/gems/bundler-1.12.3/lib
  1. /var/lib/gems/2.3.0/gems/thin-1.6.2/lib
  2. /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/thin-1.6.2
  3. /var/lib/gems/2.3.0/gems/therubyracer-0.12.1/lib
  4. /var/lib/gems/2.3.0/gems/therubyracer-0.12.1/ext
  5. /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/therubyracer-0.12.1
  6. /var/lib/gems/2.3.0/gems/sass-3.4.18/lib
  7. /var/lib/gems/2.3.0/gems/rspec-2.14.1/lib
  8. /var/lib/gems/2.3.0/gems/rspec-mocks-2.14.6/lib
  9. /var/lib/gems/2.3.0/gems/rspec-expectations-2.14.5/lib
  10. /var/lib/gems/2.3.0/gems/rspec-core-2.14.8/lib
  11. /var/lib/gems/2.3.0/gems/ref-2.0.0/lib
  12. /var/lib/gems/2.3.0/gems/nokogiri-1.6.1/lib
  13. /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.6.1
  14. /var/lib/gems/2.3.0/gems/mini_portile-0.5.3/lib
  15. /var/lib/gems/2.3.0/gems/mime-types-2.3/lib
  16. /var/lib/gems/2.3.0/gems/libv8-3.16.14.15-x86_64-linux/lib
  17. /var/lib/gems/2.3.0/gems/libv8-3.16.14.15-x86_64-linux/ext
  18. /var/lib/gems/2.3.0/gems/less-2.6.0/lib
  19. /var/lib/gems/2.3.0/gems/json-1.8.2/lib
  20. /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/json-1.8.2
  21. /var/lib/gems/2.3.0/gems/guard-nanoc-1.0.2/lib
  22. /var/lib/gems/2.3.0/gems/nanoc-4.1.6/lib
  23. /var/lib/gems/2.3.0/gems/guard-2.13.0/lib
  24. /var/lib/gems/2.3.0/gems/thor-0.19.1/lib
  25. /var/lib/gems/2.3.0/gems/pry-0.10.3/lib
  26. /var/lib/gems/2.3.0/gems/slop-3.6.0/lib
  27. /var/lib/gems/2.3.0/gems/method_source-0.8.2/lib
  28. /var/lib/gems/2.3.0/gems/notiffany-0.0.8/lib
  29. /var/lib/gems/2.3.0/gems/shellany-0.0.1/lib
  30. /var/lib/gems/2.3.0/gems/nenv-0.3.0/lib
  31. /var/lib/gems/2.3.0/gems/lumberjack-1.0.10/lib
  32. /var/lib/gems/2.3.0/gems/listen-3.1.3/lib
  33. /var/lib/gems/2.3.0/gems/ruby_dep-1.3.1/lib
  34. /var/lib/gems/2.3.0/gems/rb-inotify-0.9.7/lib
  35. /var/lib/gems/2.3.0/gems/rb-fsevent-0.9.7/lib
  36. /var/lib/gems/2.3.0/gems/formatador-0.2.5/lib
  37. /var/lib/gems/2.3.0/gems/ffi-1.9.10/lib
  38. /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/ffi-1.9.10
  39. /var/lib/gems/2.3.0/gems/eventmachine-1.2.0.1/lib
  40. /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/eventmachine-1.2.0.1
  41. /var/lib/gems/2.3.0/gems/diff-lcs-1.2.5/lib
  42. /var/lib/gems/2.3.0/gems/daemons-1.2.3/lib
  43. /var/lib/gems/2.3.0/gems/cri-2.7.0/lib
  44. /var/lib/gems/2.3.0/gems/commonjs-0.2.7/lib
  45. /var/lib/gems/2.3.0/gems/colored-1.2/lib
  46. /var/lib/gems/2.3.0/gems/coderay-1.1.1/lib
  47. /var/lib/gems/2.3.0/gems/builder-3.2.2/lib
  48. /var/lib/gems/2.3.0/gems/adsf-1.2.0/lib
  49. /var/lib/gems/2.3.0/gems/rack-1.6.4/lib
  50. /usr/local/lib/site_ruby/2.3.0
  51. /usr/local/lib/x86_64-linux-gnu/site_ruby
  52. /usr/local/lib/site_ruby
  53. /usr/lib/ruby/vendor_ruby/2.3.0
  54. /usr/lib/x86_64-linux-gnu/ruby/vendor_ruby/2.3.0
  55. /usr/lib/ruby/vendor_ruby
  56. /usr/lib/ruby/2.3.0
  57. /usr/lib/x86_64-linux-gnu/ruby/2.3.0

**Comment by ddfreyne** [comment]
Hi,

Nanoc 4 no longer supports the static data source. The purpose of the static data source was to work around the fact that Nanoc 3.x’s filesystem data source did not contain the file extension, making it difficult to include external assets such as fonts, which typically share a filename but differ only in file extension.

The Nanoc 4 upgrade guide describes [how to upgrade from the static data source](http://nanoc.ws/doc/nanoc-4-upgrade-guide/#upgrading-from-the-static-data-source). Note that this does require upgrading the site to identifiers with extensions and glob patterns.

Do let me know if you run into any snags!
