### ISSUE TITLE
NameError: uninitialized constant Nanoc3

### ISSUE THREAD

**Issue by leecalcote** [nanoc/nanoc#860]
$ bundle -v
Bundler version 1.12.5

$ nanoc --version
A Gemfile was detected, but Bundler is not loaded. This is probably not what you want. To run Nanoc with Bundler, use `bundle exec nanoc`.
Nanoc 4.1.6 © 2007-2016 Denis Defreyne.
Running ruby 2.3.1 (2016-04-26) on x86_64-darwin15 with RubyGems 2.5.1.

> $ bundle exec nanoc
> Loading site… 
> Captain! We’ve been hit!
> 
> Message:
> 
> NameError: uninitialized constant Nanoc3
> Did you mean?  Nano
> 
> Compilation stack:
> 
> 
> Captain! We’ve been hit!
> 
> Message:
> 
> NameError: uninitialized constant Nanoc3
> Did you mean?  Nano
> 
> Compilation stack:
> 
>   (empty)
> 
> Stack trace:
> 
>   0. lib/default.rb:8:in `<main>'
>   1. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/entities/code_snippet.rb:31:in `eval'
>   2. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/entities/code_snippet.rb:31:in `load'
>   3. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:24:in `each'
>   4. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:24:in `site_from_config'
>   5. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/base/repos/site_loader.rb:12:in `new_from_cwd'
>   6. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/command_runner.rb:24:in `site'
>   7. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:156:in `site'
>   8. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:161:in `compiler'
>   9. /usr/local/lib/ruby/gems/2.3.0/gems/nanoc-4.1.6/lib/nanoc/cli/error_handler.rb:166:in `stack'
>   ... 34 more lines omitted. See full crash log for details.

**Comment by ddfreyne** [comment]
Nanoc 4 no longer has the `Nanoc3` constant; it has been replaced with `Nanoc`. See the [Nanoc 4 upgrade guide](http://nanoc.ws/doc/nanoc-4-upgrade-guide/) for details.

If you want to stick with Nanoc 3 for the time being, ensure that your Gemfile specifies Nanoc 3. For example:

```ruby
gem 'nanoc', '~> 3.8'
```

… though [upgrading to Nanoc 4](http://nanoc.ws/doc/nanoc-4-upgrade-guide/) is recommended.
