### ISSUE TITLE
Make it possible to create named reps with Nanoc::Spec::HelperContext

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#868]
Thanks for supplying a spec helper with 4.2.0!

Currently one can only create the `:default` rep with `#create_rep`. Please add an optional parameter to name the rep something different like so:

```
item = ctx.create_item('item', {}, '/index.html')
ctx.create_rep(item, '/some/path.html', :foobar)
# or
ctx.create_rep(item, '/some/path.html', rep: :foobar)
```

**Comment by ddfreyne** [comment]
Makes sense! (Patches welcome :))
