### ISSUE TITLE
An item's @context.items is nil inside RuleContext

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#869]
I'm in the middle of converting a nanoc 3.x project to nanoc 4.2.0.

I've made a lot of extensions to the 3.x `Item` class that need a major overhaul. As an example, I'm trying to recreate a `slug` method that looked like this:

```ruby
class Nanoc::Item
  def slug
     # code doesn't matter, what's important is that we need access to other items
     site.items.last[:title]
  end
end
```

In the 4.x project I'm currently at code that looks like this:

```ruby
class Slug
  def initialize(item, context)
    @item = item
    @context = context
  end

  def to_str
     # code doesn't matter, what's important is that we need access to other items
     @context.items['/foo.html'][:title]
  end
end

module Nanoc
  class ItemWithoutRepsView
    def slug
      Slug.new(self, @context)
    end
  end
end
```

I need access to `@item.slug` both in `Rules` and while rendering items.

Rules:
```ruby
route '/**/*' do
  @item.slug
end
```

Item.erb:
```erb
<%= @item.slug %>
```

`@item.@context.items` is what is ultimatively accessed by the `Slug` class.

* During rule evaluation `@item.@context.items` are `nil`.
* During item compilation `@item.@context.items` is a `Nanoc::Int::IdentifiableCollection`.

I wonder if this is intended. From an extension developer perspective, it would be great if `@item.@context.items` was not `nil` because then I don't need two sets of parameters.

I've prepared a little [test project](https://github.com/agross/nanoc4-issue864) that prints stuff like this:
```
*** RULES ***
self is: Nanoc::RuleDSL::RuleContext
@item.@context is Nanoc::ViewContext
@item.@context.items is NilClass

Trying Slug.new(@item, self)
Nanoc::ItemWithoutRepsView
Nanoc::RuleDSL::RuleContext
==> success

Trying Slug.new(@item, @context)
Nanoc::ItemWithoutRepsView
NilClass
==> failed undefined method `items' for nil:NilClass

Trying @item.slug
Nanoc::ItemWithoutRepsView
"slug"
Nanoc::ItemWithoutRepsView
Nanoc::ViewContext
==> failed Slug.new: context.items are nil!
--------------------------------------------------------------------------------
*** ITEM ***
self is: Nanoc::Int::Context
@item.@context is Nanoc::ViewContext
@item.@context.items is Nanoc::Int::IdentifiableCollection

Trying Slug.new(@item, self)
Nanoc::ItemWithRepsView
Nanoc::Int::Context
==> success

Trying Slug.new(@item, @context)
Nanoc::ItemWithRepsView
NilClass
==> failed undefined method `items' for nil:NilClass

Trying @item.slug
Nanoc::ItemWithRepsView
"slug"
Nanoc::ItemWithRepsView
Nanoc::ViewContext
==> success
```

**Comment by ddfreyne** [comment]
The `ViewContext` class is private, and thus not intended to be used externally. I can’t guarantee that it’ll remain there, or have the same API, or even the same behavior.

Would it be possible to use a helper method for calculating the slug? `slug_for(item)` could still access both `@item` and `@items`, if needed.

**Comment by agross** [comment]
Hi!

Yes, I know that there are a lot of APIs marked private. Unfortunately, I need/want to use them. You may ask why ;-), but I personally don't like `xxx_for(@item)` methods that much because they clutter the global scope and rather like those helpers to be on the objects in question (`@item.xxx`). As I said, personal preference and I'm willing to take a hit when you decide to remove private APIs.

**Comment by ddfreyne** [comment]
This is not a bug I’m willing to fix, given that it’s part of a private API. The `nil` is intended, as that part of the code does not require the context to be fully filled in.
