### ISSUE TITLE
Post-processing reports items modified that were not created

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#882]
# Use case

I need to run some code only if an item has been recompiled. For compilations where the item hasn't been created or updated, the code should be skipped.

I would like to use postprocessing to check whether the item in question has been modified as described [here](http://nanoc.ws/doc/rules/#post-processing) and run the code conditionally.

# Issue

Nanoc reports the item always as modified, even if the compiler didn't create or update the file.

# Reproduction

* `nanoc create-site test`
* Edit `Rules` to include:

  ```ruby
  postprocess do
    p @items.select(&:modified)
            .map(&:identifier)
            .map(&:to_s)
  end
  ```
* `nanoc compile -V` yields:

  ```
  Loading site... done
  Compiling site...
        create  [0.02s]  output/index.html
        create  [0.01s]  output/stylesheet.css
  ["/index.html", "/stylesheet.css"]
  
  Site compiled in 0.07s.
  ```

* Second run of `nanoc compile -V` without modifiying anything on disk:
  ```
  Loading site... done
  Compiling site...
  ["/index.html", "/stylesheet.css"]
  
  Site compiled in 0.04s.
  ```

**Comment by ddfreyne** [comment]
The `#modified` method on an item returns the item representations that were modified, rather than a boolean. Could it be the case that `#modified` returns an empty list (which is treated as true-y value)?

**Comment by agross** [comment]
Alright, I understand now what `modified` does. It's not a bug, it's PEBKAC ;)

I was under the impression that the [docs here](http://nanoc.ws/doc/rules/#post-processing) return just items that were created or updated by the compiler and pass them to `update_search_index`.

With the code in the nanoc docs, all items would always be passed to `update_search_index`.Wouldn't `@items.each { |item| update_search_index ...` be simpler and achieve the same result? Or if one was to *update* the search index, would `@items.select { |i| i.modified.any? }.each ...` be more correct?

**Comment by ddfreyne** [comment]
The documentation is wrong. I’ll fix! It should be the following:

```ruby
postprocess do
  items.modified.each do |rep|
    update_search_index(rep.path, rep.compiled_content(snapshot: :last))
  end
end
```

The name of the `#modified` method is unfortunate. It’d be good to have `#modified?` on `Item` and/or `ItemRep`, and perhaps rename `#modified` to `#modified_reps`.

**Comment by ddfreyne** [comment]
* `#modified_reps` method: https://github.com/nanoc/nanoc/pull/898
* Documentation fix: https://github.com/nanoc/nanoc.ws/pull/177

**Comment by ddfreyne** [comment]
Also see #899, which is a test for the example on the Nanoc site.

(Would be interesting to have this be evaluated automatically, but that’s not the easiest thing to set up…)

**Comment by agross** [comment]
:+1: Thanks, the docs are much better now and also +1 for renaming the method.
