### ISSUE TITLE
Customizable pruning 

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#883]
Hi,

I actually have a question this time, this is not a problem report ;-)

I have some files that exist in the output directory that are created during compliation, but not by nanoc. For example, I have Sass generate a sourcemap next to the CSS file. Essentially, this is a filter that generated >1 output file (e.g. `output/assets/css/foo-fp123.css` and `output/assets/css/foo-fp123.css.map`).

Sass (Compass) also generates sprite images from nanoc items, so there also might be `output/assets/images/sprites/icons-s123.png`.

The nanoc pruner will delete these files by default because they are not known to nanoc as there's the 1 file in-1 file out convention.

I needed to extended nanoc.yaml like this:

``` yaml
prune:
  auto_prune: true
  exclude: ['sprites', 'css']
```
- Is there an API to mark files as not to be pruned?
- Are you open to extend the pruner excludes to be more flexible?

In my example above _any_ path containing `css` will be exempt from pruning. I'd prefer a callback in the `Rules`, so I can decide on a case-by-case basis and support changing fingerprints, e.g. both `icons-s123.png` and `icons-s456.png` existing.

**Comment by ddfreyne** [comment]
There’s no supported way of having one filter output multiple files. It’s an interesting idea, although I’m having a hard time imagining a workflow that would fit in nicely with Nanoc.

To me, making the pruner more flexible seems like a step in the wrong direction, as it acknowledges a problem and works around it.

Would it be possible for you to have separate filters, in separate reps, each with their own (single) output file?

**Comment by agross** [comment]
This is what the Sass/Compass filter does:

`content/assets/foo.sass` -> filter -> `output/assets/foo.css` + `output/assets/foo.css.map` + `output/assets/sprites/bar-s123.png` + ...

So one item yields > 1 output files, of which nanoc only knows  `output/assets/foo.css`.

> Would it be possible for you to have separate filters

I think I could.

In the most simplistic case this would involve running Sass/Compass multiple times, which is not desirable.

Another option is to run Sass/Compass once (creating all files). `n` other rules with `:text => :binary` filters for `assets/foo.sass` would create the `:sourcemap`, `:first_sprite`, `:second_sprite`, `:nth_sprite` reps from the files created by the Sass/Compass compiler. This would impose an ordering requirement; Compass/Sass would need to be run first. Also, whenever I decide to add a new sprite, I'd need another rep. I'm also not really in favor of this solution.

```ruby
compile '/assets/css/app.sass' do
  # :sass_with_compass is configured to create the sourcemap next to the css file.
  filter :sass_with_compass, config_file: 'compass-config.rb'
  write @item.identifier.without_ext + '.css'
end 

compile '/assets/css/app.sass', rep: :map do
  filter :copy_sass_sourcemap
  write @item.identifier.without_ext + '.css.map'
end 

compile '/assets/css/app.sass', rep: :sprite_1 do
  # looks for newest output/assets/sprites/icon-*.png
  filter :load_sass_sprite, type: 'icons'
  # no idea how to get the fingerprint that Compass assigns (???)
  write '/assets/sprites/icon-???.png'
end 

# etc.
```

Or we "just" could: :smile: 

```ruby
prune do |file|
  file !~ /(sprites|map)/
end
```

**Comment by ddfreyne** [comment]
Moved to nanoc/features#4.
