### ISSUE TITLE
Same Files compiling multiple times in nanoc-4.2.1

### ISSUE THREAD

**Issue by pmalik56** [nanoc/nanoc#886]
Same file iterate inside compile and route block for 5-6 times not sure what is the reason or how nanoc identify whether a file compiled or not? In previous version 3.7.5 it was compiling once for a file.

compile '/**/*' do
 # Same file enter in this blok multiple times
    # Compilation logic here
end

![screenshot from 2016-07-01 16 51 24](https://cloud.githubusercontent.com/assets/4602600/16523433/18401d2a-3fac-11e6-9fbb-5be97635ac5b.png)

**Comment by ddfreyne** [comment]
Can you share the `Rules` file with me so I can take a look?

**Comment by pmalik56** [comment]
Here below is my rules file.

![rules1](https://cloud.githubusercontent.com/assets/4602600/16560666/82b364e8-41fd-11e6-843a-ed42e0d984d0.png)
![rules2](https://cloud.githubusercontent.com/assets/4602600/16560668/870c19ea-41fd-11e6-91d5-ec738356f602.png)

**Comment by ddfreyne** [comment]
Can you show me where you are printing `Compiling /aspa_Adobe_kayttoehdot.pdf`? I can’t see it in the `Rules` file that you posted.

The rules are often evaluated twice (or more) to identify the processing instructions that are used, although the actual compilation is only done once. I expect this to be the reason.

**Comment by pmalik56** [comment]
its printing here 

compile /**/* do 
if it.binary?
puts 'compiling.....' + item.identifier


I have added that pdf intentionally to verify.... otherwise it give a big /tmp/routes.txt file which have multiple same entry.

**Comment by ddfreyne** [comment]
Is this line _always_ printed exactly five times?

Can you share the output of `nanoc compile --debug`?

**Comment by pmalik56** [comment]
![nannoc_compile](https://cloud.githubusercontent.com/assets/4602600/16568681/ca8a54d8-4235-11e6-9fd5-8484d98f1efb.png)

**Comment by agross** [comment]
It might be the case that Nanoc evaluates the `compile` block multiple times, but does not run any filters. After all, `compile` is just a definition of what should happen, not the actual compilation.

Have you tried putting that `puts` debug statement in the actual `Filter#run` method?

**Comment by pmalik56** [comment]
![nanoc_compile_1](https://cloud.githubusercontent.com/assets/4602600/16583345/842f08ca-42bd-11e6-89b1-bec220015dbf.png)
![nanoc_compile_2](https://cloud.githubusercontent.com/assets/4602600/16583350/87830db4-42bd-11e6-9bfb-3644d47f6dbb.png)

**Comment by agross** [comment]
Here's what I did:

* `nanoc create-site test`
* Edited `Rules`:

  ```ruby
  compile '/**/*.html' do
    puts 'rules: ' + item.identifier # added debug statement
    filter :erb # added erb filter for item

    layout '/default.*'
  end

  # NOTE: the default Rules define an erb filter defined for layouts as well!
  ```

* Edited `erb.rb` of the Nanoc gem:

  ```ruby
  def run(content, params = {})
    puts "erb for #{@item.identifier}: #{content[0...10]}" # added debug statement
    ...
  ```

* `rm -rf output; nanoc compile --verbose` prints:

  ```
  Loading site... done
  Compiling site...
  rules: /index.html
  rules: /index.html
  erb for /index.html:
  <h1>A Bra
  erb for /index.html: <!DOCTYPE
        create  [0.01s]  output/index.html
        create  [0.00s]  output/stylesheet.css
  
      | count    min    avg    max     tot
  ----+-----------------------------------
  erb |     2  0.00s  0.00s  0.01s   0.01s
  
  Site compiled in 0.06s.
  ```

So while the rule blocks are evaluated more than once (one may ask why, for example if rules are expensive), the actual erb filtering is just done once *per item*. You'll see two erb filter runs in the output, though:

* First, the item content is filtered by erb as per my updated `compile` rule.
* Second, the layout is filtered by erb, combining the HTML output of `content/index.html` and the erb input of `layouts/default.html`.

While the debug output of Nanoc's erb filter indicates that the `@item.identifier` is the same, the input is not the same (`<h1>A Bra...` of the item vs. `<!DOCTYPE...` of the layout).

**Comment by pmalik56** [comment]
ok now it's clear why it's filtering multiple times. Thanks for your valuable reply.

One more thing I am facing issue on processing static component. Seems like rules are not working on static folder as if it's not processing at all anything inside static. Previously its was working on nanoc 3.7.5 version. And I have some layouts as well in static folder which is getting this error message.

**Nanoc::Int::Errors::UnknownLayout: The site does not have a layout with identifier “/static/components/site-common/analytics/google-tag-manager.erb”**

**Comment by th-h** [comment]
pmalik56 wrote:

> One more thing I am facing issue on processing static component.
> Seems like rules are not working on static folder as if it's not
> processing at all anything inside static. Previously its was working
> on nanoc 3.7.5 version.

Do you mean the static data source? That was removed in nanoc 4.

On the upgrade page, it says:
> If you use the static data source, disable it for now and follow the
> extended upgrade instructions below.

See
<http://nanoc.ws/doc/nanoc-4-upgrade-guide/#upgrading-from-the-static-data-source>.

-thh

**Comment by pmalik56** [comment]
Is there any way to create a new layout of erb which is not in layout directory.

Like I have one component '**site-common**' in static folder which I wise to put inside content directory. But I am not able to create new layout using #new_layout this function.

**Comment by denis-soundcloud** [comment]
Please use the [Nanoc Google Group](https://groups.google.com/forum/#!forum/nanoc) for support. GitHub issues is only for issues.

I’ll close this for now!

**Comment by ddfreyne** [comment]
FYI, this will happen far less in 4.2.4, thanks to #902.
