### ISSUE TITLE
sitemap exclusion rule defaults?

### ISSUE THREAD

**Issue by jm3** [nanoc/nanoc#890]
**Feature Suggestion TL;DR**:
XMLSitemaps should probably filter out non-page assets by default

**Background:**
When setting up my XML sitemap, I had to use to jump through some hoops to exclude all the non-page files:

```ruby
= xml_sitemap :items => @items.reject{ |i| \
     i[:is_hidden] \
  || i.binary? \
  || i.identifier.to_s.match( /.(js|sass|scss|css)$/ ) \
  || i.identifier.to_s.match(/(error.html|sitemap.haml)/) 
  }
```

in order to exclude static assets from appearing in the sitemap, not to mention the sitemap itself. The rules are somewhat confusing because the item identifier matches on the SOURCE name, not the compiled ("routed") name, so e.g. you can't just filter `*.xml` because e.g. the sitemap is actually generated from `sitemap.haml`, etc.

**Comment by ddfreyne** [comment]
I’m a bit hesitant to include defaults, because defaults have a tendency to not be appropriate in all cases, and might cause other kinds of confusion.

Perhaps a solution for this is to ensure the documentation is extensive, and examples are provided.

Note that you can also use `#path` rather than `#identifier` to get the output path, and filter on that (e.g. `i.path =~ /\.html$/`).

What I’d do in your case:

1.  Set `error.sass` and `sitemap.haml` to `is_hidden: true`
2.  Change the `#reject` to a `#select` with this body:

    ```ruby
    @items.select { |i| !i[:is_hidden] && !i.binary? && i.path =~ /\.html$/ }
    ```

(Hopefully, that covers the case that you’re after.)

**Comment by jm3** [comment]
Defaults may not be appropriate in 100% of cases, but that's kinda the point of defaults, right: to Do the Right Thing™ for the majority of users, and let power-users override that with settings that meet their needs. (see also Rails' "Convention over Configuration", the design community's "Principle of least astonishment", etc.).

Maybe you can clue me in: the current behavior puts things like stylesheets into the sitemap. Is that the correct use of a sitemap, in any context? I'm pretty confident that sitemaps are used to point to pages and user-viewable content, like a video or a photo, but not a stylesheet.

**Comment by ddfreyne** [comment]
> Maybe you can clue me in: the current behavior puts things like stylesheets into the sitemap. Is that the correct use of a sitemap, in any context? 

Probably not!

> I'm pretty confident that sitemaps are used to point to pages and user-viewable content, like a video or a photo, but not a stylesheet.

I think limiting the sitemap to contain only `html` files makes sense. It’d be a backwards-incompatible change, though.

Now that I think about the solution that I gave earlier, I believe that it could be simplified to `@items.select { |i| i.path.end_with?('.html') }`. If not a default, it’s definitely worth documenting as a recommendation.

**Comment by ddfreyne** [comment]
The [`XMLSitemap` helper documentation](http://nanoc.ws/doc/reference/helpers/#xmlsitemap) should now be more helpful in setting up an XML sitemap.

I’ve added the “revisit in v5” tag to the ticket, which means I’ll look at it again when Nanoc 5.0 is coming up. In the mean time, I’ll close the ticket, as a change to the behavior of the `XMLSitemap` helper is not possible without breaking compatibility, and thus not possible in Nanoc 4.x.

Let me know what you think!
