### ISSUE TITLE
On Windows we either get UTF-8 or colored output

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#900]
Hi,

I hope you are okay with the amount of issues I recently report. (Let me know if you're not.)

I'm running Windows and Linux in parallel. It seems that Nanoc on Windows cannot output UTF-8 and colors at the same time.

There are several shells/terminals available on my machine and there's also Nanoc's check for the `win32console` gem:

* default Windows 10 terminal, e.g. `conhost.exe` + `cmd.exe`
* ConEmu running `zsh`

| Shell/Terminal | `ENV['LANG'] =~ /UTF-8/i` | `win32console` available | colors enabled | colors working | UTF-8 enabled | UTF-8 working | As expected?  |
| :------------- | :-----------------------: | :----------------------: | :------------: | :------------: | :-----------: | :-----------: | :-----------: |
| cmd.exe        | ✘                         | ✘                        | ✘              | ✘              | ✘             | ✘             | ✔             |
| cmd.exe        | ✘                         | ✔                        | ✔              | ✔              | ✘             | ✘             | ✔             |
| cmd.exe        | ✔                         | ✘                        | ✘              | ✘              | ✔             | ✔             | ✔             |
| cmd.exe        | ✔                         | ✔                        | ✔              | ✔              | ✔             | ✘             | ✘             |
| ConEmu         | ✘                         | ✘                        | ✘              | ✘              | ✘             | ✘             | ✔             |
| ConEmu         | ✘                         | ✔                        | ✔              | ✔              | ✘             | ✘             | ✔             |
| ConEmu         | ✔                         | ✘                        | ✘              | ✘              | ✔             | ✔             | ✔             |
| ConEmu         | ✔                         | ✔                        | ✔              | ✔              | ✔             | ✘             | ✘             |

The most important part is the last column where the rows have ✘es. It seems as if `win32console` breaks UTF-8 output.

Interestingly, with `Nanoc::CLI.setup_cleaning_streams` commented, coloring + UTF-8 always works without requiring `win32console` to be available.

I think it's important to note that Microsoft did some work regarding the console in Windows 10. For example, on Windows 7 Ruby cannot `print 'Loading site… '` correctly (it prints `Loading site.`) whereas on Windows 10 this is not an issue.

**Comment by ddfreyne** [comment]
Thanks for the bug reports, first of all—they’re most definitely useful, as Nanoc keeps getting better.

I’m a bit at a loss at what to do about the issues on Windows, though. I don’t develop on Windows and don’t know enough about this OS in order to support it properly. I’d definitely welcome Windows-specific fixes, however!

**Comment by agross** [comment]
> I’m a bit at a loss at what to do about the issues on Windows, though.

The question is if Nanoc wants to support older Windows versions in the future. I'd say if you drop the check for `win32console` we're fine if the user runs Windows 10 (UTF-8 + colors). Users of Windows 7 will see colors, but no UTF-8. I'd say colors are more important than pretty quotes w.r.t. to seeing what happens behind the scenes (files being created or updated).

**Comment by ddfreyne** [comment]
I’ll remove the win32console support—it’s deprecated (see [its README](https://github.com/luislavena/win32console)) in favour of [ANSICON](https://github.com/adoxa/ansicon) anyway.

**Comment by agross** [comment]
Thanks! And with Windows 10 ANSICON won't even be required anymore :-)

**Comment by ddfreyne** [comment]
Oh, so I closed this ticket without fully verifying that it meets your requirements. Does removing win32console fix the issues you have? (I’d rather not spend much time on getting older versions of Windows to work, especially considering that there’s ANSICON.)

**Comment by agross** [comment]
Yes, everything is good to go :-)

+1 for not supporting older Windows versions
