### ISSUE TITLE
Recompile site time got worse between 4.1.6 and 4.2.3

### ISSUE THREAD

**Issue by agross** [nanoc/nanoc#901]
Hi,

our Nanoc site takes about 90 seconds to compile from scratch with Nanoc 4.2.3. Rebuilding the site without changing any files on disk performance changed rather dramatically between the latest versions of Nanoc. Here are a couple of timings created on a Ubuntu VM using Ruby 2.3.1. The only thing that changed during these runs is the Nanoc version.

| Version | Compile | Recompile  |
|---------|---------|------------|
| 4.1.6   | 56.54s  | 6.01s      |
| 4.2.0   | 57.62s  | 19.64s     |
| 4.2.1   | 57.87s  | 79.55s     |
| 4.2.2   | 58.46s  | 79.44s     |
| 4.2.3   | 86.40s  | 80.25s     |

I wonder how we should go about this. If you want I can get you access to the code, or I can create kcachegrind outputs using ruby-prof while running the recompile. I previsouly had some success with it stripping off 30 seconds by changing a single line of code.

Let me know what you think!

**Comment by ddfreyne** [comment]
I’d definitely be interested in profile information! [This comment](https://github.com/nanoc/nanoc/issues/864#issuecomment-229859029) details an approach with Stackprof, which I found to be quite useful.

**Comment by ddfreyne** [comment]
(Access to the site source would also be quite useful.)

**Comment by ddfreyne** [comment]
Can you see whether #902 improves compilation times?

**Comment by agross** [comment]
And we're back at 6 seconds recompile time :-)

**Comment by ddfreyne** [comment]
Excellent. Weak refs are far less useful than soft refs, as it appears!

**Comment by agross** [comment]
:+1: Thanks for finding the right fix :-)

**Comment by ddfreyne** [comment]
FYI, Nanoc 4.2.4 will have a hidden feature, enabled by setting `NANOC_FEATURE_PROFILER=1` in the env, which adds a `--profile` option to the `compile` command, writing a profile to `tmp/stackprof_profile` using [StackProf](https://github.com/tmm1/stackprof). This’ll make it easier to debug slowdowns.

**Comment by agross** [comment]
Excellent, that sounds great! I haven't looked at stackprof, so just FYI: ruby-prof's cachegrind output is really useable. You can load it into kcachegrind and browse call stacks visually.

**Comment by ddfreyne** [comment]
I haven’t looked into ruby-prof in a while. Last time I looked, it wasn’t compatible with recent Rubies.

**Comment by agross** [comment]
I only started using ruby-prof two weeks ago so things might have changed. While text reporting is nice for things like GH issues, I really like that there is a visual frontend with drilldown functionality: https://kcachegrind.github.io/html/Screenshots.html

Just as a suggestion when text graphviz doesn't cut it. I at last was only able to find the issue using a UI.

In case you're interested, this diff cut 30 secs off our build:

```diff
        def nesting_level(item = @item)
-         item.identifier.components.count
+         item.identifier.to_s.count('/')
        end
```

**Comment by agross** [comment]
> FYI, Nanoc 4.2.4 will have a hidden feature

FYI, stackprof unfortunately doesn't work on Windows. https://github.com/tmm1/stackprof/issues/45

It's not an issue for me as I have a Linux VM handy, but Windows-only users might suffer from it in the future in case you tell them to submit profiling information.
