### ISSUE TITLE
Not creating layouts for erb other than layouts directory

### ISSUE THREAD

**Issue by pmalik56** [nanoc/nanoc#907]
I am trying to create new layout of an erb file which is not inside layouts folder but seems it's not creating a valid layout.

![new_layout](https://cloud.githubusercontent.com/assets/4602600/16729009/86ec0a2c-4772-11e6-85a4-5258957ebe7a.png)
![invalid_layout](https://cloud.githubusercontent.com/assets/4602600/16729045/adebcc7a-4772-11e6-9923-e1e276e0bbf4.png)

**Comment by ddfreyne** [comment]
The `#layouts` method is expected to return a _collection_ of layouts (e.g. an `Array`), rather than a single layout. This is why you get the `undefined method 'each'` error. Let `#layouts` return an array of layouts and this error will go away.
