### ISSUE TITLE
error on layout: default

### ISSUE THREAD

**Issue by jm3** [nanoc/nanoc#908]
i mistakenly used `layout :default` and got the error:

#### NoMethodError: undefined method __nanoc_cleaned_identifier' for :default:

wonder if there might be a better way to signal "no layout found" or the like?

**Comment by ddfreyne** [comment]
That’s indeed a confusing error message. I suppose this is where “duck typing” falls short…

Can you give me a full trace of the error? (crash.log)

**Comment by ddfreyne** [comment]
Fixed in #915.
