### ISSUE TITLE
Improve #atom_feed error message when used in postprocessor

### ISSUE THREAD

**Issue by werthen** [nanoc/nanoc#923]
### Summary

Calling `atom_feed` from the `Blogging` helper in a postprocess block throws an error because `@item` is not defined there.
### Steps to reproduce
1. Call `atom_feed` in a postprocess block
### Expected behavior

It should return the string representation of the atom feed
### Actual behavior

`NoMethodError: undefined method '[]' for nil:NilClass` when compiling. This is because `@item` is not defined at that time
### Crash log

https://gist.github.com/werthen/5cbdfdcc02251cd9b8221ded759f5eb5

**Comment by ddfreyne** [comment]
tl;dr `#atom_feed` is not intended to be run in the postprocessor

The `@item` variable not being available in the postprocessor is expected, as the postprocess does not run in the context of an item. The `atom_feed` method needs an item to obtain some feed details from.

I suggest not running `#atom_feed` in the postprocessor. The postprocessor is mostly intended for running post-compilation steps that Nanoc doesn’t take care of (e.g. updating a search index).

**Comment by werthen** [comment]
I was just trying some stuff out. Maybe there should be a clearer error message though for people trying to do the same?

**Comment by ddfreyne** [comment]
I created nanoc/features/issues/11 for this.
