### ISSUE TITLE
RuntimeError: do not know how to check outdatedness of <Nanoc::LayoutView identifier=/partials/_navbar.erb>

### ISSUE THREAD

**Issue by werthen** [nanoc/nanoc#927]
### Summary

Running the latest version of nanoc, I get this odd error. After compiling the site **exactly 4 times**, the compilation process goes fine without errors.

### Steps to reproduce

I'm not certain how to reproduce this, or what causes this. The site that has this issue is at the following location: https://github.com/ZeusWPI/zeus.ugent.be

### Expected behavior

There should be no error. After the fourth compilation, everything is fine and this error does not show up anymore.

### Actual behavior

There are errors during compilation, but doesn't affect the end result

### Crash log

https://gist.github.com/werthen/5cd94419091590fafe06e7ef2f98d3a1

**Comment by ddfreyne** [comment]
I unfortunately can’t reproduce the problem locally. Can you tell me how you can make zeus.ugent.be cause this crash, starting with a fresh clone?

**Comment by ddfreyne** [comment]
I have a potential fix in the `gh-927-layout-view-dep-tracker` branch. Can you check whether this works for you?

**Comment by werthen** [comment]
A fresh clone of zeus.ugent.be didn't resolve the issue, but the fix in `gh-927-layout-view-dep-tracker` works like a charm!

**Comment by ddfreyne** [comment]
Fixed in #931.
