### ISSUE TITLE
passthrough '/something' unreliable with legacy patterns

### ISSUE THREAD

**Issue by ddfreyne** [nanoc/nanoc#951]
Example:

```ruby
passthrough '/safari-icon.svg'
```

When using non-legacy identifiers and a legacy string pattern type, the above Rules line will _not_ match the `/safari-icon.svg` item.

The culprit is likely in [`compiler_dsl.rb` on line 281](https://github.com/nanoc/nanoc/blob/master/lib/nanoc/rule_dsl/compiler_dsl.rb#L281):

```ruby
new_identifier[/$/] = '/' unless ['*', '/'].include?(identifier[-1, 1])
```

This adds a trailing slash, which is not required.

**Comment by gpakosz** [comment]
I believe the flaw lives in `#create_pattern()` doesn't care which `identifier_type` the data source actually uses
